# SPDX-License-Identifier: Apache-2.0
---

- name: Gather package facts again after the installation phase
  ansible.builtin.package_facts:

- name: Assert - List required SAP Notes
  ansible.builtin.debug:
    var: __sap_hana_preconfigure_sapnotes_versions | difference([''])

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Assert - Include configuration actions for required sapnotes
  ansible.builtin.include_tasks: "sapnote/assert-{{ sap_note_line_item.number }}.yml"
  with_items: "{{ __sap_hana_preconfigure_sapnotes_versions | difference(['']) }}"
  loop_control:
    loop_var: sap_note_line_item
