# SPDX-License-Identifier: Apache-2.0
---

- name: Get info about file /etc/tmpfiles.d/sap.conf
  ansible.builtin.stat:
    path: /etc/tmpfiles.d/sap.conf
  register: __sap_general_preconfigure_register_stat_tmpfiles_sap_conf_assert

- name: Assert that file /etc/tmpfiles.d/sap.conf exists
  ansible.builtin.assert:
    that: __sap_general_preconfigure_register_stat_tmpfiles_sap_conf_assert.stat.exists
    fail_msg: "FAIL: File /etc/tmpfiles.d/sap.conf does not exist!"
    success_msg: "PASS: File /etc/tmpfiles.d/sap.conf exist."
  ignore_errors: "{{ sap_general_preconfigure_assert_ignore_errors | d(false) }}"
