# SPDX-License-Identifier: Apache-2.0
---

- name: Get info about file /etc/security/limits.d/99-sap.conf
  ansible.builtin.stat:
    path: /etc/security/limits.d/99-sap.conf
  register: __sap_general_preconfigure_register_stat_limits_sap_conf_assert

- name: Assert that file /etc/security/limits.d/99-sap.conf exists
  ansible.builtin.assert:
    that: __sap_general_preconfigure_register_stat_limits_sap_conf_assert.stat.exists
    fail_msg: "FAIL: File /etc/security/limits.d/99-sap.conf does not exist!"
    success_msg: "PASS: File /etc/security/limits.d/99-sap.conf exist."
  ignore_errors: "{{ sap_general_preconfigure_assert_ignore_errors | d(false) }}"

- name: Assert that file /etc/security/limits.d/99-sap.conf is a regular file
  ansible.builtin.assert:
    that: __sap_general_preconfigure_register_stat_limits_sap_conf_assert.stat.isreg
    fail_msg: "FAIL: File /etc/security/limits.d/99-sap.conf is not a regular file!"
    success_msg: "PASS: File /etc/security/limits.d/99-sap.conf is a regular file."
  ignore_errors: "{{ sap_general_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_general_preconfigure_register_stat_limits_sap_conf_assert.stat.exists
