# SPDX-License-Identifier: Apache-2.0
---

# Note: firewalld is not contained in ansible_facts.services.
#- name: Check firewalld
#  block:
#    - name: Assert that firewalld is disabled
#      assert:
#        that:
#          - "'stopped' in ansible_facts.packages['firewalld'].state"
#          - "'disabled' in ansible_facts.packages['firewalld'].status"

- name: Check firewalld
  when: "'firewalld' in ansible_facts.packages"
  block:

# Reason for noqa: We need to get the current status only
    - name: Get status of firewalld # noqa command-instead-of-module
      ansible.builtin.command: systemctl status firewalld
      register: __sap_general_preconfigure_register_firewalld_status_assert
      ignore_errors: true
      changed_when: false
      no_log: true

    - name: Assert that firewalld is disabled
      ansible.builtin.assert:
        that: "'/usr/lib/systemd/system/firewalld.service; disabled' in __sap_general_preconfigure_register_firewalld_status_assert.stdout"
        fail_msg: "FAIL: Service 'firewalld' is not disabled!"
        success_msg: "PASS: Service 'firewalld' is disabled."
      ignore_errors: "{{ sap_general_preconfigure_assert_ignore_errors | d(false) }}"

    - name: Assert that firewalld is inactive
      ansible.builtin.assert:
        that: "'inactive (dead)' in __sap_general_preconfigure_register_firewalld_status_assert.stdout"
        fail_msg: "FAIL: Service 'firewalld' is active!"
        success_msg: "PASS: Service 'firewalld' is inactive."
      ignore_errors: "{{ sap_general_preconfigure_assert_ignore_errors | d(false) }}"

- name: Report firewall install status
  ansible.builtin.debug:
    msg: "PASS: Service 'firewalld' is not installed."

  when: "'firewalld' not in ansible_facts.packages"
