# SPDX-License-Identifier: Apache-2.0
---

- name: Enable and start service uuidd
  ansible.builtin.systemd:
    name: uuidd
    enabled: true
    state: started

- name: Enable and start service uuidd.socket
  ansible.builtin.systemd:
    name: uuidd.socket
    enabled: true
    state: started
