# SPDX-License-Identifier: Apache-2.0
---
# 1944799 - SAP HANA Guidelines for SLES Operating System Installation

- name: Configure - Display SAP note number 1944799 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^1944799$') | first).number }}
          (version {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^1944799$') | first).version }}):
           SAP HANA Guidelines for SLES Operating System Installation"

- name: Import tasks from '1944799/installation.yml'
  ansible.builtin.import_tasks: 1944799/installation.yml

# - name: Import tasks from '1944799/configuration.yml'
#   ansible.builtin.import_tasks: 1944799/configuration.yml
