# SPDX-License-Identifier: Apache-2.0
---
- name: Configure - Display SAP note number 3562919 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3562919$') | first).number }}
          (version {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3562919$') | first).version }}): SAP HANA settings for RHEL 10"

- name: Import tasks from '3562919/01-configure-selinux.yml'
  ansible.builtin.import_tasks: 3562919/01-configure-selinux.yml
  when:
    - sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_01|d(false)
    - sap_hana_preconfigure_modify_selinux_labels

- name: Import tasks from '3562919/02-configure-tuned.yml'
  ansible.builtin.import_tasks: 3562919/02-configure-tuned.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_02|d(false)

- name: Import tasks from '3562919/03-disable-abrt-coredumps-kdump.yml'
  ansible.builtin.import_tasks: 3562919/03-disable-abrt-coredumps-kdump.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_03|d(false)

- name: Import tasks from '3562919/04-turn-off-auto-numa-balancing.yml'
  ansible.builtin.import_tasks: 3562919/04-turn-off-auto-numa-balancing.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_04|d(false)

- name: Import tasks from '3562919/05-configure-thp.yml'
  ansible.builtin.import_tasks: 3562919/05-configure-thp.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_05|d(false)

- name: Import tasks from '3562919/06-configure-c-states-for-lower-latency.yml'
  ansible.builtin.import_tasks: 3562919/06-configure-c-states-for-lower-latency.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_06|d(false)

- name: Import tasks from '3562919/07-configure-cpu-governor.yml'
  ansible.builtin.import_tasks: 3562919/07-configure-cpu-governor.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_07|d(false)

- name: Import tasks from '3562919/08-configure-epb.yml'
  ansible.builtin.import_tasks: 3562919/08-configure-epb.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_08|d(false)

- name: Import tasks from '3562919/09-disable-ksm.yml'
  ansible.builtin.import_tasks: 3562919/09-disable-ksm.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_09|d(false)

- name: Import tasks from '3562919/10-increase-pidmax.yml'
  ansible.builtin.import_tasks: 3562919/10-increase-pidmax.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_10|d(false)

- name: Import tasks from '3562919/11-enable-tsx.yml'
  ansible.builtin.import_tasks: 3562919/11-enable-tsx.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_3562919_11|d(false)
