# SPDX-License-Identifier: Apache-2.0
---
- name: Assert - Display SAP note number 2292690 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2292690$') | first).number }}
          (version {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2292690$') | first).version }}): SAP HANA settings for RHEL 7"

- name: Import tasks from '2292690/01-assert-tuned.yml'
  ansible.builtin.import_tasks: 2292690/01-assert-tuned.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_01|d(false)

- name: Import tasks from '2292690/02-assert-auto-numa-balancing.yml'
  ansible.builtin.import_tasks: 2292690/02-assert-auto-numa-balancing.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_02|d(false)

- name: Import tasks from '2292690/03-assert-thp.yml'
  ansible.builtin.import_tasks: 2292690/03-assert-thp.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_03|d(false)

- name: Import tasks from '2292690/04-assert-c-states-for-lower-latency.yml'
  ansible.builtin.import_tasks: 2292690/04-assert-c-states-for-lower-latency.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_04|d(false)

- name: Import tasks from '2292690/05-assert-cpu-governor.yml'
  ansible.builtin.import_tasks: 2292690/05-assert-cpu-governor.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_05|d(false)

- name: Import tasks from '2292690/06-assert-epb.yml'
  ansible.builtin.import_tasks: 2292690/06-assert-epb.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_06|d(false)

- name: Import tasks from '2292690/07-assert-ksm.yml'
  ansible.builtin.import_tasks: 2292690/07-assert-ksm.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_07|d(false)

# Step 8: SELinux is already asserted in role sap_general_preconfigure.

- name: Import tasks from '2292690/09-assert-etc-sudoers.yml'
  ansible.builtin.import_tasks: 2292690/09-assert-etc-sudoers.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_09|d(false)

- name: Import tasks from '2292690/10-assert-ibm-energyscale.yml'
  ansible.builtin.import_tasks: 2292690/10-assert-ibm-energyscale.yml
  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2292690_10|d(false)
