---

- name: Configure 3108316-2
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 2: Configure SELinux"
  tags:
    - sap_general_preconfigure_selinux

- name: Import tasks from '../../RedHat/generic/configure-selinux.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/configure-selinux.yml
  tags:
    - sap_general_preconfigure_selinux
