---

- name: Configure 3108316-4
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 4: Configure Network Time and Date"
  tags:
    - sap_general_preconfigure_network_time_and_date

- name: Start and enable service chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: yes
  tags:
    - sap_general_preconfigure_network_time_and_date
