---

- name: Configure 3108316-9
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 9: Configure Process Resource Limits"
  tags:
    - sap_general_preconfigure_nproc_limits

- name: Import tasks from '../../RedHat/generic/increase-nproc-limits.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/increase-nproc-limits.yml
  tags:
    - sap_general_preconfigure_nproc_limits
