# SPDX-License-Identifier: Apache-2.0
---

# vars file for sap_general_preconfigure

__sap_general_preconfigure_sapnotes_versions:
  - { number: '2369910', version: '18' }
  - { number: '2772999', version: '24' }
  - { number: '1771258', version: '6' }

__sap_general_preconfigure_max_repo_type_x86_64: 'e4s'
__sap_general_preconfigure_max_repo_type_ppc64le: 'e4s'
__sap_general_preconfigure_max_repo_type_s390x: 'eus'

__sap_general_preconfigure_max_repo_type: "{{ lookup('vars', '__sap_general_preconfigure_max_repo_type_' + ansible_architecture) }}"

# RHEL 8 minor releases maximum repo support duration
__sap_general_preconfigure_max_repo_type_string: '{{ __sap_general_preconfigure_max_repo_type }}-'

__sap_general_preconfigure_req_os_repos:
  - rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-baseos-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
  - rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-appstream-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
__sap_general_preconfigure_req_netweaver_repos:
  - rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-sap-netweaver-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
__sap_general_preconfigure_req_hana_repos:
  - rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-sap-solutions-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
__sap_general_preconfigure_req_ha_repos:
  - rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-{{ __sap_general_preconfigure_max_repo_type_string }}rpms

__sap_general_preconfigure_envgroups:
  - "server-product-environment"

__sap_general_preconfigure_packagegroups_x86_64:
  - "@server"

__sap_general_preconfigure_packagegroups_ppc64le:
  - "@server"

__sap_general_preconfigure_packagegroups_s390x:
  - "@server"

__sap_general_preconfigure_packagegroups: "{{ lookup('vars', '__sap_general_preconfigure_packagegroups_' + ansible_architecture) }}"

__sap_general_preconfigure_packages:
  - uuidd
  - libnsl
  - tcsh
  - psmisc
  - nfs-utils
  - bind-utils
# English locale packages are required as per SAP note 2369910:
  - langpacks-en
  - glibc-langpack-en

__sap_general_preconfigure_required_ppc64le:
  - ibm-power-managed-rhel8

# SAP notes 2772999 (setup) and 2812427 (kernel):
__sap_general_preconfigure_min_pkgs:
  - [ 'setup', '2.12.2-2.el8_0.1' ]
  - [ 'kernel', '4.18.0-80.15.1.el8_0' ]

__sap_general_preconfigure_kernel_parameters_default:
  - { name: vm.max_map_count, value: '2147483647' }
  - { name: kernel.pid_max, value: '4194304' }
