# SPDX-License-Identifier: Apache-2.0
---

# vars file for sap_general_preconfigure

__sap_general_preconfigure_sapnotes_versions:
  - { number: '2369910', version: '18' }
  - { number: '2002167', version: '36' }
  - { number: '1771258', version: '6' }
  - { number: '1391070', version: '41' }
  - { number: '0941735', version: '11' }

# RHEL 7 arch strings for setting the repo names:
__sap_general_preconfigure_rhel_7_arch_string_x86_64: 'server'
__sap_general_preconfigure_rhel_7_arch_string_ppc64le: 'for-power-le'
__sap_general_preconfigure_rhel_7_arch_string_ppc64: 'for-power'
__sap_general_preconfigure_rhel_7_arch_string_s390x: 'for-system-z'
# HA repos have a different pattern for ppc64le:
__sap_general_preconfigure_rhel_7_ha_arch_string_x86_64: '{{ __sap_general_preconfigure_rhel_7_arch_string_x86_64 }}'
__sap_general_preconfigure_rhel_7_ha_arch_string_ppc64le: 'server-for-power-le'
__sap_general_preconfigure_rhel_7_ha_arch_string_ppc64: '{{ __sap_general_preconfigure_rhel_7_arch_string_ppc64 }}'
__sap_general_preconfigure_rhel_7_ha_arch_string_s390x: '{{ __sap_general_preconfigure_rhel_7_arch_string_s390x }}'

__sap_general_preconfigure_rhel_7_arch_string: "{{ lookup('vars', '__sap_general_preconfigure_rhel_7_arch_string_' + ansible_architecture) }}"
__sap_general_preconfigure_rhel_7_ha_arch_string: "{{ lookup('vars', '__sap_general_preconfigure_rhel_7_ha_arch_string_' + ansible_architecture) }}"

__sap_general_preconfigure_max_repo_type_x86_64: 'e4s-'
__sap_general_preconfigure_max_repo_type_ppc64le: 'e4s-'
__sap_general_preconfigure_max_repo_type_ppc64: 'eus-'
__sap_general_preconfigure_max_repo_type_s390x: 'eus-'
# There are no eus HA repos for s390x:
__sap_general_preconfigure_max_repo_type_ha_x86_64: '{{ __sap_general_preconfigure_max_repo_type_x86_64 }}'
__sap_general_preconfigure_max_repo_type_ha_ppc64le: '{{ __sap_general_preconfigure_max_repo_type_ppc64le }}'
__sap_general_preconfigure_max_repo_type_ha_ppc64: '{{ __sap_general_preconfigure_max_repo_type_ppc64 }}'
__sap_general_preconfigure_max_repo_type_ha_s390x: ''

__sap_general_preconfigure_max_repo_type: "{{ lookup('vars', '__sap_general_preconfigure_max_repo_type_' + ansible_architecture) }}"
__sap_general_preconfigure_max_repo_type_ha: "{{ lookup('vars', '__sap_general_preconfigure_max_repo_type_ha_' + ansible_architecture) }}"

# RHEL 7 minor releases maximum repo support duration
__sap_general_preconfigure_max_repo_type_string_7_6: '{{ __sap_general_preconfigure_max_repo_type }}'
__sap_general_preconfigure_max_repo_type_string_7_7: '{{ __sap_general_preconfigure_max_repo_type }}'
__sap_general_preconfigure_max_repo_type_string_7_8: ''
__sap_general_preconfigure_max_repo_type_string_7_9: ''
__sap_general_preconfigure_max_repo_type_ha_string_7_6: '{{ __sap_general_preconfigure_max_repo_type_ha }}'
__sap_general_preconfigure_max_repo_type_ha_string_7_7: '{{ __sap_general_preconfigure_max_repo_type_ha }}'
__sap_general_preconfigure_max_repo_type_ha_string_7_8: ''
__sap_general_preconfigure_max_repo_type_ha_string_7_9: ''

__sap_general_preconfigure_max_repo_type_string: "{{ lookup('vars', '__sap_general_preconfigure_max_repo_type_string_' + ansible_distribution_version | replace(\".\", \"_\")) }}"
__sap_general_preconfigure_max_repo_type_ha_string: "{{ lookup('vars', '__sap_general_preconfigure_max_repo_type_ha_string_' + ansible_distribution_version | replace(\".\", \"_\")) }}"

__sap_general_preconfigure_req_os_repos:
  - rhel-{{ ansible_distribution_major_version }}-{{ __sap_general_preconfigure_rhel_7_arch_string }}-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
__sap_general_preconfigure_req_netweaver_repos:
  - rhel-sap-for-rhel-{{ ansible_distribution_major_version }}-{{ __sap_general_preconfigure_rhel_7_arch_string }}-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
__sap_general_preconfigure_req_hana_repos:
  - rhel-sap-hana-for-rhel-{{ ansible_distribution_major_version }}-{{ __sap_general_preconfigure_rhel_7_arch_string }}-{{ __sap_general_preconfigure_max_repo_type_string }}rpms
__sap_general_preconfigure_req_ha_repos:
  - rhel-ha-for-rhel-{{ ansible_distribution_major_version }}-{{ __sap_general_preconfigure_rhel_7_ha_arch_string }}-{{ __sap_general_preconfigure_max_repo_type_ha_string }}rpms

__sap_general_preconfigure_envgroups: ""

__sap_general_preconfigure_packagegroups_x86_64:
  - "@base"
  - "@compat-libraries"
  - "@large-systems"
  - "@network-file-system-client"
  - "@performance"

__sap_general_preconfigure_packagegroups_ppc64le:
  - "@base"
  - "@compat-libraries"

__sap_general_preconfigure_packagegroups_ppc64:
  - "@base"
  - "@compat-libraries"

__sap_general_preconfigure_packagegroups_s390x:
  - "@base"
  - "@compat-libraries"
  - "@large-systems"
  - "@network-file-system-client"
  - "@performance"

__sap_general_preconfigure_packagegroups: "{{ lookup('vars', '__sap_general_preconfigure_packagegroups_' + ansible_architecture) }}"

__sap_general_preconfigure_packages_x86_64:
  - uuidd
  - tcsh
  - psmisc
  - compat-sap-c++-5
  - compat-sap-c++-6
  - compat-sap-c++-7
  - compat-sap-c++-9
  - compat-sap-c++-10

__sap_general_preconfigure_packages_ppc64le:
  - uuidd
  - tcsh
  - psmisc
  - compat-sap-c++-5
  - compat-sap-c++-6
  - compat-sap-c++-7
  - compat-sap-c++-9
  - compat-sap-c++-10

__sap_general_preconfigure_packages_ppc64:
  - uuidd
  - tcsh
  - psmisc
  - compat-sap-c++-5

__sap_general_preconfigure_packages_s390x:
  - uuidd
  - tcsh
  - psmisc

__sap_general_preconfigure_packages: "{{ lookup('vars', '__sap_general_preconfigure_packages_' + ansible_architecture) }}"

# As per https://www14.software.ibm.com/support/customercare/sas/f/lopdiags/home.html :
__sap_general_preconfigure_required_ppc64le:
  - librtas
  - src
  - rsct.core.utils
  - rsct.core
  - rsct.basic
  - rsct.opt.storagerm
  - devices.chrp.base.ServiceRM
  - DynamicRM
  - ncurses-libs
  - readline
  - sqlite
  - sg3_utils
  - libgcc
  - libstdc++
  - zlib
  - iprutils
  - lsvpd
  - libvpd
  - libservicelog
  - servicelog
  - powerpc-utils
  - powerpc-utils-python
  - ppc64-diag
  - IBMinvscout

__sap_general_preconfigure_min_packages_7_2:

__sap_general_preconfigure_min_packages_7_3:

# SAP note 2812427:
__sap_general_preconfigure_min_packages_7_4:
  - [ 'kernel', '3.10.0-693.58.1.el7' ]

# SAP note 2812427:
__sap_general_preconfigure_min_packages_7_5:
  - [ 'kernel', '3.10.0-862.43.1.el7' ]

# SAP note 2812427:
__sap_general_preconfigure_min_packages_7_6:
  - [ 'kernel', '3.10.0-957.35.1.el7' ]

__sap_general_preconfigure_min_packages_7_7:

__sap_general_preconfigure_min_packages_7_8:

__sap_general_preconfigure_min_packages_7_9:

__sap_general_preconfigure_min_pkgs: "{{ lookup('vars', '__sap_general_preconfigure_min_packages_' + ansible_distribution_version | replace(\".\", \"_\")) }}"

# Note: The value for vm.max_map_count of 2147483647 (previously 2000000)
#   is set according to SAP note 900929.
__sap_general_preconfigure_kernel_parameters_default:
  - { name: kernel.sem, value: '1250 256000 100 1024' }
  - { name: vm.max_map_count, value: '2147483647' }
