# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 3108302-2
  ansible.builtin.debug:
    msg: "SAP note 3108302 Step 2: Configure tuned to use profile sap-hana"

- name: Import ../../RedHat/generic/assert-tuned.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-tuned.yml
