# SPDX-License-Identifier: Apache-2.0
---

- name: Configure 3108302-3
  ansible.builtin.debug:
    msg: "SAP note 3108302 Step 3: Disable kdump"

- name: Import ../../RedHat/generic/disable-kdump.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/disable-kdump.yml
