# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "force_latency=70"
- name: Assert 3108302-6
  ansible.builtin.debug:
    msg: "SAP note 3108302 Step 6: Configure C-States for lower latency (x86_64 platform only)"

- name: Import ../../RedHat/generic/assert-c-states-for-lower-latency.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-c-states-for-lower-latency.yml
