# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 3108302-9
  ansible.builtin.debug:
    msg: "SAP note 3108302 Step 9: Disable Kernel samepage merging (KSM)"

- name: Import ../../RedHat/generic/assert-ksm.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-ksm.yml
