# SPDX-License-Identifier: Apache-2.0
---

# Product ID for System Rename
sap_swpm_product_catalog_id: NW_StorageBasedCopy

# Generate inifile.params using sap_swpm Ansible Role
sap_swpm_inifile_list:
  - credentials
  - db_hana_nw_connection
  - nw_other_config
  - nw_central_instance
  - nw_instance_config

# Target host path and file name for the SWPM .SAR file
sap_swpm_swpm_path: /software
sap_swpm_swpm_sar_file_name: SWPM20SP08_2-80003424.SAR

# Target host path and file name for the sapcar installation file
sap_swpm_sapcar_path: /software
sap_swpm_sapcar_file_name: SAPCAR_1010-70006178.EXE

# SAP instance details
sap_swpm_ascs_instance_nr: "02"
sap_swpm_ascs_instance_hostname: "{{ ansible_hostname }}"
sap_swpm_pas_instance_nr: "01"
sap_swpm_pas_instance_hostname: "{{ ansible_hostname }}"

sap_swpm_sid_source: S4H
sap_swpm_sid_target: S20

sap_swpm_sidadm_password: "NewPass$321"
sap_swpm_abap_schema_password: "NewPass$321"
sap_swpm_abap_schema_target: "SAPHANADB"
sap_swpm_db_host_source: "{{ ansible_hostname }}"
sap_swpm_db_type: "hdb"
sap_swpm_db_sid_source: HDB
sap_swpm_db_sid_target: HDB
sap_swpm_db_instance_number: "00"

sap_swpm_fqdn: "poc.cloud"
sap_swpm_hdb_systemdb_system_password: "NewPass$321"
sap_swpm_hdb_system_password: "NewPass$321"
sap_swpm_unicode: "true"
