# SPDX-License-Identifier: Apache-2.0
---

# Detect SAP HANA and SAP NetWeaver software
# Set vars: on each Ansible Task depending on chosen template
sap_install_media_detect_source_directory: "/software"
sap_install_media_detect_source: local_dir
#sap_install_media_detect_swpm: true
#sap_install_media_detect_hostagent: true
#sap_install_media_detect_igs: true
#sap_install_media_detect_kernel: true
#sap_install_media_detect_webdisp: false
#sap_install_media_detect_db: "saphana"

# Override any variable set in sap_swpm_inifile_dictionary
sap_swpm_master_password: NewPass$321
sap_swpm_ddic_000_password: "NewPass$321"
sap_swpm_db_system_password: "NewPass$321"
sap_swpm_db_systemdb_password: "NewPass$321"
sap_swpm_db_schema_abap_password: "NewPass$321"
sap_swpm_db_sidadm_password: "NewPass$321"

# Templates and default values
sap_swpm_templates_install_dictionary:
  sap_system_rename:
    sap_swpm_product_catalog_id: NW_StorageBasedCopy
    sap_swpm_inifile_list:
      - credentials
      - db_hana_nw_connection
      - nw_other_config
      - nw_central_instance
      - nw_instance_config
    sap_swpm_inifile_dictionary:
      sap_swpm_pas_instance_nr: "01"
      sap_swpm_ascs_instance_nr: "02"

  sap_s4hana_2020_onehost_install:
    sap_swpm_product_catalog_id: NW_ABAP_OneHost:S4HANA2020.CORE.HDB.ABAP
    sap_swpm_inifile_list:
      - installation_media
      - credentials
      - db_hana_config
      - db_hana_nw_connection
      - nw_other_config
      - nw_central_instance
      - nw_gateway_webdisp
      - nw_instance_config
      - nw_ports_config
      - unix_user
    sap_swpm_inifile_dictionary:
      sap_swpm_pas_instance_nr: "01"
      sap_swpm_ascs_instance_nr: "02"

  sap_s4hana_2020_onehost_system_restore:
    sap_swpm_product_catalog_id: NW_ABAP_OneHost:S4HANA2020.CORE.HDB.CP
    sap_swpm_inifile_list:
      - installation_media
      - credentials
      - db_hana_config
      - db_hana_restore
      - db_hana_nw_connection
      - nw_other_config
      - nw_central_instance
      - nw_gateway_webdisp
      - nw_instance_config
      - nw_ports_config
      - unix_user
    sap_swpm_inifile_dictionary:
      sap_swpm_pas_instance_nr: "01"
      sap_swpm_ascs_instance_nr: "02"
