# SPDX-License-Identifier: Apache-2.0
---

# Detect SAP HANA and SAP NetWeaver software
sap_install_media_detect_source_directory: "/software"
sap_install_media_detect_source: local_dir
sap_install_media_detect_swpm: true
sap_install_media_detect_hostagent: true
sap_install_media_detect_igs: true
sap_install_media_detect_kernel: true
sap_install_media_detect_webdisp: true

# Product ID for New Installation
sap_swpm_product_catalog_id: NW_Webdispatcher:NW750.IND.PD

# Generate inifile.params using sap_swpm Ansible Role
sap_swpm_inifile_list:
  - swpm_installation_media
  - credentials
  - nw_config_other
  - nw_config_central_services_abap
  - nw_config_primary_application_server_instance
  - nw_config_ports
  - nw_config_webdisp_generic
  - nw_config_host_agent
  - sap_os_linux_user

# Software
sap_swpm_software_path: /software
sap_swpm_sapcar_path: /software
sap_swpm_swpm_path: /software

# NW Passwords
sap_swpm_master_password: "NewPass$321"

# NW Instance Parameters
sap_swpm_sid: WD1
sap_swpm_wd_instance_nr: '03'

# Backend Connection
sap_swpm_wd_system_connectivity: 'false'
sap_swpm_wd_activate_icf: 'false'
sap_swpm_wd_backend_sid: 'S4H'
sap_swpm_wd_backend_ms_http_port: '8001'
sap_swpm_wd_backend_ms_host: "{{ ansible_hostname }}"
sap_swpm_wd_backend_rfc_host: "{{ ansible_hostname }}"
sap_swpm_wd_backend_rfc_instance_nr: "01"
sap_swpm_wd_backend_rfc_client_nr: "000"
sap_swpm_wd_backend_rfc_user: "DDIC"
sap_swpm_wd_backend_rfc_user_password: "NewPass$321"
sap_swpm_wd_backend_scenario_size: '500'
sap_swpm_wd_virtual_host: "{{ ansible_hostname }}"

# SAP Host Agent
sap_swpm_install_saphostagent: 'false'
