# SPDX-License-Identifier: Apache-2.0
---

# Detect SAP HANA and SAP NetWeaver software
sap_install_media_detect_source_directory: "/software"
sap_install_media_detect_source: local_dir
sap_install_media_detect_swpm: true
sap_install_media_detect_hostagent: true
sap_install_media_detect_igs: true
sap_install_media_detect_kernel: true
sap_install_media_detect_webdisp: false
sap_install_media_detect_db: "saphana"

# Product ID for New Installation
sap_swpm_product_catalog_id: NW_ABAP_OneHost:BW4HANA20.CORE.HDB.ABAP

# Generate inifile.params using sap_swpm Ansible Role
sap_swpm_inifile_list:
  - swpm_installation_media
  - swpm_installation_media_swpm2_hana
  - credentials
  - credentials_hana
  - db_config_hana
  - db_connection_nw_hana
  - nw_config_other
  - nw_config_central_services_abap
  - nw_config_primary_application_server_instance
  - nw_config_ports
  - sap_os_linux_user

# Passwords
sap_swpm_master_password: "NewPass$321"
sap_swpm_db_system_password: "NewPass$321"
sap_swpm_db_systemdb_password: "NewPass$321"
sap_swpm_db_schema_abap: "SAPHANADB"
sap_swpm_db_schema_abap_password: "NewPass$321"
sap_swpm_db_sidadm_password: "NewPass$321"
sap_swpm_ddic_000_password: "NewPass$321"

# Instances
sap_swpm_sid: B4H
sap_swpm_pas_instance_nr: "01"
sap_swpm_ascs_instance_nr: "02"
sap_swpm_ascs_instance_hostname: "{{ ansible_hostname }}"
sap_swpm_db_host: "{{ ansible_hostname }}"
sap_swpm_db_sid: HDB
sap_swpm_db_instance_nr: "00"
sap_swpm_fqdn: "poc.cloud"

# Software
sap_swpm_software_path: /software
sap_swpm_sapcar_path: /software
sap_swpm_swpm_path: /software
