---

# ----------------------------- Mandatory parameters -----------------------------  #

# Install directory must contain
#   1.  IMDB_SERVER*SAR file
#   2.  IMDB_*SAR files for all components you wish to install
#   3.  SAPCAR executable
sap_hana_install_software_directory: /software/hana

# Master password
sap_hana_install_master_password: 'NewPass$321'

# Instance details
sap_hana_install_sid: 'HDB'
sap_hana_install_instance_nr: "00"


# ----------------------------- Optional parameters ------------------------------  #

# List of components to be installed, default 'all'
# Components should be comma separated
# sap_hana_install_components: 'all'

# Unix User
# Leave this blank if you want this set automatically by hdblcm
# For production systems, it's highly advisable to set this manually according to your environment's Unix ID policies
# sap_hana_install_userid:
# sap_hana_install_groupid:

# Adjust these accordingly for your installation type
# sap_hana_install_env_type: 'production'
# sap_hana_install_mem_restrict: 'n'
# sap_hana_install_max_mem:
# sap_hana_install_system_restart: 'n'

# Pass some extra arguments to the hdblcm cli, e.g.  --ignore=<check1>[,<check2>]...
# sap_hana_install_hdblcm_extraargs:

# For more optional parameters please consult the documentation or
# Check the file <role path>/defaults/main.yml
