# SPDX-License-Identifier: Apache-2.0
---

sap_storage_dict:
  hanadata:
    name: 'hanadata'
    directory: '/hana/data'
    vg: 'hanadatavg'
    lv: 'hanadatalv'
    pv: ["/dev/sdb"]
    numluns: '1'
    stripesize: ''
# LVM striped partition
  hanalog:
    name: 'hanalog'
    directory: '/hana/log'
    vg: 'hanalogvg'
    lv: 'hanaloglv'
    pv: ["/dev/sdc", "/dev/sdd"]
    numluns: '2'
    stripesize: '32'
  hanashared:
    name: 'hanashared'
    directory: '/hana/shared'
    vg: 'hanasharedvg'
    lv: 'hanasharedlv'
    pv: ["/dev/sde"]
    numluns: '1'
    stripesize: ''
  usrsap:
    name: 'usrsap'
    directory: '/usr/sap'
    vg: 'usrsapvg'
    lv: 'usrsaplv'
    pv: ["/dev/sdf"]
    numluns: '1'
    stripesize: ''
  sapmnt:
    name: 'sapmnt'
    directory: '/sapmnt'
    vg: 'sapmntvg'
    lv: 'sapmntlv'
    pv: ["/dev/sdg"]
    numluns: '1'
    stripesize: ''
