---

# Detect SAP HANA and SAP NetWeaver software
sap_install_media_detect_source_directory: "/software"
sap_install_media_detect_source: local_dir
sap_install_media_detect_swpm: true
sap_install_media_detect_hostagent: true
sap_install_media_detect_igs: true
sap_install_media_detect_kernel: true
sap_install_media_detect_webdisp: false
sap_install_media_detect_db: "saphana"

# Manual set critical software paths
# sap_swpm_sapcar_path: /software/sapcar
# sap_swpm_swpm_path: /software/sap_swpm
# sap_swpm_software_path: /software/sap_download_basket

# NOTE: Values in Dictionary Keys for instance numbers must be string using '01' single quote, otherwise SAP SWPM will crash

sap_swpm_ansible_role_mode: "advanced"

sap_swpm_product_catalog_id: NW_ABAP_OneHost:S4HANA2020.CORE.HDB.ABAP

sap_swpm_inifile_custom_values_dictionary:
  archives.downloadBasket: /software/download_basket
  DiagnosticsAgent.dasidAdmPassword: ''
  HDB_Recovery_Dialogs.backupLocation: ''
  HDB_Recovery_Dialogs.backupName: ''
  HDB_Recovery_Dialogs.sapControlWsdlUrl: "http://{{ ansible_hostname }}:50013/SAPControl?wsdl"
  HDB_Recovery_Dialogs.sidAdmName: hdbadm
  HDB_Recovery_Dialogs.sidAdmPassword: NewPass$321
  HDB_Schema_Check_Dialogs.schemaName: ''
  HDB_Schema_Check_Dialogs.schemaPassword: ''
  HDB_Schema_Check_Dialogs.validateSchemaName: false
  HDB_Software_Dialogs.useMediaCD: false
  hostAgent.sapAdmPassword: ''
  NW_ABAP_Prepare_SUM.prepareSUM: false
  NW_ABAP_Prepare_SUM.startSUM: false
  NW_ABAP_SPAM_Update.SPAMUpdateDecision: false
  NW_ABAP_TMSConfig.configureTMS: true
  NW_checkMsgServer.abapMSPort: 3602
  NW_CI_Instance.ascsInstanceNumber: '02'
  NW_CI_Instance.ascsVirtualHostname: "{{ ansible_hostname }}"
  NW_CI_Instance.ciInstanceNumber: '01'
  NW_CI_Instance.ciMSPort: 3602
  NW_CI_Instance.scsInstanceNumber: ''
  NW_DDIC_Password.ddic000Password: NewPass$321
  NW_getFQDN.FQDN: poc.cloud
  NW_getFQDN.setFQDN: true
  NW_getLoadType.loadType: SAP
  NW_GetMasterPassword.masterPwd: NewPass$321
  NW_GetSidNoProfiles.sid: S4H
  NW_HDB_DB.abapSchemaName: SAPHANADB
  NW_HDB_DB.abapSchemaPassword: NewPass$321
  NW_HDB_getDBInfo.dbhost: "{{ ansible_hostname }}"
  NW_HDB_getDBInfo.dbsid: HDB
  NW_HDB_getDBInfo.instanceNumber: '00'
  NW_HDB_getDBInfo.systemDbPassword: NewPass$321
  NW_HDB_getDBInfo.systemid: HDB
  NW_HDB_getDBInfo.systemPassword: NewPass$321
  NW_HDB_getDBInfo.systemPasswordBackup: ''
  nw_instance_ers.ersInstanceNumber: ''
  nw_instance_ers.ersVirtualHostname: ''
  NW_Recovery_Install_HDB.sidAdmName: hdbadm
  NW_Recovery_Install_HDB.sidAdmPassword: NewPass$321
  NW_SCS_Instance.ascsInstallGateway: true
  NW_SCS_Instance.instanceNumber: '02'
  NW_SCS_Instance.scsVirtualHostname: "{{ ansible_hostname }}"
  nwUsers.sapsysGID: ''
  nwUsers.sidAdmUID: ''
  nwUsers.sidadmPassword: NewPass$321
  storageBasedCopy.hdb.instanceNumber: '00'
  storageBasedCopy.hdb.systemPassword: NewPass$321
