---

- name: Assert that service abrtd is disabled, and inactive or stopped
  ansible.builtin.include_tasks: assert-services.yml
  vars:
    __sap_hana_preconfigure_service_status: "{{ ansible_facts.services['abrtd.service'].status }}"
    __sap_hana_preconfigure_service_state: "{{ ansible_facts.services['abrtd.service'].state }}"
    __sap_hana_preconfigure_packages_and_services_pkg: "{{ __sap_hana_preconfigure_packages_and_services['abrtd']['pkg'] }}"
    __sap_hana_preconfigure_packages_and_services_svc: "{{ __sap_hana_preconfigure_packages_and_services['abrtd']['svc'] }}"
    __sap_hana_preconfigure_packages_and_services_svc_status: "{{ __sap_hana_preconfigure_packages_and_services['abrtd']['svc_status'] }}"
    __sap_hana_preconfigure_packages_and_services_svc_state: "{{ __sap_hana_preconfigure_packages_and_services['abrtd']['svc_state'] }}"
    __sap_hana_preconfigure_packages_and_services_systemd_enabled: "{{ __sap_hana_preconfigure_packages_and_services['abrtd']['systemd_enabled'] }}"
    __sap_hana_preconfigure_packages_and_services_systemd_state: "{{ __sap_hana_preconfigure_packages_and_services['abrtd']['systemd_state'] }}"
