---

- name: Assert that service firewalld is disabled, and inactive or stopped
  ansible.builtin.include_tasks: assert-services.yml
  vars:
    __sap_hana_preconfigure_service_status: "{{ ansible_facts.services['firewalld.service'].status }}"
    __sap_hana_preconfigure_service_state: "{{ ansible_facts.services['firewalld.service'].state }}"
    __sap_hana_preconfigure_packages_and_services_pkg: "{{ __sap_hana_preconfigure_packages_and_services['firewalld']['pkg'] }}"
    __sap_hana_preconfigure_packages_and_services_svc: "{{ __sap_hana_preconfigure_packages_and_services['firewalld']['svc'] }}"
    __sap_hana_preconfigure_packages_and_services_svc_status: "{{ __sap_hana_preconfigure_packages_and_services['firewalld']['svc_status'] }}"
    __sap_hana_preconfigure_packages_and_services_svc_state: "{{ __sap_hana_preconfigure_packages_and_services['firewalld']['svc_state'] }}"
    __sap_hana_preconfigure_packages_and_services_systemd_enabled: "{{ __sap_hana_preconfigure_packages_and_services['firewalld']['systemd_enabled'] }}"
    __sap_hana_preconfigure_packages_and_services_systemd_state: "{{ __sap_hana_preconfigure_packages_and_services['firewalld']['systemd_state'] }}"
