# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "kernel.numa_balancing = 0"
- name: Disable numad
  ansible.builtin.include_tasks: disable-services.yml
  vars:
    line_item: numad
  when: not sap_hana_preconfigure_use_tuned
