---

# Configure tmpfs
- name: Configure - Display SAP note number 0941735 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^0941735$') | first).number }}
          (version {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^0941735$') | first).version }}): Configure tmpfs;
          memtotal_mb = {{ ansible_memtotal_mb }};
          swaptotal_mb = {{ ansible_swaptotal_mb }};
          sap_general_preconfigure_size_of_tmpfs_gb = {{ sap_general_preconfigure_size_of_tmpfs_gb }}"
  tags:
    - always

- name: Import tasks from '../RedHat/generic/configure-tmpfs.yml'
  ansible.builtin.import_tasks: ../RedHat/generic/configure-tmpfs.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_0941735 | d(false)
  tags:
    - sap_general_preconfigure_0941735
    - sap_general_preconfigure_configure_tmpfs
