# SPDX-License-Identifier: Apache-2.0
---

- name: Configure - Display SAP note number 3562909 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3562909$') | first).number }}
          (version {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3562909$') | first).version }}): Configure RHEL 10"
  tags:
    - always

- name: Import tasks from '3562909/02-configure-selinux.yml'
  ansible.builtin.import_tasks: 3562909/02-configure-selinux.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_02 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_02

- name: Import tasks from '3562909/03-configure-hostname.yml'
  ansible.builtin.import_tasks: 3562909/03-configure-hostname.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_03 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_03

- name: Import tasks from '3562909/04-configure-network-time-and-date.yml'
  ansible.builtin.import_tasks: 3562909/04-configure-network-time-and-date.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_04 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_04

- name: Import tasks from '3562909/05-configure-firewall.yml'
  ansible.builtin.import_tasks: 3562909/05-configure-firewall.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_05 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_05

- name: Import tasks from '3562909/06-configure-uuidd.yml'
  ansible.builtin.import_tasks: 3562909/06-configure-uuidd.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_06 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_06

- name: Import tasks from '3562909/07-configure-tmpfs.yml'
  ansible.builtin.import_tasks: 3562909/07-configure-tmpfs.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_07 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_07

- name: Import tasks from '3562909/08-configure-linux-kernel-parameters.yml'
  ansible.builtin.import_tasks: 3562909/08-configure-linux-kernel-parameters.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_08 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_08

- name: Import tasks from '3562909/09-configure-process-resource-limits.yml'
  ansible.builtin.import_tasks: 3562909/09-configure-process-resource-limits.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_09 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_09

- name: Import tasks from '3562909/10-configure-systemd-tmpfiles.yml'
  ansible.builtin.import_tasks: 3562909/10-configure-systemd-tmpfiles.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_3562909_10 | d(false)
  tags:
    - sap_general_preconfigure_3562909
    - sap_general_preconfigure_3562909_10
