# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Install Media Detect - Rename - Add 'zip' extension to zip files
  ansible.builtin.include_tasks: ./add_zip_extension_loop_block.yml
  loop: "{{ __sap_install_media_detect_fact_zip_files_without_extension | d([]) }}"
  loop_control:
    loop_var: line_item

- name: SAP Install Media Detect - Rename - Add 'exe' extension to self-extracting rar files
  ansible.builtin.include_tasks: ./add_exe_extension_loop_block.yml
  loop: "{{ __sap_install_media_detect_fact_exe_files_without_extension | d([]) }}"
  loop_control:
    loop_var: line_item

- name: SAP Install Media Detect - Rename - Add 'rar' extension to rar files
  ansible.builtin.include_tasks: ./add_rar_extension_loop_block.yml
  loop: "{{ __sap_install_media_detect_fact_rar_files_without_extension | d([]) }}"
  loop_control:
    loop_var: line_item
