---
# BEGIN: Default Variables for sap_general_preconfigure

# sap_general_preconfigure_config_all: (not defined by default)
# If set to `false`, the role will only execute or verify the installation or configuration steps of SAP notes.
# Default is to perform installation and configuration steps.

# sap_general_preconfigure_installation: (not defined by default)
# If `sap_general_preconfigure_config_all` is set to `false`, set this variable to `true` to perform only the
# installation steps of SAP notes.

# sap_general_preconfigure_configuration: (not defined by default)
# If `sap_general_preconfigure_config_all` is set to `false`, set this variable to `true` to perform only the
# configuration steps of SAP notes for which the corresponding SAP notes parameters have been set to `true`.
# Example: See README.md

sap_general_preconfigure_assert: false
# If set to `true`, the role will run in assertion mode instead of the default configuration mode.

sap_general_preconfigure_assert_ignore_errors: false
# In assertion mode, the role will abort when encountering any assertion error.
# If this parameter is set to `false`, the role will *not* abort when encountering an assertion error.
# This is useful if the role is used for reporting a system's SAP notes compliance.

sap_general_preconfigure_system_roles_collection: 'fedora.linux_system_roles'
# Set which Ansible Collection to use for the Linux System Roles.
# For community/upstream, use 'fedora.linux_system_roles'
# For the RHEL System Roles for SAP, or for Red Hat Automation Hub, use 'redhat.rhel_system_roles'
# Possible Values:
# - fedora.linux_system_roles
# - redhat.rhel_system_roles

sap_general_preconfigure_enable_repos: false
# Set to `true` if you want the role to enable the repos as configured by the following repo related parameters.
# The default is `false`, meaning that the role will not enable repos.

sap_general_preconfigure_use_netweaver_repos: true
# Set to `false` if you want the role to not enable the SAP NetWeaver repo(s).
# The default is `true`, meaning that the role will enable the SAP NetWeaver repo(s).
# Only valid if `sap_general_preconfigure_enable_repos` is set to `true`.

sap_general_preconfigure_use_hana_repos: true
# Set to `false` if you want the role to not enable the SAP HANA repo(s).
# The default is `true`, meaning that the role will enable the SAP HANA repo(s).
# Only valid if `sap_general_preconfigure_enable_repos` is set to `true`.

sap_general_preconfigure_use_ha_repos: true
# Set to `false` if you want the role to not enable the high availability repo(s).
# The default is `true`, meaning that the role will enable the high availability repo(s).
# Only valid if `sap_general_preconfigure_enable_repos` is set to `true`.

sap_general_preconfigure_disable_all_other_repos: true
# Set to `false` if you want the role to not disable all repos before enabling the desired ones as configured above.
# The default is `true`, meaning that the role will disable all repos before enabling the desired ones.
# Only valid if `sap_general_preconfigure_enable_repos` is set to `true`.

# sap_general_preconfigure_req_repos: (not defined by default)
# If you want to provide your own list of repos (e.g. on cloud systems), set this variable accordingly.
# Otherwise, the RHEL default repo names with the maximum support duration for the RHEL minor release are chosen automatically
# (e.g. normal repos for RHEL 8.3, e4s repos for RHEL 8.4).
# Example: See README.md

sap_general_preconfigure_set_minor_release: false
# Set to `true` if you want the role to set the RHEL minor release, which is required for SAP HANA. Default is `false`.
# If you set the RHEL minor release, then you must also use the `eus` or `e4s` repos.

sap_general_preconfigure_packagegroups: "{{ __sap_general_preconfigure_packagegroups }}"
# The name of the software package group to install.
# The default for this parameter is set in the vars file which corresponds to the detected OS version.
# Example: See README.md

sap_general_preconfigure_envgroups: "{{ __sap_general_preconfigure_envgroups }}"
# The name of the software environment group to check.
# The default for this parameter is set in the vars file which corresponds to the detected OS version.
# Example: See README.md

sap_general_preconfigure_packages: "{{ __sap_general_preconfigure_packages }}"
# The list of packages to install.
# The default for this variable is set in the vars file which corresponds to the detected OS version.

sap_general_preconfigure_min_package_check: true
# The default is to install or check if the minimum package versions are installed as defined in the vars files.
# Set to `false` if you do not install or check these minimum package versions.

sap_general_preconfigure_install_ibm_power_tools: true
# Set this parameter to `false` to not install the IBM Power Systems service and productivity tools.
# See also SAP note 2679703.

sap_general_preconfigure_add_ibm_power_repo: true
# Set this parameter to `false` if you do not want to add the IBM Power tools repository (e.g. because the packages
# are already available on the local network). The IBM Power Systems service and productivity tools will only
# be installed if the variable `sap_general_preconfigure_install_ibm_power_tools` is set to `true`, which is the default.

sap_general_preconfigure_ibm_power_repo_url: 'https://public.dhe.ibm.com/software/server/POWER/Linux/yum/download/ibm-power-repo-latest.noarch.rpm'
# URL for the IBM Power Systems service and productivity tools, see https://www.ibm.com/support/pages/service-and-productivity-tools

sap_general_preconfigure_update: false
# By default, the role will not update the system, for avoiding an unintentional minor OS release update.
# Set this parameter to `true` if you want to update your system to the latest package versions.
# When using SAP HANA, make sure to set the release lock properly so the minor OS release will be one of
# those for which SAP HANA is supported. See also `sap_general_preconfigure_set_minor_release`.

sap_general_preconfigure_reboot_ok: false
# Set to `true` if you want to perform a reboot at the end of the role, if necessary.

sap_general_preconfigure_fail_if_reboot_required: true
# If `sap_general_preconfigure_reboot_ok` is set to `false`, which is the default, a reboot requirement should not
# remain unnoticed. For this reason, we let the role fail. Set this parameter to `false` to override this behavior.
# Can be useful if you want to implement your own reboot handling.

sap_general_preconfigure_selinux_state: 'permissive'
# One of the SELinux states to be set on the system.
# Possible Values:
# - enforcing
# - permissive
# - disabled

sap_general_preconfigure_create_directories: true
# Set to `false` if you do not want the SAP directories to be created by the role.
# The SAP directories will always be created if `sap_general_preconfigure_modify_selinux_labels`
# (see below) is set to `true`, no matter how `sap_general_preconfigure_create_directories` is set.

sap_general_preconfigure_sap_directories:
  - /usr/sap
# List of SAP directories to be created.

sap_general_preconfigure_modify_selinux_labels: true
# Set to `false` if you do not want to modify the SELinux labels for the SAP directories set
# in variable `sap_general_preconfigure_sap_directories`.

sap_general_preconfigure_size_of_tmpfs_gb: "{{ ((0.75 * (ansible_memtotal_mb + ansible_swaptotal_mb)) / 1024) | round | int }}"
# The size of the tmpfs in GB. The formula used here is mentioned in SAP note 941735.

sap_general_preconfigure_modify_etc_hosts: true
# Set to `false` if you do not want the role to modify the `/etc/hosts` file.

sap_general_preconfigure_etc_sysctl_sap_conf: '/etc/sysctl.d/sap.conf'
# The file name of the sysctl config file to be used

sap_general_preconfigure_kernel_parameters: "{{ __sap_general_preconfigure_kernel_parameters_default }}"
# The Linux kernel parameters to use. By default, these are taken from the vars file.
# The default for this parameter is set in the vars file which corresponds to the detected OS version.
# Example: See README.md

sap_general_preconfigure_max_hostname_length: '13'
# The maximum length of the hostname. See SAP note 611361.

# If "global" variables are set, use those. If not, default to the values from gather_facts:
sap_general_preconfigure_ip: "{{ sap_ip | d(ansible_default_ipv4.address) }}"
# The IPV4 address to be used for updating or checking `/etc/hosts` entries.

sap_general_preconfigure_hostname: "{{ sap_hostname | d(ansible_hostname) }}"
# The hostname to be used for updating or checking `/etc/hosts` entries.

sap_general_preconfigure_domain: "{{ sap_domain | d(ansible_domain) }}"
# The DNS domain name to be used for updating or checking `/etc/hosts` entries.

# sap_general_preconfigure_db_group_name: (not defined by default)
# Use this variable to specify the name of the RHEL group which is used for the database processes.
# If defined, it will be used to configure process limits as per step
# Configuring Process Resource Limits
# Example: See README.md

# END: Default Variables for sap_general_preconfigure
