# SPDX-License-Identifier: Apache-2.0
---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Ensure required packages for SAP NetWeaver are installed
  ansible.builtin.package:
    state: present
    name: "{{ sap_netweaver_preconfigure_packages }}"

- name: Ensure required packages for Adobe Document Services are installed, x86_64 only
  ansible.builtin.package:
    state: present
    name: "{{ __sap_netweaver_preconfigure_adobe_doc_services_packages }}"
  when:
    - ansible_architecture == 'x86_64'
    - sap_netweaver_preconfigure_use_adobe_doc_services
