# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 3562909-9
  ansible.builtin.debug:
    msg: "SAP note 3562909 Step 9: Configure Process Resource Limits"
  tags:
    - sap_general_preconfigure_nproc_limits

- name: Import tasks from '../../RedHat/generic/assert-limits-conf-file.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-limits-conf-file.yml
  tags:
    - sap_general_preconfigure_nproc_limits

- name: Import tasks from '../../RedHat/generic/assert-nproc-limits.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-nproc-limits.yml
  tags:
    - sap_general_preconfigure_nproc_limits
