# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: IBM Lab for SAP Solutions, Red Hat for SAP Community of Practice
  description: Standalone installation of SAP Host Agent on Linux OS (RHEL, SLES)
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [ 7, 8, 9 ]
    - name: SLES
      versions: [ 15SP3 ]
  galaxy_tags: [ 'sap', 'rhel', 'redhat', 'sles', 'suse' ]
dependencies: []
