---

# Inherit from global parameters, if they exist
sap_storage_setup_host_type: "{{ sap_host_type }}"
sap_storage_setup_sid: "{{ sap_system_sid }}"

# By default do not look for multipath devices.
# When enabled, this includes
# - installation of necessary packages
# - enabling of related services
sap_storage_setup_multipath_enable_and_detect: false

# The instance_nr parameters are required for references at the bottom.
sap_storage_setup_nwas_abap_ascs_instance_nr: '00'
sap_storage_setup_nwas_abap_ers_instance_nr: '10'
sap_storage_setup_nwas_abap_pas_instance_nr: '01'
sap_storage_setup_nwas_abap_aas_instance_nr: '11'
sap_storage_setup_nwas_java_scs_instance_nr: '20'
sap_storage_setup_nwas_java_ers_instance_nr: '30'
sap_storage_setup_nwas_java_ci_instance_nr: '21'

# Directories use static prefixes /SYS, /ASCS, /ERS, /D, /SCS, /J
# Required File Systems and Directories - SAP Directories
# https://help.sap.com/docs/SLTOOLSET/39c32e9783f6439e871410848f61544c/d8d6abf3dceb45b9aa7b5f4e44b0d4b4.html?version=CURRENT_VERSION_SWPM20
#
# Predefined prefixes during SAP SWPM installation:
# - NWAS ABAP ASCS uses ASCS<Instance_Number>
# - NWAS ABAP ERS uses ERS<Instance_Number>
# - NWAS ABAP PAS/AAS uses D<Instance_Number>
# - NWAS JAVA SCS uses SCS<Instance_Number>
# - NWAS JAVA ERS uses ERS<Instance_Number>
# - NWAS JAVA AS uses J<Instance_Number>
# - NWAS WebDispatcher uses W<Instance_Number>

#----------------------------------------------------------#

sap_storage_setup_nfs_filesystem_type: nfs4
sap_storage_setup_nfs_mount_options: defaults
sap_storage_setup_local_filesystem_type: xfs

# subdirectories as per SAP requirements

sap_storage_setup_nfs_dirs_usr_sap:
  all:
    - "{{ sap_storage_setup_sid }}/SYS"
  nwas_abap_aas:
    - "{{ sap_storage_setup_sid }}/D{{ sap_storage_setup_nwas_abap_aas_instance_nr }}"
  nwas_abap_ascs:
    - "{{ sap_storage_setup_sid }}/ASCS{{ sap_storage_setup_nwas_abap_ascs_instance_nr }}"
  nwas_abap_ers:
    - "{{ sap_storage_setup_sid }}/ERS{{ sap_storage_setup_nwas_abap_ers_instance_nr }}"
  nwas_abap_pas:
    - "{{ sap_storage_setup_sid }}/D{{ sap_storage_setup_nwas_abap_pas_instance_nr }}"
  nwas_java_ci:
    - "{{ sap_storage_setup_sid }}/J{{ sap_storage_setup_nwas_java_ci_instance_nr }}"
  nwas_java_ers:
    - "{{ sap_storage_setup_sid }}/ERS{{ sap_storage_setup_nwas_java_ers_instance_nr }}"
  nwas_java_scs:
    - "{{ sap_storage_setup_sid }}/SCS{{ sap_storage_setup_nwas_java_scs_instance_nr }}"

#####
#### Legacy code - retain vars for commented out code, until decision on specific activities for each Cloud
######

sap_storage_setup_cloud_type: 'generic'
# generic | az | aws

# Azure variables

sap_storage_az_imds_json:
sap_storage_az_imds_url: 'http://169.254.169.254/metadata/instance/compute?api-version=2020-09-01'
sap_storage_az_vmsize_url: 'http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2017-08-01&format=text'

sap_storage_az_vmsize:

sap_storage_az_lun: '/dev/disk/azure/scsi1/lun'

# AWS variables

# should probably put into a platform specific vars file, to be included and overwriting the default
#sap_storage_setup_aws_nfs_options: 'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,acl'

sap_storage_aws_imds_url:
sap_storage_aws_vmsize_url:

sap_storage_aws_vmsize:

# IBM Cloud variables
#
