---

# vars file for sap_netweaver_preconfigure

__sap_netweaver_preconfigure_sapnotes:
  - "2526952"
  - "3119751"

__sap_netweaver_preconfigure_sapnotes_versions:
  - { number: '2526952', version: '5' }
  - { number: '3119751', version: '13' }

__sap_netweaver_preconfigure_packages:
  - tuned-profiles-sap

__sap_netweaver_preconfigure_adobe_doc_services_packages:
  - autoconf.noarch
  - automake.noarch
  - cyrus-sasl.x86_64
  - expat.x86_64
  - fontconfig.x86_64
  - glibc-devel.i686
  - keyutils-libs.x86_64
  - krb5-libs.x86_64
  - libcom_err.x86_64
  - libidn2.x86_64
  - libselinux.x86_64
  - libssh2.x86_64
  - libxcb.i686
  - nspr.x86_64
  - nss.x86_64
  - nss-softokn.x86_64
  - nss-softokn-freebl.x86_64
  - nss-util.x86_64
  - openldap.x86_64
  - openssl.x86_64
  - zlib.x86_64
  - libstdc++.i686
  - libX11.i686
  - libXau.i686
  - glibc.i686
  - libstdc++.i686
  - libgcc.i686
  - libuuid.i686
