# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 15

__sap_netweaver_preconfigure_sapnotes_versions: []
  # 2578899 - SUSE Linux Enterprise Server 15: Installation Note
  # Already included in sap_general_preconfigure

  # SAP Notes applicable to NETWEAVER saptune solution:
  # 941735 1771258 2578899 2993054 1656250 900929

  # 941735 - SAP memory management system for 64-bit Linux systems
  # kernel.shmall, kernel.shmmax are already default.
  # ShmFileSystemSizeMB, VSZ_TMPFS_PERCENT are optional parameters for /dev/shm

  # 1771258 - Linux: User and system resource limits
  # Limits are created by applying saptune solution or predefined in sapconf.

  # 900929 - Linux: STORAGE_PARAMETERS_WRONG_SET and "mmap() failed"
  # Parameter vm.max_map_count=2147483647 is already default value.

__sap_netweaver_preconfigure_patterns:
  - sap_server
  - sap-nw

__sap_netweaver_preconfigure_packages:
  # Patterns are not included in package list
  # Ansible package module skips recommended packages resulting in discrepancies.

  # Recommended packages
  - tcsh
  - acl
  - insserv-compat  # Support for System V init scripts
  - libstdc++6
  - libatomic1
  - libgcc_s1

  # Recommended for System monitoring
  - cpupower
  - "{{ 'libcpupower0' if ansible_distribution_version is version('15.6', '<') else 'libcpupower1' }}"
  - libsensors4

  # Additional packages
  - nfs-utils
  - bind-utils
  - procmail


# SLES_SAP is using saptune, but SLES is using sapconf.
__sap_netweaver_preconfigure_use_saptune: true
