# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 2777782-1
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 1: Configure SELinux"

- name: Import ../../RedHat/generic/assert-selinux.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-selinux.yml
