# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 2777782-3
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 3: Disable ABRT, core dumps, and kdump"

- name: Import ../../RedHat/generic/assert-abrtd.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-abrtd.yml

- name: Import ../../RedHat/generic/assert-abrt-ccpp.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-abrt-ccpp.yml

- name: Import ../../RedHat/generic/assert-coredumps.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-coredumps.yml

- name: Import ../../RedHat/generic/assert-kdump.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-kdump.yml
