# SPDX-License-Identifier: Apache-2.0
---

- name: Configure 2777782-3
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 3: Disable ABRT, core dumps, and kdump"

- name: Import ../../RedHat/generic/disable-abrtd.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/disable-abrtd.yml

- name: Import ../../RedHat/generic/disable-abrt-ccpp.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/disable-abrt-ccpp.yml

- name: Import ../../RedHat/generic/disable-coredumps.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/disable-coredumps.yml

- name: Import ../../RedHat/generic/disable-kdump.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/disable-kdump.yml
