# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "transparent_hugepages=never"
- name: Configure 2777782-5
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 5: Disable Transparent Hugepages (THP)"

- name: Import ../../RedHat/generic/configure-thp.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/configure-thp.yml
