# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 2777782-9
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 9: Disable Kernel samepage merging (KSM)"

- name: Import ../../RedHat/generic/assert-ksm.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-ksm.yml
