# SPDX-License-Identifier: Apache-2.0
---

- name: Configure 2777782-9
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 9: Disable Kernel samepage merging (KSM)"

- name: Import ../../RedHat/generic/disable-ksm.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/disable-ksm.yml
