# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 2777782-10
  ansible.builtin.debug:
    msg: "SAP note 2777782 Step 10: Increase kernel.pidmax"

- name: Notify about where 'kernel.pidmax' is asserted
  ansible.builtin.debug:
    msg: "INFO: Kernel parameter 'kernel.pid_max' is already asserted by role 'sap_general_preconfigure' if necessary."
