# SPDX-License-Identifier: Apache-2.0
---

# define variables here that will not change
# Those are valid for all OS
#

# Default parameter file for sysctl settings according to SAP NOTE 2382421
__sap_hana_preconfigure_etc_sysctl_saphana_conf: '/etc/sysctl.d/sap_hana.conf'

# Default parameter file for sysctl settings according to SAP NOTE 3024346
__sap_hana_preconfigure_etc_sysctl_netapp_hana_conf: '/etc/sysctl.d/91-NetApp-HANA.conf'

# dummy entries for passing the arg spec validation:
__sap_hana_preconfigure_supported_rhel_minor_releases: []
__sap_hana_preconfigure_req_repos_redhat_7_x86_64: []
__sap_hana_preconfigure_req_repos_redhat_7_ppc64le: []
__sap_hana_preconfigure_req_repos_redhat_8_x86_64: []
__sap_hana_preconfigure_req_repos_redhat_8_ppc64le: []
__sap_hana_preconfigure_req_repos_redhat_9_x86_64: []
__sap_hana_preconfigure_req_repos_redhat_9_ppc64le: []
__sap_hana_preconfigure_packages: []
__sap_hana_preconfigure_patterns: []
__sap_hana_preconfigure_kernel_parameters_default: []
__sap_hana_preconfigure_kernel_parameters_default_ppc64le: []
__sap_hana_preconfigure_ibm_power_repo_url: ''
