---

# required SAP Notes for SLES 15

__sap_hana_preconfigure_sapnotes:
#        - "{% if ansible_architecture == 'ppc64le' %}2055470{% endif %}"
  - "1944799"
  - "2578899"
  - "1275776"
  - "2684254"

__sap_hana_preconfigure_min_pkgs:

__sap_hana_preconfigure_packages:
    # SAP NOTE 2772999
    # SAP NOTE 2292690
    # SAP NOTE 22455582
#
#   libtool ltdl: https://answers.sap.com/questions/476177/hana-db-installation-ended-with-exit-code-127.html
#   it is required since HANA 2 SPS 03, and as such installed in general

#
# Intel needs additional packages over x86_64
#

__sap_hana_preconfigure_grub_file: /tmp/grub

# SLES_SAP is using saptune, but SLES is using sapconf.
# Default value true runs saptune, but installation.yml auto-detects base product and adjusts.
__sap_hana_preconfigure_run_saptune: true
