# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 16

__sap_hana_preconfigure_sapnotes_versions: []

__sap_hana_preconfigure_min_pkgs:

__sap_hana_preconfigure_patterns:
  - sles_minimal_sap
  - sles_sap_DB

__sap_hana_preconfigure_packages:
  # Patterns are not included in package list
  # Ansible package module skips recommended packages resulting in discrepancies.

  # Recommended packages
  - tcsh
  - psmisc

  # 2578899 is not updated for SLES 16 yet.
  - uuidd
  - sysstat
  - sysctl-logger

  # 3139184 - Linux: systemd integration for sapstartsrv and SAP Host Agent
  - polkit

  # Recommended for System monitoring
  - cpupower
  - libcpupower1
  - libsensors4

  # Additional packages
  - nfs-utils
  - bind-utils

# SLES_SAP is using saptune, but SLES is using sapconf.
__sap_hana_preconfigure_use_saptune: true
