---

- name: Assert 2002167-4
  ansible.builtin.debug:
    msg: "SAP note 2002167 Step 4: Linux Kernel Parameters"
  tags:
    - sap_general_preconfigure_kernel_parameters

- name: Import tasks from '../../RedHat/generic/assert-kernel-parameters.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-kernel-parameters.yml
  tags:
    - sap_general_preconfigure_kernel_parameters
