# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  namespace: community
  author: Red Hat for SAP Community of Practice, Markus Koch, Thomas Bludau, Bernd Finger, Than Ngo, Rainer Leber
  description: Prepare Linux OS (RHEL, SLES) with specific configurations required for SAP HANA installation
  company: Red Hat, Inc.
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [ 7, 8, 9 ]
    - name: SLES
      versions: [ 15SP3 ]
  galaxy_tags: [ 'sap', 'hana', 'rhel', 'redhat', 'sles', 'suse' ]
dependencies: []
