# SPDX-License-Identifier: Apache-2.0
---

- name: Execute task to update GRUB entries
  ansible.builtin.include_tasks:
    file: ../../SLES/generic/grub_update.yml
  vars:
    __sap_hana_preconfigure_grub_cmdline: "{{ __sap_hana_preconfigure_grub_cmdline_2684254 }}"
  when: __sap_hana_preconfigure_grub_cmdline | length > 0


# Verify SAP Note before block and revert if found invalid
- name: Verify SAP note 2684254 before changes
  ansible.builtin.command:
    cmd: saptune note verify 2684254
  register: __sap_hana_preconfigure_verify_2684254_before
  changed_when: false
  ignore_errors: true
  when: __sap_hana_preconfigure_use_saptune | d(true)

- name: Apply SAP note 2684254 using saptune
  when:
    - __sap_hana_preconfigure_use_saptune | d(true)
    - __sap_hana_preconfigure_verify_2684254_before.rc != 0
  block:
    - name: Revert SAP note 2684254
      ansible.builtin.command:
        cmd: saptune note revert 2684254
      changed_when: true

    - name: Apply SAP note 2684254
      ansible.builtin.command:
        cmd: saptune note apply 2684254
      changed_when: true

    - name: Verify SAP note 2684254 after changes
      ansible.builtin.command:
        cmd: saptune note verify --show-non-compliant 2684254
      register: __sap_hana_preconfigure_verify_2684254_after
      changed_when: false
      ignore_errors: true

    - name: Display error if saptune verify failed
      ansible.builtin.debug:
        msg: |
          {{ __sap_hana_preconfigure_verify_2684254_after.stdout_lines }}
          {{ __sap_hana_preconfigure_verify_2684254_after.stderr_lines }}
      when:
        __sap_hana_preconfigure_verify_2684254_after.rc != 0


- name: Configuration changes without saptune
  when: not __sap_hana_preconfigure_use_saptune | d(true)
  block:

    # The KSM feature helps reduce physical memory overhead by detecting memory pages with identical content.
    # The feature is useful for VMs, but the space-time tradeoff does not pay off for HDB instances not running in VMs.
    # Kernel samepage merging is usually deactivated by default.
    - name: Disable Kernel samepage merging (KSM)
      ansible.builtin.lineinfile:
        dest: /etc/init.d/boot.local
        mode: "0744"
        line: echo 0 > /sys/kernel/mm/ksm/run
        state: present
        create: true


- name: "(Optional) Set governor to performance - Intel"
  ansible.builtin.debug:
    msg: |
      SAP Recommends setting governor to performance mode on physical Intel servers.
      This setting is not mandatory for smaller systems, where energy savings are of consideration.

      You can configure it using following methods:
      - Execute: saptune note apply 2684254
      - Append command to /etc/init.d/boot.local: cpupower frequency-set -g performance

      Result can be validated by executing: cpupower frequency-info


- name: "(Optional) Set Energy Performance Bias to performance - Intel"
  ansible.builtin.debug:
    msg: |
      SAP Recommends setting Energy Performance Bias to performance mode on physical Intel servers.
      This setting is not mandatory for smaller systems, where energy savings are of consideration.

      You can configure it using following methods:
      - Execute: saptune note apply 2684254
      - Append command to /etc/init.d/boot.local: cpupower set -b 0

      Result can be validated by executing: cpupower info
