# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 2292690-1
  ansible.builtin.debug:
    msg: "SAP note 2292690 Step 1: Configure tuned to use profile sap-hana"

- name: Import ../../RedHat/generic/assert-tuned.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-tuned.yml
