# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "kernel.numa_balancing = 0"
- name: Assert 2292690-2
  ansible.builtin.debug:
    msg: "SAP note 2292690 Step 2: Turn off auto-numa balancing"

- name: Import ../../RedHat/generic/assert-auto-numa-balancing.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-auto-numa-balancing.yml
