# SPDX-License-Identifier: Apache-2.0
---

- name: Assert 2292690-7
  ansible.builtin.debug:
    msg: "SAP note 2292690 Step 7: Disable Kernel samepage merging (KSM)"

- name: Import ../../RedHat/generic/assert-ksm.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-ksm.yml
