# SPDX-License-Identifier: Apache-2.0
---
# Identify if SAPHanaSR-angi package is available for installation.
# SAPHanaSR-angi replaces SAPHanaSR and SAPHanaSR-ScaleOut.

# This is destructive step if executed on running cluster
# without proper migration from SAPHanaSR to SAPHanaSR-angi!


- name: "SAP HA Prepare Pacemaker - Block for preparation of SAPHanaSR-angi HANA cluster"
  when: (sap_ha_pacemaker_cluster_saphanasr_angi_detection | bool)
  block:
    # Requirement for package_facts Ansible Module
    # SLES: Ensure OS Package for Python Lib of rpm bindings is enabled for System Python
    - name: "SAP HA Prepare Pacemaker - Ensure python3-rpm package is present"
      ansible.builtin.package:
        name: python3-rpm
        state: present

    - name: "SAP HA Prepare Pacemaker - Gather installed packages facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "SAP HA Prepare Pacemaker - Search for SAPHanaSR-angi"
      ansible.builtin.command:
        cmd: zypper se SAPHanaSR-angi
      changed_when: false
      register: __sap_ha_pacemaker_cluster_zypper_angi_check
      failed_when: false


    # Uninstall SAPHanaSR package on SLES 15
    # package can be replaced with "rpm -e --nodeps {{ item }}"
    - name: "SAP HA Prepare Pacemaker - Remove SAPHanaSR and SAPHanaSR-doc"
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - SAPHanaSR
        - SAPHanaSR-doc
      when:
        - __sap_ha_pacemaker_cluster_zypper_angi_check is defined
        - __sap_ha_pacemaker_cluster_zypper_angi_check.rc == 0
        - "'SAPHanaSR' in ansible_facts.packages"
        # SAPHanaSR (Classic) is not available on SLES 16
        - ansible_distribution_major_version | int < 16

    - name: "SAP HA Prepare Pacemaker - Set fact angi_available"
      ansible.builtin.set_fact:
        __sap_ha_pacemaker_cluster_saphanasr_angi_available: true
      when:
        - __sap_ha_pacemaker_cluster_zypper_angi_check is defined
        - __sap_ha_pacemaker_cluster_zypper_angi_check.rc == 0


- name: "SAP HA Prepare Pacemaker - Block for preparation of Classic HANA cluster"
  when:
    - not (sap_ha_pacemaker_cluster_saphanasr_angi_detection | bool)
    # SAPHanaSR (Classic) is not available on SLES 16
    - ansible_distribution_major_version | int < 16
  block:
    # Requirement for package_facts Ansible Module
    # SLES: Ensure OS Package for Python Lib of rpm bindings is enabled for System Python
    - name: "SAP HA Prepare Pacemaker - Ensure python3-rpm package is present"
      ansible.builtin.package:
        name: python3-rpm
        state: present

    - name: "SAP HA Prepare Pacemaker - Gather installed packages facts"
      ansible.builtin.package_facts:
        manager: auto

    # package can be replaced with "rpm -e --nodeps {{ item }}"
    - name: "SAP HA Prepare Pacemaker - Remove SAPHanaSR-angi"
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - SAPHanaSR-angi
      when:
        - "'SAPHanaSR-angi' in ansible_facts.packages"

    - name: "SAP HA Prepare Pacemaker - Set fact angi_available"
      ansible.builtin.set_fact:
        __sap_ha_pacemaker_cluster_saphanasr_angi_available: false


# Ensure that angi flag is always set for SLES 16
- name: "SAP HA Prepare Pacemaker - Ensure angi_available is set for SLES 16"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_saphanasr_angi_available: true
  when:
    - ansible_distribution_major_version | int > 15
