# SPDX-License-Identifier: Apache-2.0
---

# Reason for noqa: The command might change things but we do not yet attempt to find out
- name: SAP SWPM Post Install - ensure password expiry disabled {{ sap_swpm_sid | lower + 'adm' }}
  ansible.builtin.shell: |
    chage -m 0 -M 99999 -I -1 -E -1 {{ sap_swpm_sid | lower }}adm
    chage -m 0 -M 99999 -I -1 -E -1 sapadm
  args:
    executable: /bin/bash
  become: true
  register: __sap_swpm_post_install_register_sidadm_noexpire
  changed_when: __sap_swpm_post_install_register_sidadm_noexpire is succeeded

# Firewall

- name: SAP SWPM Post Install - Firewall Setup
  ansible.builtin.include_tasks: post_install/firewall.yml
  when:
    - sap_swpm_setup_firewall

########################################################################################################################

- name: SAP SWPM Deployment - Finished
  ansible.builtin.debug:
    msg:
      - '   SAP SWPM deployment successfully completed '
      - ' '
      - '   SAP Product        -       {{ sap_swpm_product_catalog_id }}  '
      - '   SID                -       {{ sap_swpm_sid | d("") }} '
      - '   Primary Instance   -       {{ sap_swpm_pas_instance_nr | d("") }} '
      - '   Host               -       {{ ansible_hostname }} '
      - '   FQDN               -       {{ ansible_fqdn }}  '
      - '   IP                 -       {{ ansible_default_ipv4.address | d(ansible_all_ipv4_addresses[0]) }}  '
#      - '   Master Password    -       {{ sap_swpm_master_password }} '
#      - '   DDIC 000 Password  -       {{ sap_swpm_ddic_000_password }} '

# SAP HANA Client will not be installed for any installation with SAP AnyDB
# and will only be installed alongside SAP NWAS PAS or AAS (not NWAS ASCS)
- name: SAP SWPM Post Install - Check for SAP HANA Client hdbuserstore
  ansible.builtin.stat:
    path: /usr/sap/{{ sap_swpm_sid }}/hdbclient/hdbuserstore
  register: __sap_swpm_post_install_register_hdbuserstore_exists

- name: SAP SWPM Post Install - Enforce Connection Info in SAP HANA Client hdbuserstore
  ansible.builtin.shell: |
    /usr/sap/{{ sap_swpm_sid }}/hdbclient/hdbuserstore \
    SET DEFAULT \
    {{ sap_swpm_db_host }}:3{{ sap_swpm_db_instance_nr }}13@{{ sap_swpm_db_sid }} \
    {{ sap_swpm_db_schema_abap }} '{{ sap_swpm_db_schema_abap_password }}'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_swpm_sid | lower }}adm"
  when:
    - sap_swpm_install_saphostagent is defined and sap_swpm_install_saphostagent
    - __sap_swpm_post_install_register_hdbuserstore_exists.stat.exists
  register: __sap_swpm_post_install_register_hdbuserstore_connection
  changed_when: __sap_swpm_post_install_register_hdbuserstore_connection is succeeded

# Now that SWPM finished we may need to deal with SUM before continuing when sap_swpm_sum_start: 'true'
# and if we are doing OneHost or CI/PAS installation
# If observer mode is enabled, SWPM will wait for SUM to finish before continuing so we can't do anything here
- name: SAP SWPM Post Install - Control SUM if required
  ansible.builtin.include_tasks: post_install/sum_push_to_finish.yml
  when:
    - sap_swpm_sum_start
    - not sap_swpm_swpm_observer_mode
    - "'NW_ABAP_CI:' in sap_swpm_product_catalog_id or 'NW_ABAP_OneHost:' in sap_swpm_product_catalog_id"
