# SPDX-License-Identifier: Apache-2.0
---
# SAP HANA Scale-Out specific parameter values
#
# TODO: make sure to first respect 'ha_cluster' native variables

# Extra package list is combination of:
#  minimal base packages required for all scenarios
#  scenario specific packages
__sap_ha_pacemaker_cluster_sap_extra_packages: "{{
  __sap_ha_pacemaker_cluster_sap_extra_packages_dict.minimal | d([])
  + (__sap_ha_pacemaker_cluster_sap_extra_packages_dict.hana_angi
    if __sap_ha_pacemaker_cluster_saphanasr_angi_available
    else __sap_ha_pacemaker_cluster_sap_extra_packages_dict.hana_scaleout) }}"

sap_ha_pacemaker_cluster_hadr_provider_name: SAPHanaSR
