---
# SAP System IDs that are reserved and must not be used
# Reference: SAP Note 1979280
__sap_sid_prohibited: ['ADD', 'ADM', 'ALL', 'AMD', 'AND', 'ANY', 'ARE', 'ASC',
                       'AUX', 'AVG', 'BIN', 'BIT', 'CDC', 'COM', 'CON', 'DAA',
                       'DBA', 'DBM', 'DBO', 'DTD', 'ECO', 'END', 'EPS', 'EXE',
                       'FOR', 'GET', 'GID', 'IBM', 'INT', 'KEY', 'LIB', 'LOG',
                       'LPT', 'MAP', 'MAX', 'MEM', 'MIG', 'MIN', 'MON', 'NET',
                       'NIX', 'NOT', 'NUL', 'OFF', 'OLD', 'OMS', 'OUT', 'PAD',
                       'PRN', 'RAW', 'REF', 'ROW', 'SAP', 'SET', 'SGA', 'SHG',
                       'SID', 'SQL', 'SUM', 'SYS', 'TMP', 'TOP', 'TRC', 'UID',
                       'USE', 'USR', 'VAR']

# ansible_facts required by the role
__sap_ha_pacemaker_cluster_required_facts:
  - architecture # subset: min, hardware
  - board_asset_tag # subset: hardware
  - default_ipv4 # subset: interfaces
  - distribution # subset: min, hardware
  - distribution_major_version # subset: min, hardware
  - distribution_version # subset: min, hardware
  - hostname #ubset: min, hardware
  - os_family # subset: min, hardware
#  - selinux # subset: min, hardware
#  - service_mgr # subset: min, hardware
  - system_vendor # subset: hardware
#  - virtualization_role # subset: virtual
#  - virtualization_type # subset: virtual

# By default assume non-multi-NIC configuration.
# This is automatically adjusted during preparation tasks.
__sap_ha_pacemaker_cluster_nic_multi_bool: false

# By default use the construction of IPaddr2 VIP resources.
# Platforms define different methods as applicable.
sap_ha_pacemaker_cluster_vip_method: ipaddr

# (cloud) platform helper variable - leave empty for default = not cloud
__sap_ha_pacemaker_cluster_platform: ''


# ATTENTION:
# Any variables for 'ha_cluster' which this SAP role supports/inherits should also
# be added to
# - variable validations
# - conditionals (if applicable)
# - config report template
#
# TODO: verify that the task flow logic works without these explicit
# pre-definitions. Otherwise there is a need to hard-code parameters
# which have defaults in the 'ha_cluster' LSR.
# Remove this section when validated.
#
# Never set defaults for these:
#__sap_ha_pacemaker_cluster_cluster_name:
#__sap_ha_pacemaker_cluster_hacluster_user_password:


# Pre-define internal optional parameters to avoid defaults in the code:
__sap_ha_pacemaker_cluster_sap_extra_packages: []
__sap_ha_pacemaker_cluster_platform_extra_packages: []

__sap_ha_pacemaker_cluster_cluster_properties: []
__sap_ha_pacemaker_cluster_constraints_colocation: []
__sap_ha_pacemaker_cluster_constraints_location: []
__sap_ha_pacemaker_cluster_constraints_order: []
__sap_ha_pacemaker_cluster_extra_packages: []
__sap_ha_pacemaker_cluster_fence_agent_packages: []
__sap_ha_pacemaker_cluster_repos: []
__sap_ha_pacemaker_cluster_resource_primitives: []
__sap_ha_pacemaker_cluster_resource_groups: []
__sap_ha_pacemaker_cluster_resource_clones: []

# Predefine host_map for variable construction
__sap_ha_pacemaker_cluster_pcmk_host_map: ''
