---
#sap_ha_pacemaker_cluster_vip_resource_name: "vip_{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}"

# The following directories are appended to the 'nfs_path' of the '/usr/sap' storage
# definition.
# Therefore, the /usr/sap prefix must be left out of the listed path items.
__sap_ha_pacemaker_cluster_nwas_abap_ascs_ers_filesystems:
  - "{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}/ASCS{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_instance_nr }}"
  - "{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}/ERS{{ sap_ha_pacemaker_cluster_nwas_abap_ers_instance_nr }}"

# List of ASCS/ERS profile names.
# Used in tasks/configure_nwas_postinstallation.yml for sap_cluster_connector setup.
__sap_ha_pacemaker_cluster_nwas_abap_ascs_ers_profile_paths:
  - "{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_start_profile_string }}"
  - "{{ sap_ha_pacemaker_cluster_nwas_abap_ers_sapinstance_start_profile_string }}"
