---
# SAP NetWeaver ABAP specific parameter values
#
# TODO: make sure to first respect 'ha_cluster' native variables

__sap_ha_pacemaker_cluster_sap_extra_packages:
  - resource-agents-sap
  - "{% if sap_ha_pacemaker_cluster_enable_cluster_connector %}{{ __sap_ha_pacemaker_cluster_halib_package }}{% endif %}"
