---
# Variables specific on AWS platform, EC2 Virtual Servers
#
# TODO: make sure to first respect 'ha_cluster' native variables

sap_ha_pacemaker_cluster_fence_agent_packages:
  - fence-agents-aws

sap_ha_pacemaker_cluster_platform_extra_packages:
  - awscli

__sap_ha_pacemaker_cluster_repos:
  - id: "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-e4s-rhui-rpms"
    name: High Availability

# Predefine
__sap_ha_pacemaker_cluster_aws_instances: []

sap_ha_pacemaker_cluster_stonith_default:
  agent: "stonith:fence_aws"
  options:
    access_key: "{{ sap_ha_pacemaker_cluster_aws_access_key_id }}"
    secret_key: "{{ sap_ha_pacemaker_cluster_aws_secret_access_key }}"
    region: "{{ sap_ha_pacemaker_cluster_aws_region }}"

# Platform specific VIP handling
sap_ha_pacemaker_cluster_vip_method: aws_vpc_move_ip
sap_ha_pacemaker_cluster_vip_resource_group_name: vipgroup

__sap_ha_pacemaker_cluster_available_vip_agents:
  # Testing only! Not officially supported for SAP on AWS.
  ipaddr:
    agent: "ocf:heartbeat:IPaddr2"

  # Testing only! Not officially supported for SAP on AWS. Updates VM Instance network interface (ENI) with Secondary Private IP.
  awsvip:
    agent: "ocf:heartbeat:awsvip"
    with: ipaddr

  # Supported agent to manage Virtual/Overlay IPs for SAP on AWS by updating VPC Routing Table.
  aws_vpc_move_ip:
    agent: "ocf:heartbeat:aws-vpc-move-ip"
