---
# Variables specific on IBM Cloud platform, IBM Power Virtual Servers (ppc64le)
#
# TODO: make sure to first respect 'ha_cluster' native variables

sap_ha_pacemaker_cluster_fence_agent_packages:
  - fence-agents-ibm-powervs

#__sap_ha_pacemaker_cluster_platform_extra_packages:
#  -

__sap_ha_pacemaker_cluster_repos:
  - id: "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-e4s-rpms"
    name: High Availability E4S (4-Year) for Power, little endian
#  - id: "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-eus-rpms"
#    name: High Availability EUS (2-Year) for Power, little endian
#  - id: "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-rpms"
#    name: High Availability for Power, little endian

# Predefine
__sap_ha_pacemaker_cluster_ibmcloud_powervs_hosts: []


sap_ha_pacemaker_cluster_stonith_default:
  id: "res_fence_ibm_powervs"
  agent: "stonith:fence_ibm_powervs"
  options:
    token: "{{ sap_ha_pacemaker_cluster_ibmcloud_api_key }}"
    region: "{{ sap_ha_pacemaker_cluster_ibmcloud_region }}"
    crn: "{{ sap_ha_pacemaker_cluster_ibmcloud_powervs_workspace_crn }}"
    instance: "{{ sap_ha_pacemaker_cluster_ibmcloud_powervs_workspace_guid }}"  # Identified during execution initial tasks, populated when variables are imported
    plug: "{{ sap_ha_pacemaker_cluster_ibmcloud_powervs_instance_id }}"  # Identified during execution initial tasks, populated when variables are imported
    api-type: "{{ sap_ha_pacemaker_cluster_ibmcloud_powervs_api_type | default('public') }}"  # Dependent on network interface attachments, if no public network interface then 'private' value must be provided.
    proxy: "{{ sap_ha_pacemaker_cluster_ibmcloud_powervs_forward_proxy_url | default('') }}"  # Dependent on network interface attachments, if no public network interface then a valid HTTP Proxy URL value must be provided.

sap_ha_pacemaker_cluster_fence_options:
  pcmk_reboot_retries: 4
  pcmk_reboot_timeout: 600
  pcmk_monitor_timeout: 600
  pcmk_status_timeout: 60
  power_timeout: 240


# Platform specific VIP handling
sap_ha_pacemaker_cluster_vip_method: ipaddr
sap_ha_pacemaker_cluster_vip_resource_group_name: vipgroup

__sap_ha_pacemaker_cluster_available_vip_agents:

  # IPaddr2 requires a Virtual IP within a common Network (i.e. 1 VLAN / 1 VPC / 1 VNet), one or more Subnets may be used
  # With this design restriction, IPaddr2 is only to be used for High Availability within a single location (i.e. 1 Availability Zone / Datacenter / Location within 1 Region)
  ipaddr:
    agent: "ocf:heartbeat:IPaddr2"
