# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 16
# - SUSE Linux Enterprise Server 16

# Dictionary with additional cluster packages for specific scenarios
__sap_ha_pacemaker_cluster_sap_extra_packages_dict:
  minimal: []  # All minimal packages are part of patterns
  hana_scaleout:
    - patterns-sap-HADB
  hana_scaleup:
    - patterns-sap-HADB
  hana_angi: []  # SAPHanaSR-angi package is part of patterns-sap-HADB
  nwas:
    - patterns-sap-HAAPP

# Package list was simplified because of new patterns below:

# patterns-sap-HADB contains:
# - patterns-sles_sap_DB
# - patterns-ha-ha_sles
# - SAPHanaSR-angi
# - ClusterTools2
# - supportutils-plugin-ha-sap
# - socat

# patterns-sap-HAAPP contains:
# - patterns-sles_sap_APP
# - patterns-ha-ha_sles
# - sapstartsrv-resource-agents
# - sap-suse-cluster-connector
# - ClusterTools2
# - supportutils-plugin-ha-sap
# - socat
