# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 15
# - SUSE Linux Enterprise Server 15

__sap_ha_pacemaker_cluster_sap_extra_packages_dict:
  minimal:
    # Pattern contains all required cluster packages
    - patterns-ha-ha_sles
    - ClusterTools2
  hana_scaleout:
    - SAPHanaSR-ScaleOut
  hana_scaleup:
    - SAPHanaSR
  hana_angi:
    - SAPHanaSR-angi
  nwas:
    - sap-suse-cluster-connector
    - sapstartsrv-resource-agents
