---
__sap_ha_pacemaker_cluster_halib_package: sap-suse-cluster-connector

# List of configuration lines that must be added to the instance profiles.
# Used in tasks/configure_nwas_ascs_ers_postinstallation.yml for SAP HA Interface setup.
__sap_ha_pacemaker_cluster_connector_config_lines:
  - "service/halib = $(DIR_EXECUTABLE)/saphascriptco.so"
  - "service/halib_cluster_connector = /usr/bin/sap_suse_cluster_connector"

# Cluster commands to manage resources - crmsh commands in SUSE OS family.
__sap_ha_pacemaker_cluster_command:
  resource_stop: "crm resource stop"
  resource_start: "crm resource start"
  resource_defaults_show: "crm configure show type:rsc_defaults"
  resource_defaults_update: "crm configure rsc_defaults"
