# SPDX-License-Identifier: Apache-2.0
---
# Default repositories are tied to subscription for SLES4SAP, no need to specify them.
# __sap_ha_pacemaker_cluster_repos:
# __sap_ha_pacemaker_cluster_repos_dict:

__sap_ha_pacemaker_cluster_halib_package: sap-suse-cluster-connector

# List of configuration lines that must be added to the instance profiles for SAP HA Interface setup.
__sap_ha_pacemaker_cluster_connector_config_lines:
  - "service/halib = $(DIR_EXECUTABLE)/saphascriptco.so"
  - "service/halib_cluster_connector = /usr/bin/sap_suse_cluster_connector"

# Cluster commands to manage resources - crmsh commands in SUSE OS family.
__sap_ha_pacemaker_cluster_command:
  resource_stop: "crm resource stop"
  resource_start: "crm resource start"
  resource_restart: "crm resource restart"
  resource_cleanup: "crm resource cleanup"

# Default corosync options - OS specific
__sap_ha_pacemaker_cluster_corosync_totem_default:
  options:
    token: 5000
    token_retransmits_before_loss_const: 10
    join: 60
    consensus: 6000
    max_messages: 20

# Make sure that there is always the minimal default fed into the included role.
# This is combined with the custom list 'sap_ha_pacemaker_cluster_fence_agent_packages'.
__sap_ha_pacemaker_cluster_fence_agent_packages_minimal:
  - fence-agents

# Dictionary with fence packages for each platform
# fence-agents are defined in __sap_ha_pacemaker_cluster_fence_agent_packages_minimal already.
__sap_ha_pacemaker_cluster_fence_agent_packages_dict:
  # Separate agent because of https://www.suse.com/support/kb/doc/?id=000021504
  # This package is present in SLES4SAP 15 SP4 and higher
  cloud_msazure_vm:
    - fence-agents-azure-arm

# Dictionary with extra platform specific packages
__sap_ha_pacemaker_cluster_platform_extra_packages_dict:
  cloud_aws_ec2_vs:
    - awscli
  cloud_gcp_ce_vm:
    - socat
  cloud_msazure_vm:
    - socat

# Dictionary with additional cluster packages for specific scenarios
# All packages are defined in SLES_15 and SLES_16 var files.
__sap_ha_pacemaker_cluster_sap_extra_packages_dict:
  {}

# Dictionary with preferred platform specific VIP method that differs from default
__sap_ha_pacemaker_cluster_vip_method_dict:
  cloud_gcp_ce_vm: gcp_anything_socat

# Resource agents - fully qualified names
__sap_ha_pacemaker_cluster_resource_agents:
  saphanatopology: "ocf:suse:SAPHanaTopology"
  saphana: "ocf:suse:SAPHana"
  saphanacontroller: "ocf:suse:SAPHanaController"
  saphanafilesystem: "ocf:suse:SAPHanaFilesystem"
  sapstartsrv: "ocf:suse:SAPStartSrv"

# Boolean variable reflecting availability of SAPHanaSR-angi availability.
__sap_ha_pacemaker_cluster_saphanasr_angi_available: false

# Default SAP HANA hook parameters combined based on user decision
__sap_ha_pacemaker_cluster_hook_hana_scaleup_perf:
  saphanasr:
    - provider: SAPHanaSR
      path: /usr/share/SAPHanaSR/
      options:
        - name: execution_order
          value: 1
  tkover:
    - provider: susTkOver
      path: /usr/share/SAPHanaSR/
      options:
        - name: execution_order
          value: 2
  chksrv:
    - provider: susChkSrv
      path: /usr/share/SAPHanaSR/
      options:
        - name: execution_order
          value: 3
        - name: action_on_lost
          value: stop

__sap_ha_pacemaker_cluster_hook_hana_scaleup_perf_angi:
  saphanasr:
    - provider: susHanaSR
      path: /usr/share/SAPHanaSR-angi/
      options:
        - name: execution_order
          value: 1
  tkover:
    - provider: susTkOver
      path: /usr/share/SAPHanaSR-angi/
      options:
        - name: execution_order
          value: 2
        - name: sustkover_timeout
          value: 30
  chksrv:
    - provider: susChkSrv
      path: /usr/share/SAPHanaSR-angi/
      options:
        - name: execution_order
          value: 3
        - name: action_on_lost
          value: stop
        - name: stop_timeout
          value: 25

# Placeholder dictionaries
__sap_ha_pacemaker_cluster_hook_hana_scaleout: []
__sap_ha_pacemaker_cluster_hook_hana_scaleout_angi: []

# Enable default OS recommended hooks
sap_ha_pacemaker_cluster_hana_hook_tkover: true
sap_ha_pacemaker_cluster_hana_hook_chksrv: true

# Central Services Cluster Simple Mount: Enabled as default
sap_ha_pacemaker_cluster_nwas_cs_ers_simple_mount: true
