# SPDX-License-Identifier: Apache-2.0
---

- name: Assert that saptune solution is correct
  when: __sap_netweaver_preconfigure_use_saptune
  block:
    - name: Discover active solution
      ansible.builtin.command:
        cmd: saptune solution enabled
      register: __sap_netweaver_preconfigure_register_saptune_status
      changed_when: false
      ignore_errors: true

    - name: Set fact for active solution
      ansible.builtin.set_fact:
        # Capture the first block on none whitespace
        __sap_netweaver_preconfigure_register_solution_configured:
          "{{ (__sap_netweaver_preconfigure_register_saptune_status.stdout | regex_search('(\\S+)', '\\1'))[0] | default('NONE') }}"

    - name: Assert that active solution is the expected solution
      ansible.builtin.assert:
        that: __sap_netweaver_preconfigure_register_solution_configured == sap_netweaver_preconfigure_saptune_solution
        fail_msg: "FAIL: the configured saptune solution is '{{ __sap_netweaver_preconfigure_register_solution_configured
          }}'' and does not match the expected solution '{{ sap_netweaver_preconfigure_saptune_solution }}'"
        success_msg: "PASS: the configured saptune solution matches the expected solution '{{ sap_netweaver_preconfigure_saptune_solution }}'"
      ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"

    - name: Verify saptune solution
      ansible.builtin.command:
        cmd: "saptune solution verify {{ sap_netweaver_preconfigure_saptune_solution }}"
      register: __sap_netweaver_preconfigure_register_saptune_verify
      changed_when: false
      failed_when: false
      when:
        - __sap_netweaver_preconfigure_register_solution_configured == sap_netweaver_preconfigure_saptune_solution


    - name: Assert that saptune solution is verified by saptune
      ansible.builtin.assert:
        that: "{{ __sap_netweaver_preconfigure_register_saptune_verify.rc == 0 }}"
        success_msg: "PASS: saptune solution {{ sap_netweaver_preconfigure_saptune_solution }} is verified by saptune."
        fail_msg: |
          "FAIL: active saptune solution is not verified by saptune! See details below:"
          {{ __sap_netweaver_preconfigure_register_saptune_verify.stdout_lines }}
          {{ __sap_netweaver_preconfigure_register_saptune_verify.stderr_lines }}
      when:
        - __sap_netweaver_preconfigure_register_solution_configured == sap_netweaver_preconfigure_saptune_solution


- name: Assert that adequate swap is configured
  ansible.builtin.assert:
    that: ansible_swaptotal_mb > (sap_netweaver_preconfigure_min_swap_space_mb | int)
    fail_msg: "FAIL: A minimum of {{ sap_netweaver_preconfigure_min_swap_space_mb
     }}MiB is required but only {{ ansible_swaptotal_mb }}MiB was discovered"
    success_msg: "PASS: the system has at least {{ sap_netweaver_preconfigure_min_swap_space_mb
     }}MiB of swap configured"
  when: sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured
