# SPDX-License-Identifier: Apache-2.0
---

- name: Get current enabled saptune solution
  ansible.builtin.command:
    cmd: "saptune solution enabled"
  register: __sap_netweaver_preconfigure_register_solution_enabled
  changed_when: false
  failed_when: false
  when: __sap_netweaver_preconfigure_use_saptune

# Enabled solution contains newline, which has to be removed
- name: Cleanup saptune solution enabled output
  ansible.builtin.set_fact:
    __sap_netweaver_preconfigure_register_solution_enabled_trim:
      "{{ __sap_netweaver_preconfigure_register_solution_enabled.stdout | trim | replace('\n', '') }}"
  when: __sap_netweaver_preconfigure_use_saptune

# Verify SAP Solution before block and revert if found invalid
- name: Verify saptune solution before changes
  ansible.builtin.command:
    cmd: "saptune solution verify {{ sap_netweaver_preconfigure_saptune_solution }}"
  register: __sap_netweaver_preconfigure_register_solution_verify_before
  changed_when: false
  failed_when: false
  when:
    - __sap_netweaver_preconfigure_use_saptune
    - __sap_netweaver_preconfigure_register_solution_enabled_trim == sap_netweaver_preconfigure_saptune_solution

- name: Apply saptune solution
  when:
    - __sap_netweaver_preconfigure_use_saptune
    - sap_netweaver_preconfigure_saptune_solution_force
      or __sap_netweaver_preconfigure_register_solution_enabled_trim != sap_netweaver_preconfigure_saptune_solution
      or __sap_netweaver_preconfigure_register_solution_verify_before.rc != 0
  block:
    - name: Show current enabled saptune solution
      ansible.builtin.debug:
        msg: "{{ __sap_netweaver_preconfigure_register_solution_enabled_trim }}"
      when: __sap_netweaver_preconfigure_register_solution_enabled_trim != ''

    - name: Revert saptune configuration
      ansible.builtin.command:
        cmd: "saptune revert all"
      changed_when: true

    - name: Ensure saptune solution is applied
      ansible.builtin.command:
        cmd: "saptune solution apply {{ sap_netweaver_preconfigure_saptune_solution }}"
      changed_when: true

    - name: Ensure solution was successful after changes
      ansible.builtin.command:
        cmd: "saptune solution verify --show-non-compliant {{ sap_netweaver_preconfigure_saptune_solution }}"
      changed_when: false
      failed_when: false
      register: __sap_netweaver_preconfigure_register_solution_verify_after

    - name: Display error if saptune verify failed
      ansible.builtin.fail:
        msg: |
          {{ __sap_netweaver_preconfigure_register_solution_verify_after.stdout_lines }}
          {{ __sap_netweaver_preconfigure_register_solution_verify_after.stderr_lines }}
      when: __sap_netweaver_preconfigure_register_solution_verify_after.rc != 0

    - name: Show applied saptune solution
      ansible.builtin.debug:
        msg: "{{ sap_netweaver_preconfigure_saptune_solution }}"


- name: Warn if not enough swap space is configured
  ansible.builtin.fail:
    msg: "The system has only {{ ansible_swaptotal_mb }} MB of swap space configured,
      which is less than the minimum required amount of {{ sap_netweaver_preconfigure_min_swap_space_mb
       }} MB for SAP NetWeaver!"
  ignore_errors: true
  when:
    - ansible_swaptotal_mb < sap_netweaver_preconfigure_min_swap_space_mb|int
    - not sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured|d(true)

- name: Fail if not enough swap space is configured
  ansible.builtin.fail:
    msg: "The system has only {{ ansible_swaptotal_mb }} MB of swap space configured,
      which is less than the minimum required amount of {{ sap_netweaver_preconfigure_min_swap_space_mb
       }} MB for SAP NetWeaver!"
  when:
    - ansible_swaptotal_mb < sap_netweaver_preconfigure_min_swap_space_mb|int
    - sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured|d(true)
