# SPDX-License-Identifier: Apache-2.0
---

- name: Gather service facts
  ansible.builtin.service_facts:

# Service packagekit is part of PackageKit-backend-zypp (SLE-Module-Desktop-Applications)
# This service creates zypper locks and causes package install failures.
# Service cannot be disabled and we have to mask its execution.
- name: Mask packagekit.service when present
  ansible.builtin.systemd_service:
    name: packagekit.service
    masked: true
  when: "'packagekit.service' in ansible_facts.services"
  notify: __sap_netweaver_preconfigure_packagekit_handler


- name: Wait for stop of packagekit.service
  ansible.builtin.shell: |
    set -o pipefail && bash -c '
    while (ps aux | grep "[z]ypper" | grep -v grep) || (ps aux | grep "/usr/lib/packagekitd" | grep -v grep) ||
     ([ -f /var/run/zypp.pid ] && [ -s /var/run/zypp.pid ]); do
      sleep 10;
    done'
  register: __packagekit_service_check
  changed_when: false
  until: __packagekit_service_check.rc == 0
  retries: 60
  when: "'packagekit.service' in ansible_facts.services"


# Pattern installation will run only if pattern is not installed
# This ensures that command module shows correct changed status
- name: Query installed zypper patterns
  ansible.builtin.command:
    cmd: zypper patterns --installed-only
  register: __sap_netweaver_preconfigure_register_patterns
  changed_when: false
  ignore_errors: true

- name: Ensure that the required zypper patterns are installed
  ansible.builtin.command:
    cmd: zypper install -y -t pattern {{ item }}
  loop: "{{ sap_netweaver_preconfigure_patterns }}"
  when: item not in __sap_netweaver_preconfigure_register_patterns.stdout
  changed_when: item not in __sap_netweaver_preconfigure_register_patterns.stdout

- name: Ensure that the required packages are installed
  ansible.builtin.package:
    state: present
    name: "{{ sap_netweaver_preconfigure_packages }}"


# Reason for noqa: Zypper supports "state: latest"
- name: Ensure that the system is updated to the latest patchlevel # noqa package-latest
  ansible.builtin.package:
    state: latest
    name: "*"
  when: sap_netweaver_preconfigure_update | bool


# 1275776 - Linux: Preparing SLES for SAP environments
- name: Install saptune if available
  ansible.builtin.include_tasks:
    file: generic/saptune_install.yml

- name: Takeover and enable saptune if available
  ansible.builtin.include_tasks:
    file: generic/saptune_takeover.yml


# Reason for noqa: The command to be executed might contain pipes
- name: Determine if the system needs to be restarted # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: "zypper ps"
  register: __sap_netweaver_preconfigure_register_needs_restarting
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: Display the output of the reboot requirement check
  ansible.builtin.debug:
    var: __sap_netweaver_preconfigure_register_needs_restarting

- name: Call Reboot handler if necessary
  ansible.builtin.command:
    cmd: /bin/true
  notify: __sap_netweaver_preconfigure_reboot_handler
  changed_when: true
  when:
    - __sap_netweaver_preconfigure_register_needs_restarting is failed
      or __sap_netweaver_preconfigure_register_needs_restarting.rc == 102
