# SPDX-License-Identifier: Apache-2.0
---

# Check rpm --whatprovides only if package cannot be found directly.
- name: Query RPM packages
  ansible.builtin.shell:
    cmd: |
      if rpm -q {{ item }} &> /dev/null;
      then rpm -q {{ item }}
      else rpm -q --whatprovides {{ item }};
      fi
  register: __sap_general_preconfigure_register_packages
  changed_when: false
  ignore_errors: true
  loop: "{{ __sap_general_preconfigure_packages_2578899 }}"

- name: Assert that all required packages are installed
  ansible.builtin.assert:
    that: __sap_general_preconfigure_register_packages.results | selectattr('item', 'equalto', item) | map(attribute='rc') | first == 0
    fail_msg: "FAIL: Package '{{ item }}' is not installed!"
    success_msg: "PASS: Package '{{ item }}' is installed."
  loop: "{{ __sap_general_preconfigure_packages_2578899 }}"
  ignore_errors: "{{ sap_general_preconfigure_assert_ignore_errors | d(false) }}"
