# SPDX-License-Identifier: Apache-2.0
---

- name: Ensure that the required packages are installed
  ansible.builtin.package:
    name: "{{ __sap_general_preconfigure_packages_2578899 }}"
    state: present
