---
# Set which Ansible Collection to use for the Linux System Roles.
# For community/upstream, use 'fedora.linux_system_roles'
# For the RHEL System Roles for SAP, or for Red Hat Automation Hub, use 'redhat.rhel_system_roles'
sap_ha_pacemaker_cluster_system_roles_collection: 'fedora.linux_system_roles'

# Variables for the cluster setup must be constructed by dedicated tasks!
# The included 'ha_cluster' role will not work with the role variables set
# in this role.

# Do NOT USE ANSIBLE FACTS for defaults to be compatible with
# playbooks that disable generic fact gathering!

sap_ha_pacemaker_cluster_cluster_name: "{{ ha_cluster_cluster_name | default('my-cluster') }}"

sap_ha_pacemaker_cluster_create_config_varfile: false
sap_ha_pacemaker_cluster_create_config_dest: "{{ sap_ha_pacemaker_cluster_cluster_name }}_resource_config.yml"

# Inherit SAP common (global synonyms) parameters
sap_ha_pacemaker_cluster_cluster_nodes: "{{ sap_ha_cluster_nodes | default(sap_hana_cluster_nodes) }}"
sap_ha_pacemaker_cluster_hana_sid: "{{ sap_hana_sid | default('') }}"
sap_ha_pacemaker_cluster_hana_instance_number: "{{ sap_hana_instance_number | default('00') }}"

sap_ha_pacemaker_cluster_storage_definition: "{{ sap_storage_definition | default([]) }}"
sap_ha_pacemaker_cluster_storage_nfs_filesytem_type: nfs4
sap_ha_pacemaker_cluster_storage_nfs_mount_options: hard,acl
sap_ha_pacemaker_cluster_storage_nfs_server: "{{ sap_storage_nfs_server | default('') }}"

sap_ha_pacemaker_cluster_netweaver_sid: "{{ sap_swpm_sid | default('') }}"
sap_ha_pacemaker_cluster_netweaver_abap_ascs_instance_number: "{{ sap_swpm_ascs_instance_nr }}"
sap_ha_pacemaker_cluster_netweaver_abap_ers_instance_number: "{{ sap_swpm_ers_instance_nr }}"
sap_ha_pacemaker_cluster_netweaver_abap_pas_instance_number: "{{ sap_swpm_pas_instance_nr }}"
sap_ha_pacemaker_cluster_netweaver_abap_aas_instance_number: "{{ sap_swpm_aas_instance_nr }}"
sap_ha_pacemaker_cluster_netweaver_java_scs_instance_number: "{{ sap_swpm_java_scs_instance_nr }}"
sap_ha_pacemaker_cluster_netweaver_java_ers_instance_number: "{{ sap_swpm_java_ers_instance_nr }}"

#sap_ha_pacemaker_cluster_netweaver_common_filesystems:
#  - /sapmnt
#  - /usr/sap/trans
#  - "/usr/sap/{{ sap_ha_pacemaker_cluster_netweaver_sid }}/SYS"

# The following directories are appended to the 'nfs_path' of the '/usr/sap' storage
# definition.
# Therefore, the /usr/sap prefix must be left out of the listed path items.
sap_ha_pacemaker_cluster_netweaver_abap_ascs_ers_filesystems:
  - "{{ sap_ha_pacemaker_cluster_netweaver_sid }}/ASCS{{ sap_ha_pacemaker_cluster_netweaver_abap_ascs_instance_number }}"
  - "{{ sap_ha_pacemaker_cluster_netweaver_sid }}/ERS{{ sap_ha_pacemaker_cluster_netweaver_abap_ers_instance_number }}"

# Make sure that there is always the default fed into the included role
sap_ha_pacemaker_cluster_fence_agent_packages:
  - fence-agents-all

sap_ha_pacemaker_cluster_extra_packages: "{{ ha_cluster_extra_packages | default([]) }}"

# Adjusting resource defaults
sap_ha_pacemaker_cluster_resource_defaults:
  resource-stickiness: 1000
  migration-threshold: 5000

# The type of SAP landscape and multi-node replication
# TODO: Type definitions and feature support
# TODO: Implement all types
# hana_scaleup_costopt  (not yet)
# hana_scaleup_perf     (default)
# hana_scaleup_per_dr   (not yet)
# hana_scaleout         (not yet)
# nwas_abap_ascs_ers
# nwas_abap_pas_aas
# nwas_java_scs_ers     (maybe)
sap_ha_pacemaker_cluster_host_type: "{{ sap_host_type | default('hana_scaleup_perf') }}"
sap_ha_pacemaker_cluster_replication_type: none

# Optional parameters to customize HANA resources
# AUTOMATED_REGISTER
sap_ha_pacemaker_cluster_hana_automated_register: true
# DUPLICATE_PRIMARY_TIMEOUT
sap_ha_pacemaker_cluster_hana_duplicate_primary_timeout: 900
# PREFER_SITE_TAKEOVER
sap_ha_pacemaker_cluster_hana_prefer_site_takeover: true

### stonith resource parameter defaults
sap_ha_pacemaker_cluster_fence_options:
  pcmk_reboot_retries: 4
  pcmk_reboot_timeout: 400
  power_timeout: 240

### Resource default patterns
sap_ha_pacemaker_cluster_vip_address: "{{ sap_hana_vip | default(sap_cluster_vip) }}"
sap_ha_pacemaker_cluster_vip_resource_agent: "ocf:heartbeat:IPaddr2"
sap_ha_pacemaker_cluster_vip_resource_name: "vip_{{ sap_ha_pacemaker_cluster_hana_sid }}_{{ sap_ha_pacemaker_cluster_hana_instance_number }}"

# SAP HANA - Resource IDs (names) as convenience parameters.
sap_ha_pacemaker_cluster_hana_resource_name: "SAPHana_{{ sap_ha_pacemaker_cluster_hana_sid }}_{{ sap_ha_pacemaker_cluster_hana_instance_number }}"
sap_ha_pacemaker_cluster_hana_resource_clone_name: "{{ sap_ha_pacemaker_cluster_hana_resource_name }}-clone"
sap_ha_pacemaker_cluster_hana_topology_resource_name: "SAPHanaTopology_{{ sap_ha_pacemaker_cluster_hana_sid }}_{{ sap_ha_pacemaker_cluster_hana_instance_number }}"
sap_ha_pacemaker_cluster_hana_topology_resource_clone_name: "{{ sap_ha_pacemaker_cluster_hana_topology_resource_name }}-clone"


sap_ha_pacemaker_cluster_resource_filesystem_force_unmount: safe


# SAP NetWeaver common - Resource IDs (names) as convenience parameters.
# - /sapmnt
# - /usr/sap/trans
# - /usr/sap/<<SID>>/SYS
sap_ha_pacemaker_cluster_netweaver_sapmnt_filesystem_resource_name: "Filesystem_NWAS_SAPMNT_{{ sap_ha_pacemaker_cluster_netweaver_sid }}"
sap_ha_pacemaker_cluster_netweaver_transports_filesystem_resource_name: "Filesystem_NWAS_TRANS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}"
sap_ha_pacemaker_cluster_netweaver_sys_filesystem_resource_name: "Filesystem_NWAS_SYS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}"

# SAP NetWeaver ABAP ASCS/ERS - Resource IDs (names) as convenience parameters.
# - /usr/sap/<<SID>>/ASCS<<Instance>>
# - /usr/sap/<<SID>>/ERS<<Instance>>
sap_ha_pacemaker_cluster_netweaver_abap_ascs_filesystem_resource_name: "Filesystem_NWAS_ABAP_ASCS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_ascs_instance_number }}"
sap_ha_pacemaker_cluster_netweaver_abap_ascs_sapinstance_resource_name: "SAPInstance_NWAS_ABAP_ASCS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_ascs_instance_number }}"
sap_ha_pacemaker_cluster_netweaver_abap_ascs_sapinstance_resource_clone_name: "{{ sap_ha_pacemaker_cluster_netweaver_abap_ascs_sapinstance_resource_name }}-clone"
sap_ha_pacemaker_cluster_netweaver_abap_ers_filesystem_resource_name: "Filesystem_NWAS_ABAP_ERS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_ers_instance_number }}"
sap_ha_pacemaker_cluster_netweaver_abap_ers_sapinstance_resource_name: "SAPInstance_NWAS_ABAP_ERS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_ers_instance_number }}"
sap_ha_pacemaker_cluster_netweaver_abap_ers_sapinstance_resource_clone_name: "{{ sap_ha_pacemaker_cluster_netweaver_abap_ers_sapinstance_resource_name }}-clone"

# SAP NetWeaver ABAP PAS/AAS - Resource IDs (names) as convenience parameters.
# - /usr/sap/<<SID>>/D<<Instance>>
#sap_ha_pacemaker_cluster_netweaver_abap_pas_filesystem_resource_name: "Filesystem_NWAS_ABAP_PAS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_pas_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_abap_pas_sapinstance_resource_name: "SAPInstance_NWAS_ABAP_PAS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_pas_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_abap_aas_filesystem_resource_name: "Filesystem_NWAS_ABAP_AAS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_aas_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_abap_aas_sapinstance_resource_name: "SAPInstance_NWAS_ABAP_AAS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_abap_aas_instance_number }}"

# SAP NetWeaver JAVA SCS/ERS - Resource IDs (names) as convenience parameters.
# - /usr/sap/<<SID>>/SCS<<Instance>>
# - /usr/sap/<<SID>>/ERS<<Instance>>
#sap_ha_pacemaker_cluster_netweaver_java_scs_filesystem_resource_name: "Filesytem_NWAS_JAVA_SCS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_java_scs_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_java_scs_sapinstance_resource_name: "SAPInstance_NWAS_JAVA_SCS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_java_scs_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_java_scs_sapinstance_resource_clone_name: "{{ sap_ha_pacemaker_cluster_netweaver_abap_ascs_sapinstance_resource_name }}-clone"
#sap_ha_pacemaker_cluster_netweaver_java_ers_filesystem_resource_name: "Filesytem_NWAS_JAVA_ERS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_java_ers_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_java_ers_sapinstance_resource_name: "SAPInstance_NWAS_JAVA_ERS_{{ sap_ha_pacemaker_cluster_netweaver_sid }}_{{ sap_ha_pacemaker_cluster_netweaver_java_ers_instance_number }}"
#sap_ha_pacemaker_cluster_netweaver_java_ers_sapinstance_resource_clone_name: "{{ sap_ha_pacemaker_cluster_netweaver_abap_ers_sapinstance_resource_name }}-clone"


# TODO: network interface name used for client access
sap_ha_pacemaker_cluster_vip_client_interface: eth0
sap_ha_pacemaker_cluster_vip_update_rt: []

## A custom stonith definition that takes precedence over platform defaults.
# sap_ha_pacemaker_cluster_stonith_custom:
#   - name: ""
#     agent: "stonith:"
#     options:
#       pcmk_host_list: ""

# Simpler format translated into 'ha_cluster_cluster_properties' format of
# 'ha_cluster' LSR.
sap_ha_pacemaker_cluster_cluster_properties:
  stonith-enabled: true
  stonith-timeout: 900
  concurrent-fencing: true


## Infrastructure Platform variables, shown here for visibility only and should not be given default values
##
## AWS platform, EC2 Virtual Servers
# sap_ha_pacemaker_cluster_aws_access_key_id
# sap_ha_pacemaker_cluster_aws_secret_access_key
# sap_ha_pacemaker_cluster_aws_region
##
## Google Cloud platform, Compute Engine Virtual Machines
# sap_ha_pacemaker_cluster_gcp_project
# sap_ha_pacemaker_cluster_gcp_region_zone
##
## IBM Cloud platform, Virtual Servers (x86_64)
# sap_ha_pacemaker_cluster_ibmcloud_api_key
# sap_ha_pacemaker_cluster_ibmcloud_region
##
## IBM Cloud platform, IBM Power Virtual Servers (ppc64le)
# sap_ha_pacemaker_cluster_ibmcloud_api_key
# sap_ha_pacemaker_cluster_ibmcloud_region
# sap_ha_pacemaker_cluster_ibmcloud_powervs_workspace_crn
# sap_ha_pacemaker_cluster_ibmcloud_powervs_workspace_guid
# sap_ha_pacemaker_cluster_ibmcloud_powervs_api_type
# sap_ha_pacemaker_cluster_ibmcloud_powervs_forward_proxy_url
##
## MS Azure platform, Virtual Machines
# sap_ha_pacemaker_cluster_msazure_subscription_id
# sap_ha_pacemaker_cluster_msazure_resource_group
