# SPDX-License-Identifier: Apache-2.0
---
################################################################################
# Role generic parameters
################################################################################

# Do NOT USE ANSIBLE FACTS for defaults to be compatible with
# playbooks that disable generic fact gathering!

# Set which Ansible Collection to use for the Linux System Roles.
# For community/upstream, use 'fedora.linux_system_roles'
# For the RHEL System Roles for SAP, or for Red Hat Automation Hub, use 'redhat.rhel_system_roles'
sap_ha_pacemaker_cluster_system_roles_collection: 'fedora.linux_system_roles'

# Variables for the cluster setup must be constructed by dedicated tasks!
# The included 'ha_cluster' role will not work with the role variables set
# in this role. This SAP HA role takes care of the parameter construction
# based on the target cluster to be configured, before feeding it into 'ha_cluster'.


# Optional: write all cluster configuration (including unencrypted credentials!) into a yaml
# config file.
# Useful for parameter review or reuse with the 'ha_cluster' LSR.
sap_ha_pacemaker_cluster_create_config_varfile: false
sap_ha_pacemaker_cluster_create_config_dest: "review_resource_config.yml"

# Inherit SAP common (global synonyms) parameters when defined.

# This variable is currently only required for HANA nodes to define
# - hana_site: <DC-name>
# Other options are needed in the separate HSR setup role.
sap_ha_pacemaker_cluster_cluster_nodes: "{{ sap_hana_cluster_nodes | d([]) }}"

# Resource defaults are defined differently by cluster type in different tasks, if not custom defined.
sap_ha_pacemaker_cluster_resource_defaults: {}
sap_ha_pacemaker_cluster_operation_defaults: {}

# The type of SAP landscape and multi-node replication
# TODO: Type definitions and feature support
# TODO: Implement all types
# hana_scaleup_costopt  (not yet)
# hana_scaleup_perf     (available, default)
# hana_scaleup_per_dr   (not yet)
# hana_scaleout         (not yet)
# nwas_abap_ascs_ers    (available)
# nwas_abap_pas_aas     (not yet)
# nwas_java_scs_ers     (available)

# 'sap_ha_pacemaker_cluster_host_type' is converted from string to list type in
# 'tasks/ascertain_sap_landscape.yml'.
sap_ha_pacemaker_cluster_host_type: "{{ sap_host_type | d(['hana_scaleup_perf']) }}"

### VIP resource default patterns
sap_ha_pacemaker_cluster_vip_client_interface: ''

## A custom stonith definition that takes precedence over platform defaults.
# sap_ha_pacemaker_cluster_stonith_custom:
#   - name: ""
#     agent: "stonith:"
#     options:
#       pcmk_host_list: ""

# sap_ha_pacemaker_cluster_stonith_custom: []

# Simpler definition format here which gets transformed into the 'ha_cluster' LSR native
# 'ha_cluster_cluster_properties' parameter.
sap_ha_pacemaker_cluster_cluster_properties:
  stonith-enabled: true
  stonith-timeout: 900
  concurrent-fencing: true

### Constraints:
# score is dynamic and automatically increased for groups
sap_ha_pacemaker_cluster_constraint_colo_base_score: 2000

################################################################################
# Inherit from 'ha_cluster' Linux System Role parameters when defined
################################################################################

# Optional without a default. The 'ha_cluster' LSR defaults will apply when not defined.
# sap_ha_pacemaker_cluster_ha_cluster:
# sap_ha_pacemaker_cluster_cluster_name:

# Optional. Set a default here and not in the code.
sap_ha_pacemaker_cluster_extra_packages: []

# Optional: additional fence agent packages. This is combined with the above "minimal" list.
sap_ha_pacemaker_cluster_fence_agent_packages: []

# Mandatory.
# Either inherit from the 'ha_cluster' LSR variable when defined, but do not set a default.
# This fails the argument validation when none of the 2 vars are defined.
sap_ha_pacemaker_cluster_hacluster_user_password: "{{ ha_cluster_hacluster_password }}"


################################################################################
# HANA
################################################################################

sap_ha_pacemaker_cluster_hana_sid: ''  # Mandatory System ID in capital letters
sap_ha_pacemaker_cluster_hana_instance_nr: ''  # Mandatory instance number in string format

# Optional parameters to customize SAPHana resources
# AUTOMATED_REGISTER
sap_ha_pacemaker_cluster_hana_automated_register: true
# DUPLICATE_PRIMARY_TIMEOUT
sap_ha_pacemaker_cluster_hana_duplicate_primary_timeout: 7200
# PREFER_SITE_TAKEOVER
sap_ha_pacemaker_cluster_hana_prefer_site_takeover: true

# SAP HANA - Resource IDs (names) as convenience parameters.
sap_ha_pacemaker_cluster_hana_resource_name: ''             # Default: rsc_SAPHana_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_resource_clone_name: ''       # Default: cln_SAPHana_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_resource_clone_msl_name: ''   # Default: msl_SAPHana_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hanacontroller_resource_name: ''   # Default: rsc_SAPHanaCon_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hanacontroller_resource_clone_name: ''  # Default: <cln|mst>_SAPHanaCon_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_topology_resource_name: ''  # Default: rsc_SAPHanaTop_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_topology_resource_clone_name: ''  # Default: cln_SAPHanaTop_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_filesystem_resource_name: ''  # Default: rsc_SAPHanaFil_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_filesystem_resource_clone_name: ''  # Default: cln_SAPHanaFil_<SID>_HDB<Instance Number>

# SAP HANA - Constraint names
sap_ha_pacemaker_cluster_hana_order_topology_hana_name: ''  # Default: ord_saphana_saphanatop_<SID>_HDB<Instance Number>
sap_ha_pacemaker_cluster_hana_colocation_hana_vip_primary_name: ''  # Default: col_saphana_vip_<SID>_HDB<Instance Number>_primary
sap_ha_pacemaker_cluster_hana_colocation_hana_vip_secondary_name: ''  # Default: col_saphana_vip_<SID>_HDB<Instance Number>_readonly
sap_ha_pacemaker_cluster_hana_order_hana_vip_primary_name: ''  # Default: ord_saphana_vip_<SID>_HDB<Instance Number>_primary
sap_ha_pacemaker_cluster_hana_order_hana_vip_secondary_name: ''  # Default: ord_saphana_vip_<SID>_HDB<Instance Number>_readonly

# Multiple VIP parameters can be defined and will be combined.
# See tasks/include_construct_vip_resources.yml
#
# Mandatory: primary VIP address definition in HANA scale-up clusters
sap_ha_pacemaker_cluster_vip_hana_primary_ip_address: ''
sap_ha_pacemaker_cluster_vip_hana_primary_resource_name: ''  # Default: rsc_vip_<SID>_HDB<Instance Number>_primary
sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name: ''  # Default: rsc_vip_health_check_<SID>_HDB<Instance Number>_primary

sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address: ''
sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name: ''  # Default: rsc_vip_<SID>_HDB<Instance Number>_readonly
sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name: ''  # Default: rsc_vip_health_check_<SID>_HDB<Instance Number>_readonly

sap_ha_pacemaker_cluster_healthcheck_hana_primary_id: ''  # Default: <SID>prim
sap_ha_pacemaker_cluster_healthcheck_hana_secondary_id: ''  # Default: <SID>ro

# Optional dictionary with custom list of HANA Hooks for replication
sap_ha_pacemaker_cluster_hana_hooks: []
# Parameters enable additional srHooks for TkOver and ChkSrv.
# They are ignored if sap_ha_pacemaker_cluster_hana_hooks is used.
sap_ha_pacemaker_cluster_hana_hook_tkover: false
sap_ha_pacemaker_cluster_hana_hook_chksrv: false

# SAP Hana global.ini path calculated from SID
sap_ha_pacemaker_cluster_hana_global_ini_path: ''  # Default: /usr/sap/<SID>/SYS/global/hdb/custom/config/global.ini

# Disable auto-detection of SAPHanaSR-angi package and use Classic
sap_ha_pacemaker_cluster_saphanasr_angi_detection: true

################################################################################
# NetWeaver generic definitions
################################################################################

# Default will be ENSA2. To configure HA resources for ENSA1,
# set this parameter to 'true'.
sap_ha_pacemaker_cluster_nwas_cs_ensa1: false

# Enable ENSA2 simple mount configuration
sap_ha_pacemaker_cluster_nwas_cs_ers_simple_mount: true

# Enable/Disable sap_cluster_connector.
# Ref.: https://access.redhat.com/solutions/3606101
sap_ha_pacemaker_cluster_enable_cluster_connector: true

# SAP Netweaver instance details
sap_ha_pacemaker_cluster_nwas_sid: ''  # Mandatory System ID in capital letters for Netweaver scenarios
sap_ha_pacemaker_cluster_nwas_ascs_instance_nr: ''  # Mandatory instance number for ASCS/ERS
sap_ha_pacemaker_cluster_nwas_scs_instance_nr: ''   # Mandatory instance number for SCS/ERS
sap_ha_pacemaker_cluster_nwas_ers_instance_nr: ''   # Mandatory instance number for ASCS/ERS and SCS/ERS
# TODO: Differentiate between ABAP and JAVA (Dxx vs Jxx) once supported
sap_ha_pacemaker_cluster_nwas_abap_pas_instance_nr: ''  # Mandatory instance number for PAS/AAS
sap_ha_pacemaker_cluster_nwas_abap_aas_instance_nr: ''  # Mandatory instance number for PAS/AAS


# Definitions for filesystems resources. Currently limited to NFS filesystems.
sap_ha_pacemaker_cluster_storage_definition: "{{ sap_storage_setup_definition | d([]) }}"
sap_ha_pacemaker_cluster_storage_nfs_filesystem_type: nfs
sap_ha_pacemaker_cluster_storage_nfs_mount_options: 'defaults'
sap_ha_pacemaker_cluster_storage_nfs_server: "{{ sap_storage_nfs_server | d('') }}"

# NFS filesystem resource requirement
# Not adding to argument_specs because this should not be changed anyway.
# TODO: review later and move to internal vars in vars/main.yml?
sap_ha_pacemaker_cluster_resource_filesystem_force_unmount: safe


# Multiple VIP parameters can be defined and will be combined.
# See tasks/include_construct_vip_resources.yml
sap_ha_pacemaker_cluster_vip_nwas_ascs_ip_address: ''
sap_ha_pacemaker_cluster_vip_nwas_ascs_resource_name: ''  # Default rsc_vip_<SID>_ASCS<ASCS-instance-number>
sap_ha_pacemaker_cluster_healthcheck_nwas_ascs_resource_name: ''  # Default: rsc_vip_health_check_<SID>_ASCS<ASCS-instance-number>

sap_ha_pacemaker_cluster_vip_nwas_scs_ip_address: ''
sap_ha_pacemaker_cluster_vip_nwas_scs_resource_name: ''  # Default: rsc_vip_<SID>_SCS<SCS-instance-number>
sap_ha_pacemaker_cluster_healthcheck_nwas_scs_resource_name: ''  # Default: rsc_vip_health_check_<SID>_SCS<SCS-instance-number>

sap_ha_pacemaker_cluster_vip_nwas_ers_ip_address: ''
sap_ha_pacemaker_cluster_vip_nwas_ers_resource_name: ''  # Default: rsc_vip_<SID>_ERS<ERS-instance-number>
sap_ha_pacemaker_cluster_healthcheck_nwas_ers_resource_name: ''  # Default: rsc_vip_health_check_<SID>_ERS<ERS-instance-number>

sap_ha_pacemaker_cluster_vip_nwas_abap_pas_ip_address: ''
sap_ha_pacemaker_cluster_vip_nwas_abap_pas_resource_name: '' # Default: rsc_vip_<SID>_PAS<PAS-instance-number>
sap_ha_pacemaker_cluster_healthcheck_nwas_abap_pas_resource_name: ''  # Default: rsc_vip_health_check_<SID>_PAS<PAS-instance-number>

sap_ha_pacemaker_cluster_vip_nwas_abap_aas_ip_address: ''
sap_ha_pacemaker_cluster_vip_nwas_abap_aas_resource_name: '' # Default: rsc_vip_<SID>_AAS<AAS-instance-number>
sap_ha_pacemaker_cluster_healthcheck_nwas_abap_aas_resource_name: ''  # Default: rsc_vip_health_check_<SID>_AAS<AAS-instance-number>

sap_ha_pacemaker_cluster_healthcheck_nwas_ascs_id: ''
sap_ha_pacemaker_cluster_healthcheck_nwas_scs_id: ''
sap_ha_pacemaker_cluster_healthcheck_nwas_ers_id: ''
sap_ha_pacemaker_cluster_healthcheck_nwas_pas_id: ''
sap_ha_pacemaker_cluster_healthcheck_nwas_aas_id: ''

# SAP NetWeaver common - Resource IDs (names) as convenience parameters
# for the following filesystems:
# - /sapmnt
# - /usr/sap/trans
# - /usr/sap/<<SID>>/SYS
sap_ha_pacemaker_cluster_nwas_sapmnt_filesystem_resource_name: ''  # Default: rsc_fs_<SID>_sapmnt
sap_ha_pacemaker_cluster_nwas_sapmnt_filesystem_resource_clone_name: ''  # Default: cln_fs_<SID>_sapmnt

sap_ha_pacemaker_cluster_nwas_transports_filesystem_resource_name: ''  # Default: rsc_fs_<SID>_trans
sap_ha_pacemaker_cluster_nwas_transports_filesystem_resource_clone_name: '' # Default: cln_fs_<SID>_trans

sap_ha_pacemaker_cluster_nwas_sys_filesystem_resource_name: ''  # Default: rsc_fs_<SID>_sys
sap_ha_pacemaker_cluster_nwas_sys_filesystem_resource_clone_name: ''  # Default: cln_fs_<SID>_sys

# The shared filesystems are not required to be configured in the cluster.
# By default it is assumed that they are mounted by the system and available on all cluster nodes.
# Set this parameter to "true" to configure the 3 shared filesystems as part of the cluster.
sap_ha_pacemaker_cluster_nwas_shared_filesystems_cluster_managed: false


################################################################################
# ASCS and SCS shared resource defaults
################################################################################

# TODO: Remove backwards compatibility to nwas_abap_ascs
sap_ha_pacemaker_cluster_nwas_cs_sapinstance_automatic_recover_bool:
  "{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_automatic_recover_bool | d(false) }}"
sap_ha_pacemaker_cluster_nwas_cs_sapinstance_resource_stickiness:
  "{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_resource_stickiness | d(5000) }}"
sap_ha_pacemaker_cluster_nwas_cs_sapinstance_ensa1_migration_threshold:
  "{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_ensa1_migration_threshold | d(1) }}"
sap_ha_pacemaker_cluster_nwas_cs_sapinstance_ensa1_failure_timeout:
  "{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_ensa1_failure_timeout | d(60) }}"
sap_ha_pacemaker_cluster_nwas_cs_group_stickiness:
  "{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_group_stickiness | d(3000) }}"


################################################################################
# ASCS resource defaults
################################################################################

sap_ha_pacemaker_cluster_nwas_ascs_sapinstance_instance_name: ''  # Mandatory name of instance profile
sap_ha_pacemaker_cluster_nwas_ascs_sapinstance_start_profile_string: ''  # Full path of instance profile

sap_ha_pacemaker_cluster_nwas_ascs_filesystem_resource_name: ''  # Default: rsc_fs_<SID>_ASCS<ASCS-instance-number>
sap_ha_pacemaker_cluster_nwas_ascs_sapinstance_resource_name: ''  # Default: rsc_SAPInstance_<SID>_ASCS<ASCS-instance-number>
sap_ha_pacemaker_cluster_nwas_ascs_sapstartsrv_resource_name: ''  # Default: rsc_SAPStartSrv_<SID>_ASCS<ASCS-instance-number>

sap_ha_pacemaker_cluster_vip_nwas_ascs_resource_group_name: ''  # Default: grp_<SID>_ASCS<ASCS-instance-number>

sap_ha_pacemaker_cluster_nwas_colocation_ascs_no_ers_name: ''  # Default: col_ascs_separate_<SID>
sap_ha_pacemaker_cluster_nwas_order_ascs_first_name: ''  # Default: ord_ascs_first_<SID>


################################################################################
# SCS resource defaults
################################################################################

sap_ha_pacemaker_cluster_nwas_scs_sapinstance_instance_name: ''  # Mandatory name of instance profile
sap_ha_pacemaker_cluster_nwas_scs_sapinstance_start_profile_string: ''  # Full path of instance profile

sap_ha_pacemaker_cluster_nwas_scs_filesystem_resource_name: ''  # Default: rsc_fs_<SID>_SCS<SCS-instance-number>
sap_ha_pacemaker_cluster_nwas_scs_sapinstance_resource_name: ''  # Default: rsc_SAPInstance_<SID>_SCS<SCS-instance-number>
sap_ha_pacemaker_cluster_nwas_scs_sapstartsrv_resource_name: ''  # Default: rsc_SAPStartSrv_<SID>_SCS<SCS-instance-number>

sap_ha_pacemaker_cluster_vip_nwas_scs_resource_group_name: ''  # Default: grp_<SID>_SCS<SCS-instance-number>

sap_ha_pacemaker_cluster_nwas_colocation_scs_no_ers_name: ''  # Default: col_ascs_separate_<SID>
sap_ha_pacemaker_cluster_nwas_order_scs_first_name: ''  # Default: ord_ascs_first_<SID>


################################################################################
# ERS resource defaults
################################################################################

sap_ha_pacemaker_cluster_nwas_ers_sapinstance_instance_name: ''  # Mandatory name of instance profile
sap_ha_pacemaker_cluster_nwas_ers_sapinstance_start_profile_string: ''  # Full path of instance profile

sap_ha_pacemaker_cluster_nwas_ers_filesystem_resource_name: ''  # Default: rsc_fs_<SID>_ERS<ERS-instance-number>
sap_ha_pacemaker_cluster_nwas_ers_sapinstance_resource_name: ''  # Default: rsc_SAPInstance_<SID>_ERS<ERS-instance-number>
sap_ha_pacemaker_cluster_nwas_ers_sapstartsrv_resource_name: ''  # Default: rsc_SAPStartSrv_<SID>_ERS<ERS-instance-number>
sap_ha_pacemaker_cluster_vip_nwas_ers_resource_group_name: ''  # Default: grp_<SID>_ERS<ERS-instance-number>

sap_ha_pacemaker_cluster_nwas_ers_sapinstance_automatic_recover_bool: false

################################################################################
# PAS/AAS resource defaults
################################################################################
# sap_ha_pacemaker_cluster_nwas_abap_pas_filesystem_resource_name: ''
# sap_ha_pacemaker_cluster_nwas_abap_pas_sapinstance_resource_name: ''
# sap_ha_pacemaker_cluster_nwas_abap_aas_filesystem_resource_name: ''
# sap_ha_pacemaker_cluster_nwas_abap_aas_sapinstance_resource_name: ''


################################################################################
# Platform specific
################################################################################

## Infrastructure Platform variables, shown here for visibility only and should not be given default values

## AWS platform, EC2 Virtual Servers
# sap_ha_pacemaker_cluster_aws_vip_update_rt
# sap_ha_pacemaker_cluster_aws_access_key_id
# sap_ha_pacemaker_cluster_aws_secret_access_key
# sap_ha_pacemaker_cluster_aws_region
# sap_ha_pacemaker_cluster_aws_credentials_setup: false

## Google Cloud platform, Compute Engine Virtual Machines
# sap_ha_pacemaker_cluster_gcp_project
# sap_ha_pacemaker_cluster_gcp_region_zone

## IBM Cloud platform, Virtual Servers (x86_64)
# sap_ha_pacemaker_cluster_ibmcloud_api_key
# sap_ha_pacemaker_cluster_ibmcloud_region

## IBM Cloud platform, IBM Power Virtual Servers (ppc64le)
# sap_ha_pacemaker_cluster_ibmcloud_api_key
# sap_ha_pacemaker_cluster_ibmcloud_region
# sap_ha_pacemaker_cluster_ibmcloud_powervs_workspace_crn
# sap_ha_pacemaker_cluster_ibmcloud_powervs_api_type
# sap_ha_pacemaker_cluster_ibmcloud_powervs_forward_proxy_url

## IBM PowerVM hypervisor, Virtual Machines (LPAR, ppc64le)
# sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host
# sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_port # default, SSH Port 22
# sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_login
# sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_login_password
# sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_version

## MS Azure platform, Virtual Machines
# sap_ha_pacemaker_cluster_msazure_subscription_id
# sap_ha_pacemaker_cluster_msazure_resource_group
