# SPDX-License-Identifier: Apache-2.0
---

# Update /etc/hosts for NW

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' will not be configured for NW due to missing 'sap_swpm_fqdn'
  ansible.builtin.debug:
    msg: "WARN: Not configuring NW entries in '/etc/hosts' because 'sap_swpm_fqdn' is not defined!"
  when:
    (sap_swpm_fqdn | type_debug == 'NoneType') or
    (sap_swpm_fqdn | length == 0)

- name: SAP SWPM Pre Install - Update '/etc/hosts' for NW
  ansible.builtin.import_role:
    name: '{{ sap_swpm_sap_install_collection }}.sap_maintain_etc_hosts'
  vars:
    sap_maintain_etc_hosts_list:
      - node_ip: "{{ ansible_default_ipv4.address | d(ansible_all_ipv4_addresses[0]) }}"
        node_name: "{{ ansible_hostname }}"
        node_domain: "{{ sap_swpm_fqdn }}"
        state: present
  when:
    - "sap_swpm_fqdn | type_debug != 'NoneType'"
    - "sap_swpm_fqdn | length > 0"

# Update /etc/hosts for HANA

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' will not be configured for HANA due to missing 'sap_swpm_db_ip'
  ansible.builtin.debug:
    msg: "WARN: Not configuring HANA entries in '/etc/hosts' because 'sap_swpm_db_ip' is not defined!"
  when:
    (sap_swpm_db_ip | type_debug == 'NoneType') or
    (sap_swpm_db_ip | length == 0)

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' will not be configured for HANA due to missing 'sap_swpm_db_host'
  ansible.builtin.debug:
    msg: "WARN: Not configuring HANA entries in '/etc/hosts' because 'sap_swpm_db_host' is not defined!"
  when:
    (sap_swpm_db_host | type_debug == 'NoneType') or
    (sap_swpm_db_host | length == 0)

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' will not be configured for HANA because 'sap_swpm_db_host' is the current host
  ansible.builtin.debug:
    msg: "WARN: Not configuring HANA entries in '/etc/hosts' because 'sap_swpm_db_host' is the current host!"
  when: sap_swpm_db_host == ansible_hostname

- name: SAP SWPM Pre Install - Update '/etc/hosts' for HANA
  ansible.builtin.import_role:
    name: '{{ sap_swpm_sap_install_collection }}.sap_maintain_etc_hosts'
  vars:
    sap_maintain_etc_hosts_list:
      - node_ip: "{{ sap_swpm_db_ip }}"
        node_name: "{{ sap_swpm_db_host }}"
        node_domain: "{{ sap_swpm_fqdn }}"
        state: present
  when:
    - "sap_swpm_db_ip | type_debug != 'NoneType'"
    - "sap_swpm_db_ip | length > 0"
    - "sap_swpm_db_host | type_debug != 'NoneType'"
    - "sap_swpm_db_host | length > 0"
    - "sap_swpm_db_host != ansible_hostname"
