---

# Ensure {{ sap_hostagent_agent_tmp_directory }} directory is removed from the target host
- name: Ensure {{ sap_hostagent_agent_tmp_directory }} directory does not exist
  ansible.builtin.file:
    path: "{{ sap_hostagent_agent_tmp_directory }}"
    state: absent
    mode: '0755'
  when: sap_hostagent_clean_tmp_directory
