---
# Reminder: This file is included in a loop over a dictionary.
# Included in: tasks/include_construct_vip_resources.yml
#
# file loop var: vip_list_item
#
# Example:
# {{ vip_list_item.key }}   => vip_SID_00_primary
# {{ vip_list_item.value }} => 192.168.1.10
#
# Example for HC definition:
# {{ vip_list_item.key }}   => hc_vip_SID_00_primary
# {{ vip_list_item.value }} => 62600

# Azure requires 2 resources for the floating IP setup.
#
# 1) resource type "IPaddr2"
#   => is already created through construct_vars_vip_resources_default.yml


# 2) resource type "azure_lb" (requires 'socat')

#- name: "SAP HA Prepare Pacemaker - MS Azure - Verify socat binary path"
#  ansible.builtin.shell: |
#    which socat
#  register: __sap_ha_pacemaker_cluster_register_socat_path
#  changed_when: false

# Hint: the 'vip_list_item's will only be the ones matching the cluster host type.
- name: "SAP HA Prepare Pacemaker - MS Azure - Add resource: Azure Load Balancer (NLB L-4) for VIP routing: {{ vip_list_item.key }} (azure_lb)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__health_check] }}"
  vars:
    __health_check:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: port
              value: "{{ vip_list_item.value }}"
#            - name: nc
#              value: "{{ __sap_ha_pacemaker_cluster_register_socat_path.stdout }}"
  when:
    - sap_ha_pacemaker_cluster_vip_method == 'azure_lb'
    - __health_check.id in __sap_ha_pacemaker_cluster_healthcheck_resource_list
    - __health_check.id not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
#    - __sap_ha_pacemaker_cluster_register_socat_path.stdout is defined
#    - __sap_ha_pacemaker_cluster_register_socat_path.stdout | length > 0
