---
# Reminder: This file is included in a loop over a dictionary.

- name: "SAP HA Prepare Pacemaker - ipaddr resource agent - Add resource: OS network interface Virtual IP"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents['ipaddr'].agent }}"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"
            - name: cidr_netmask
              value: 32
            - name: nic
              value: "{{ sap_ha_pacemaker_cluster_vip_client_interface }}"
  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - (sap_ha_pacemaker_cluster_vip_method == 'ipaddr') or
      (__sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with is defined and
      'ipaddr' in __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with)

- name: "SAP HA Prepare Pacemaker - haproxy resource agent - Add resource: Google Cloud Load Balancing Internal passthrough Network Load Balancer (NLB L-4) for VIP routing when SAP HANA scale-up HA"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__health_check] }}"
  vars:
    __health_check:
      id: "hc_{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      operations:
        - action: monitor
          attrs:
            - name: interval
              value: 10
            - name: timeout
              value: 20
  when:
    - __health_check.id is not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - ('hc_' + vip_list_item.key) not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'gcp_nlb_reserved_ip_haproxy'
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0
