---
# Reminder: This file is included in a loop over a dictionary.

- name: "SAP HA Prepare Pacemaker - ipaddr resource agent - Add resource: OS network interface Virtual IP"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents['ipaddr'].agent }}"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"
            - name: nic
              value: "{{ sap_ha_pacemaker_cluster_vip_client_interface }}"
  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - (sap_ha_pacemaker_cluster_vip_method == 'ipaddr') or
      (__sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with is defined and
      'ipaddr' in __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with)
