---
# Reminder: This file is included in a loop over a dictionary.
# Included in: tasks/include_construct_vip_resources.yml
#
# file loop var: vip_list_item
#
# Example:
# {{ vip_list_item.key }}   => vip_SID_00_primary
# {{ vip_list_item.value }} => 192.168.1.10

# 1. Using the IPaddr2 resource agent is not recommended nor supported
# 2. IPaddr2 resources would be created by construct_vars_vip_resources_default.yml
#
# Using 'awsvip' is also not recommended or supported officially for SAP setups.
# This is for testing purpose only and works together with the standard IPaddr2 resource.
- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Add resource: AWS floating IP: {{ vip_list_item.key }} (awsvip - dev/test only!)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"  # pri_ prefix removed
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: secondary_private_ip
              value: "{{ vip_list_item.value }}"
  when:
#     - ('pri_' ~ vip_list_item.key) not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'awsvip'
    - vip_list_item.key in __sap_ha_pacemaker_cluster_vip_resource_list

- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Add resource group for VIP resources (dev/test only)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_groups: "{{ __sap_ha_pacemaker_cluster_resource_groups + [__vip_group] }}"
  vars:
    __vip_group:
      id: "{{ sap_ha_pacemaker_cluster_vip_group_prefix }}{{ vip_list_item.key }}"
      resource_ids:
        - "{{ vip_list_item.key }}"
#        - "pri_{{ vip_list_item.key }}"
  when:
    - __vip_group.id is not in (__sap_ha_pacemaker_cluster_resource_groups | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method in ['awsvip']
    - vip_list_item.key in __sap_ha_pacemaker_cluster_vip_resource_list

# The following is the officially recommended and supported method for VIP resources on AWS EC2.
- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Add resource: AWS VIP OverlayIP: {{ vip_list_item.key }} (aws_vpc_move_ip)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"
            - name: interface
              value: "{{ sap_ha_pacemaker_cluster_vip_client_interface }}"
            - name: routing_table
              value: "{{ sap_ha_pacemaker_cluster_aws_vip_update_rt }}"
  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'aws_vpc_move_ip'
    - vip_list_item.key in __sap_ha_pacemaker_cluster_vip_resource_list
