# SPDX-License-Identifier: Apache-2.0
---
# Reminder: This file is included in a loop over a dictionary.
# Included in: tasks/include_construct_vip_resources.yml
#
# file loop var: vip_list_item
#
# Example:
# {{ vip_list_item.key }}   => vip_SID_00_primary
# {{ vip_list_item.value }} => 192.168.1.10

- name: "SAP HA Prepare Pacemaker - GCP CE - Add resource: OS network interface Virtual IP: {{ vip_list_item.key }} (IPaddr2)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents['ipaddr'].agent | d('ocf:heartbeat:IPaddr2') }}"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"
            - name: cidr_netmask
              value: 32
            - name: nic
              value: "{{ sap_ha_pacemaker_cluster_vip_client_interface }}"
      operations:
        - action: monitor
          attrs:
            - name: interval
              value: 3600

  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'ipaddr' or
      (__sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with is defined and
      __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with == 'ipaddr')
    - vip_list_item.key in __sap_ha_pacemaker_cluster_vip_resource_list

- name: "SAP HA Prepare Pacemaker - GCP CE - Add resource: Network Load Balancer (NLB L-4) for VIP routing: {{ vip_list_item.key }} (haproxy)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__health_check] }}"
  vars:
    __health_check:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent + '@' + __haproxy_id }}"
      operations:
        - action: monitor
          attrs:
            - name: interval
              value: 10
            - name: timeout
              value: 20

    __haproxy_id: >-
      {% if vip_list_item.key == __sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name -%}
        {{ __sap_ha_pacemaker_cluster_healthcheck_hana_primary_id }}
      {%- elif vip_list_item.key == __sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name
        and sap_ha_pacemaker_cluster_healthcheck_hana_secondary_port | length > 4 -%}
        {{ __sap_ha_pacemaker_cluster_healthcheck_hana_secondary_id }}
      {%- elif vip_list_item.key == __sap_ha_pacemaker_cluster_healthcheck_nwas_ascs_resource_name -%}
        {{ __sap_ha_pacemaker_cluster_healthcheck_nwas_ascs_id }}
      {%- elif vip_list_item.key == __sap_ha_pacemaker_cluster_healthcheck_nwas_ers_resource_name -%}
        {{ __sap_ha_pacemaker_cluster_healthcheck_nwas_ers_id }}
      {%- elif vip_list_item.key == __sap_ha_pacemaker_cluster_healthcheck_nwas_abap_pas_resource_name -%}
        {{ __sap_ha_pacemaker_cluster_healthcheck_nwas_pas_id }}
      {%- elif vip_list_item.key == __sap_ha_pacemaker_cluster_healthcheck_nwas_abap_aas_resource_name -%}
        {{ __sap_ha_pacemaker_cluster_healthcheck_nwas_aas_id }}
      {%- else -%}
      {%- endif %}

  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'gcp_nlb_reserved_ip_haproxy'
    - vip_list_item.key in __sap_ha_pacemaker_cluster_healthcheck_resource_list
    - __haproxy_id | length > 0


- name: "SAP HA Prepare Pacemaker - GCP CE - Add resource: Socat resource for Health Checks (socat)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__health_check] }}"
  vars:
    __health_check:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: binfile
              value: "/usr/bin/socat"
            - name: cmdline_options
              value: "-U TCP-LISTEN:{{ vip_list_item.value }},backlog=10,fork,reuseaddr /dev/null"
      operations:
        - action: monitor
          attrs:
            - name: interval
              value: 10
            - name: timeout
              value: 20

  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'gcp_anything_socat'
    - vip_list_item.key in __sap_ha_pacemaker_cluster_healthcheck_resource_list
