---
# Reminder: This file is included in a loop over a dictionary.

- name: "SAP HA Prepare Pacemaker - ipaddr resource agent - Add resource: OS network interface Virtual IP (dev/test only)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"
            - name: nic
              value: "{{ sap_ha_pacemaker_cluster_vip_client_interface }}"
  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - (sap_ha_pacemaker_cluster_vip_method == 'ipaddr') or
      (__sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with is defined and
      'ipaddr' in __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].with)

- name: "SAP HA Prepare Pacemaker - awsvip resource agent - Add resource: AWS floating IP (dev/test only)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "pri_{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: secondary_private_ip
              value: "{{ vip_list_item.value }}"
  when:
    - ('pri_' ~ vip_list_item.key) not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'awsvip'

- name: "SAP HA Prepare Pacemaker - awsvip resource agent - Add resource group for VIP resources (dev/test only)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_groups: "{{ __sap_ha_pacemaker_cluster_resource_groups + [__vip_group] }}"
  vars:
    __vip_group:
      id: "{{ sap_ha_pacemaker_cluster_vip_resource_group_name }}_{{ vip_list_item.key }}"
      resource_ids:
        - "{{ vip_list_item.key }}"
        - "pri_{{ vip_list_item.key }}"
  when:
    - __vip_group.id is not in (__sap_ha_pacemaker_cluster_resource_groups | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method in ['awsvip']

- name: "SAP HA Prepare Pacemaker - aws_vpc_move_ip resource agent - Add resource: AWS VIP OverlayIP"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ vip_list_item.key }}"
      agent: "{{ __sap_ha_pacemaker_cluster_available_vip_agents[sap_ha_pacemaker_cluster_vip_method].agent }}"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"
            - name: interface
              value: "{{ sap_ha_pacemaker_cluster_vip_client_interface }}"
            - name: routing_table
              value: "{{ sap_ha_pacemaker_cluster_aws_vip_update_rt }}"
  when:
    - vip_list_item.key not in (__sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id'))
    - sap_ha_pacemaker_cluster_vip_method == 'aws_vpc_move_ip'
