---

# Include vars files based on the environment.
- name: "SAP HA Prepare Pacemaker - Include platform specific variables"
  when: __sap_ha_pacemaker_cluster_vars_file is file
  ansible.builtin.include_vars: "{{ __sap_ha_pacemaker_cluster_vars_file }}"
  loop:
    - "platform_{{ __sap_ha_pacemaker_cluster_platform }}.yml"
  vars:
    __sap_ha_pacemaker_cluster_vars_file: "{{ role_path }}/vars/{{ item }}"


# pcmk_host_map format: <hostname1>:<host1-id>;<hostname2>:<host2-id>...
- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: |-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].ansible_board_asset_tag }}
        {%- if not loop.last %};{% endif %}
      {% endfor %}
  when: __sap_ha_pacemaker_cluster_platform == "cloud_aws_ec2_vs"

- name: "SAP HA Prepare Pacemaker - IBM Power VS from IBM Cloud - Set variable for fencing agent"
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_ibmcloud_powervs_host_guid: "{{ __sap_ha_pacemaker_cluster_register_ibmcloud_powervs_host }}"
    sap_ha_pacemaker_cluster_ibmcloud_powervs_workspace_guid: '{{ __sap_ha_pacemaker_cluster_register_ibmcloud_powervs_workspace_crn | replace("::","") | regex_replace(".*\:") }}'
  when: __sap_ha_pacemaker_cluster_platform == "cloud_ibmcloud_powervs"

# pcmk_host_map format: <hostname1>:<host1-id>;<hostname2>:<host2-id>...
- name: "SAP HA Prepare Pacemaker - IBM Power VS from IBM Cloud - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: |-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].sap_ha_pacemaker_cluster_ibmcloud_powervs_instance_id }}
        {%- if not loop.last %};{% endif %}
      {% endfor %}
  when: __sap_ha_pacemaker_cluster_platform == "cloud_ibmcloud_powervs"


- name: "SAP HA Prepare Pacemaker - IBM PowerVM - Set variable for fencing agent"
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_ibmpower_vm_hmc_system_partition_name: "{{ __sap_ha_pacemaker_cluster_register_ibmpower_vm_hmc_system_partition_name.stdout }}"
    sap_ha_pacemaker_cluster_ibmpower_vm_hmc_system_host_mtms: "{{ __sap_ha_pacemaker_cluster_register_ibmpower_vm_hmc_system_host_mtms_gui_string.stdout }}"

  when: __sap_ha_pacemaker_cluster_platform == "hyp_ibmpower_vm"

# pcmk_host_map format: <hostname1>:<host1-id>;<hostname2>:<host2-id>...
- name: "SAP HA Prepare Pacemaker - IBM PowerVM - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: |-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].sap_ha_pacemaker_cluster_ibmpower_vm_hmc_system_partition_name }}
        {%- if not loop.last %};{% endif %}
      {% endfor %}
  when: __sap_ha_pacemaker_cluster_platform == "hyp_ibmpower_vm"


# pcmk_host_map format: <hostname1>:<host1-id>;<hostname2>:<host2-id>...
- name: "SAP HA Prepare Pacemaker - IBM Cloud VS - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: |-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].__sap_ha_pacemaker_cluster_register_ibmcloud_vs_host.stdout }}
        {%- if not loop.last %};{% endif %}
      {% endfor %}
  when: __sap_ha_pacemaker_cluster_platform == "cloud_ibmcloud_vs"


# pcmk_host_map format: <hostname1>:<hostname1>;<hostname2>:<hostname2>...
- name: "SAP HA Prepare Pacemaker - MS Azure VM - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: |-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].ansible_hostname }}
        {%- if not loop.last %};{% endif %}
      {% endfor %}
  when: __sap_ha_pacemaker_cluster_platform == "cloud_msazure_vm"
