---
# Requirement to enable the fencing resource to function.


# pcmk_host_map format: <hostname1>:<hostname1>;<hostname2>:<hostname2>...
- name: "SAP HA Prepare Pacemaker - MS Azure VM - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: >-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].ansible_hostname }}
      {%-  if not loop.last %};{%- endif -%}
      {%- endfor %}
