---
# Requirement to enable the fencing resource to function.


# pcmk_host_map format: <hostname1>:<host1-id>;<hostname2>:<host2-id>...
- name: "SAP HA Prepare Pacemaker - IBM Cloud VS - Assemble host mapping"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_pcmk_host_map: >-
      {% for node in ansible_play_hosts_all -%}
        {{ hostvars[node].ansible_hostname }}:{{ hostvars[node].__sap_ha_pacemaker_cluster_register_ibmcloud_vs_host.stdout }}
      {%-  if not loop.last %};{%- endif -%}
      {%- endfor %}
