---
# Requirement to enable the fencing resource to function.

- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Create awscli config directory"
  ansible.builtin.file:
    mode: 0755
    owner: root
    path: /root/.aws
    state: directory

- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Create awscli config"
  ansible.builtin.blockinfile:
    backup: true
    block: |
      [default]
      region = {{ sap_ha_pacemaker_cluster_aws_region }}
    create: true
    mode: 0600
    owner: root
    path: /root/.aws/config

- name: "SAP HA Prepare Pacemaker - AWS EC2 VS - Store awscli credentials"
  ansible.builtin.blockinfile:
    backup: true
    block: |
      [default]
      aws_access_key_id = {{ sap_ha_pacemaker_cluster_aws_access_key_id }}
      aws_secret_access_key = {{ sap_ha_pacemaker_cluster_aws_secret_access_key }}
    create: true
    mode: 0600
    owner: root
    path: /root/.aws/credentials
  no_log: true
