---
# Ansible facts rely on SMBIOS/DMI, which does not exist on ppc64le CPU Architecture.
# Identify from RSCT binary instead.
- name: "SAP HA Prepare Pacemaker - IBM Power VS from IBM Cloud - Register instance ID"
  ansible.builtin.shell: |
    /opt/rsct/bin/ctgethscid -value PartitionUUID
  register: __sap_ha_pacemaker_cluster_register_ibmcloud_powervs_host
  changed_when: false
  check_mode: false
