---
# Ansible facts rely on SMBIOS/DMI, which does not exist on ppc64le CPU Architecture.

# Discovered input used for plug (via pcmk_host_map)
# The Instance ID in the IBM Power Virtual Server Workspace, is identical string to the UUID reported in the host
# alt command using IBM Power RSCT binary: /opt/rsct/bin/ctgethscid | grep PartitionUUID | cut -d \" -f2
# alt command using cloud-init data: cat /run/cloud-init/instance-data.json | grep uuid | cut -d \" -f4
# alt command using cloud-init data: cat /run/cloud-init/instance-data.json | grep instance_id | cut -d \" -f4
- name: "SAP HA Prepare Pacemaker -  IBM Cloud Power VS - IBM Power Virtual Server UUID"
  ansible.builtin.shell: |
    set -o pipefail && echo $(tr -d '\0' < /proc/device-tree/ibm,partition-uuid)
  register: __sap_ha_pacemaker_cluster_register_ibmcloud_powervs_host
  changed_when: false
  check_mode: false

- name: "SAP HA Prepare Pacemaker - Ensure ipcalc binary installed"
  ansible.builtin.package:
    name:
      - ipcalc
    state: present

- name: "SAP HA Prepare Pacemaker - IBM Cloud PowerVS - Calculate network interface subnet CIDR"
  ansible.builtin.shell: |
    set -o pipefail && ipcalc --prefix \
     {{ ansible_facts[sap_ha_pacemaker_cluster_vip_client_interface].ipv4.network
     + '/' + ansible_facts[sap_ha_pacemaker_cluster_vip_client_interface].ipv4.netmask }} \
     | sed 's|PREFIX=||'
  register: __sap_ha_pacemaker_cluster_vip_client_interface_subnet_cidr
  changed_when: false
  check_mode: false
