---
# Identify if SAPHanaSR-angi package is available for installation.
# SAPHanaSR-angi replaces SAPHanaSR and SAPHanaSR-ScaleOut.

# TODO:
# Add RedHat specific steps to identify SAPHanaSR-angi package.
