# SPDX-License-Identifier: Apache-2.0
---

- name: Display the role path
  ansible.builtin.debug:
    var: role_path
  tags:
    - always

# Example of files loading order:
# 1. Suse.yml / RedHat.yml - Specific to OS family.
# 2. SLES_15.yml / RedHat_9.yml - Specific to distribution (SLES, SLES_SAP or RedHat) and major release.
# 3. SLES_15.6.yml / RedHat_9.2 - Specific to distribution (SLES, SLES_SAP or RedHat) and minor release.
# 4. SLES_SAP_15.yml - Specific to distribution SLES_SAP and major release.
# 5. SLES_SAP_15.6.yml - Specific to distribution SLES_SAP and minor release.
- name: Include OS specific vars, specific
  ansible.builtin.include_vars: "{{ __vars_file }}"
  loop: "{{ __var_files }}"
  vars:
    __vars_file: "{{ role_path }}/vars/{{ item }}"
    __distribution_major: "{{ ansible_distribution ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_minor: "{{ ansible_distribution ~ '_' ~ ansible_distribution_version }}"
    # Enables loading of shared vars between SLES and SLES_SAP
    __distribution_major_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_minor_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_version }}"
    __var_files: >-
      {{
        [
          ansible_os_family ~ '.yml',
          (ansible_distribution ~ '.yml') if ansible_distribution != ansible_os_family else None,
          (__distribution_major_split ~ '.yml') if __distribution_major_split != __distribution_major else None,
          (__distribution_minor_split ~ '.yml') if __distribution_minor_split != __distribution_minor else None,
          __distribution_major ~ '.yml',
          __distribution_minor ~ '.yml'
        ] | select('defined') | select('string') | list
      }}
  when: __vars_file is file
  tags:
    - always


- name: Rename user sap_preconfigure variables if found, generic
  ansible.builtin.set_fact:
    sap_general_preconfigure_config_all: "{{ (sap_preconfigure_config_all | d(sap_general_preconfigure_config_all)) | d(true) }}"
    sap_general_preconfigure_installation: "{{ (sap_preconfigure_installation | d(sap_general_preconfigure_installation)) | d(false) }}"
    sap_general_preconfigure_configuration: "{{ (sap_preconfigure_configuration | d(sap_general_preconfigure_configuration)) | d(false) }}"
    sap_general_preconfigure_assert: "{{ sap_preconfigure_assert | d(sap_general_preconfigure_assert) }}"
    sap_general_preconfigure_assert_ignore_errors: "{{ sap_preconfigure_assert_ignore_errors | d(sap_general_preconfigure_assert_ignore_errors) }}"
    sap_general_preconfigure_packagegroups: "{{ sap_preconfigure_packagegroups | d(sap_general_preconfigure_packagegroups) }}"
    sap_general_preconfigure_envgroups: "{{ sap_preconfigure_envgroups | d(sap_general_preconfigure_envgroups) }}"
    sap_general_preconfigure_packages: "{{ sap_preconfigure_packages | d(sap_general_preconfigure_packages) }}"
    sap_general_preconfigure_min_package_check: "{{ sap_preconfigure_min_package_check | d(sap_general_preconfigure_min_package_check) }}"
    sap_general_preconfigure_update: "{{ sap_preconfigure_update | d(sap_general_preconfigure_update) }}"
    sap_general_preconfigure_reboot_ok: "{{ sap_preconfigure_reboot_ok | d(sap_general_preconfigure_reboot_ok) }}"
    sap_general_preconfigure_fail_if_reboot_required: "{{ sap_preconfigure_fail_if_reboot_required | d(sap_general_preconfigure_fail_if_reboot_required) }}"
    sap_general_preconfigure_selinux_state: "{{ sap_preconfigure_selinux_state | d(sap_general_preconfigure_selinux_state) }}"
    sap_general_preconfigure_size_of_tmpfs_gb: "{{ sap_preconfigure_size_of_tmpfs_gb | d(sap_general_preconfigure_size_of_tmpfs_gb) }}"
#    sap_general_preconfigure_locale: "{{ sap_preconfigure_locale | d(sap_general_preconfigure_locale) }}"
    sap_general_preconfigure_modify_etc_hosts: "{{ sap_preconfigure_modify_etc_hosts | d(sap_general_preconfigure_modify_etc_hosts) }}"
    sap_general_preconfigure_kernel_parameters: "{{ sap_preconfigure_kernel_parameters | d(sap_general_preconfigure_kernel_parameters) }}"
    sap_general_preconfigure_max_hostname_length: "{{ sap_preconfigure_max_hostname_length | d(sap_general_preconfigure_max_hostname_length) }}"
  tags:
    - always

- name: Rename user sap_preconfigure variables if found, RHEL only
  ansible.builtin.set_fact:
    sap_general_preconfigure_2002167_02: "{{ (sap_preconfigure_2002167_02 | d(sap_general_preconfigure_2002167_02)) | d(false) }}"
    sap_general_preconfigure_2002167_03: "{{ (sap_preconfigure_2002167_03 | d(sap_general_preconfigure_2002167_03)) | d(false) }}"
    sap_general_preconfigure_2002167_04: "{{ (sap_preconfigure_2002167_04 | d(sap_general_preconfigure_2002167_04)) | d(false) }}"
    sap_general_preconfigure_2002167_05: "{{ (sap_preconfigure_2002167_05 | d(sap_general_preconfigure_2002167_05)) | d(false) }}"
    sap_general_preconfigure_2002167_06: "{{ (sap_preconfigure_2002167_06 | d(sap_general_preconfigure_2002167_06)) | d(false) }}"
    sap_general_preconfigure_0941735: "{{ (sap_preconfigure_0941735 | d(sap_general_preconfigure_0941735)) | d(false) }}"
    sap_general_preconfigure_1391070: "{{ (sap_preconfigure_1391070 | d(sap_general_preconfigure_1391070)) | d(false) }}"
    sap_general_preconfigure_1771258: "{{ (sap_preconfigure_1771258 | d(sap_general_preconfigure_1771258) | d(false)) }}"
    sap_general_preconfigure_2772999_02: "{{ (sap_preconfigure_2772999_02 | d(sap_general_preconfigure_2772999_02) | d(false)) }}"
    sap_general_preconfigure_2772999_03: "{{ (sap_preconfigure_2772999_03 | d(sap_general_preconfigure_2772999_03) | d(false)) }}"
    sap_general_preconfigure_2772999_04: "{{ (sap_preconfigure_2772999_04 | d(sap_general_preconfigure_2772999_04) | d(false)) }}"
    sap_general_preconfigure_2772999_05: "{{ (sap_preconfigure_2772999_05 | d(sap_general_preconfigure_2772999_05) | d(false)) }}"
    sap_general_preconfigure_2772999_06: "{{ (sap_preconfigure_2772999_06 | d(sap_general_preconfigure_2772999_06) | d(false)) }}"
    sap_general_preconfigure_2772999_07: "{{ (sap_preconfigure_2772999_07 | d(sap_general_preconfigure_2772999_07) | d(false)) }}"
    sap_general_preconfigure_2772999_08: "{{ (sap_preconfigure_2772999_08 | d(sap_general_preconfigure_2772999_08)) | d(false) }}"
    sap_general_preconfigure_2772999_09: "{{ (sap_preconfigure_2772999_09 | d(sap_general_preconfigure_2772999_09)) | d(false) }}"
    sap_general_preconfigure_2772999_10: "{{ (sap_preconfigure_2772999_10 | d(sap_general_preconfigure_2772999_10)) | d(false) }}"
  when: ansible_facts['distribution'] in ['RedHat']
  tags:
    - always

- name: Rename sap_preconfigure_db_group_name if defined
  ansible.builtin.set_fact:
    sap_general_preconfigure_db_group_name: "{{ sap_preconfigure_db_group_name | d(sap_general_preconfigure_db_group_name) }}"
  when: sap_preconfigure_db_group_name is defined or sap_general_preconfigure_db_group_name is defined
  tags:
    - always

- name: Set filename prefix to empty string if role is run in normal mode
  ansible.builtin.set_fact:
    __sap_general_preconfigure_fact_assert_filename_prefix: ""
  when: not sap_general_preconfigure_assert | d(false)
  tags:
    - always

- name: Prepend filename with assert string if role is run in assert mode
  ansible.builtin.set_fact:
    __sap_general_preconfigure_fact_assert_filename_prefix: "assert-"
  when: sap_general_preconfigure_assert | d(false)
  tags:
    - always

- name: Include tasks from 'installation.yml'
  ansible.builtin.include_tasks:
    file: '{{ item }}/{{ __sap_general_preconfigure_fact_assert_filename_prefix }}installation.yml'
    apply:
      tags: sap_general_preconfigure_installation
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_installation | d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'
    - '{{ ansible_os_family }}.yml'
  tags:
    - sap_general_preconfigure_installation

- name: Include tasks from 'configuration.yml'
  ansible.builtin.include_tasks:
    file: '{{ item }}/{{ __sap_general_preconfigure_fact_assert_filename_prefix }}configuration.yml'
    apply:
      tags: sap_general_preconfigure_configuration
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_configuration | d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'
    - '{{ ansible_os_family }}.yml'
  tags:
    - always

# allow a reboot at the end of the preconfigure role
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - always
