# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  namespace: community
  author: Red Hat for SAP Community of Practice, Bernd Finger, Rainer Leber
  description: Prepare Linux OS (RHEL, SLES) with specific configurations required for SAP NetWeaver installation
  company: Red Hat, Inc.
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [ 7, 8, 9 ]
  galaxy_tags: [ 'sap', 'netweaver', 'rhel', 'redhat', 'sles', 'suse' ]
dependencies: []
