---

- name: Rename some variables used by hdblcm configfile
  ansible.builtin.set_fact:
    sap_hana_install_sid: "{{ sap_hana_sid | d(sap_hana_install_sid) | d('') }}"
    sap_hana_install_number: "{{ sap_hana_instance_number | d(sap_hana_install_instance_nr) | d(sap_hana_install_instance_number) | d(sap_hana_install_number) | d('') }}"
    sap_hana_install_master_password: "{{ sap_hana_install_common_master_password | d(sap_hana_install_master_password) }}"
    sap_hana_install_system_usage: "{{ sap_hana_install_env_type | d(sap_hana_install_system_usage) }}"
    sap_hana_install_restrict_max_mem: "{{ sap_hana_install_mem_restrict | d(sap_hana_install_restrict_max_mem) }}"
  tags:
    - sap_hana_install_check_hana_exists
    - sap_hana_install_preinstall
    - sap_hana_install_set_log_mode
    - sap_hana_install_configure_firewall

- name: Fail if necessary variable 'sap_hana_install_sid' is not defined
  ansible.builtin.fail:
    msg: "The variable 'sap_hana_install_sid' is not defined."
  when: sap_hana_install_sid | length == 0
  tags:
    - sap_hana_install_check_hana_exists
    - sap_hana_install_preinstall

- name: Validate SAP HANA System ID - 'sap_hana_install_sid' consists of 3 characters
  ansible.builtin.assert:
    that: sap_hana_install_sid | length == 3
    success_msg: "PASS: The length of the SAP System ID '{{ sap_hana_install_sid }}' is 3 characters."
    fail_msg: "FAIL: The length of the SAP HANA System ID '{{ sap_hana_install_sid }}' is not 3 characters!"
  tags:
    - sap_hana_install_check_hana_exists
    - sap_hana_install_preinstall

- name: Validate SAP HANA System ID - 'sap_hana_install_sid' is not in the list of reserved SAP SIDs
  ansible.builtin.assert:
    that: sap_hana_install_sid not in __sap_hana_install_sid_prohibited
    success_msg: "PASS: The SAP HANA System ID '{{ sap_hana_install_sid }}' is not in the list of reserved SAP SIDs in SAP note 1979280 v.20."
    fail_msg: "FAIL: The SAP HANA System ID '{{ sap_hana_install_sid }}' is in the list of reserved SAP SIDs in SAP note 1979280 v.20!"
  tags:
    - sap_hana_install_check_hana_exists
    - sap_hana_install_preinstall

- name: Fail if necessary variable 'sap_hana_install_number' is not defined
  ansible.builtin.fail:
    msg: "The variable 'sap_hana_install_number' is not defined."
  when: sap_hana_install_number | length == 0
  tags:
    - sap_hana_install_check_hana_exists
    - sap_hana_install_preinstall

- name: SAP HANA existence checking
  ansible.builtin.import_tasks: hana_exists.yml
  when:
    - sap_hana_install_new_system | d(true)
    - not sap_hana_install_force | d(false)
  tags:
    - sap_hana_install_check_hana_exists
    - sap_hana_install_preinstall

- name: Install SAP HANA
  when: not __sap_hana_install_fact_is_installed | d(false)
  block:

    - name: SAP HANA pre-install steps
      ansible.builtin.import_tasks: pre_install.yml
      tags: sap_hana_install_preinstall

    - name: SAP HANA installation steps
      ansible.builtin.import_tasks: hana_install.yml
      when: sap_hana_install_new_system | d(true)

    - name: SAP HANA addhosts steps
      ansible.builtin.import_tasks: hana_addhosts.yml
      when: not sap_hana_install_new_system | d(true)

    - name: SAP HANA post-install steps
      ansible.builtin.import_tasks: post_install.yml
