# SPDX-License-Identifier: Apache-2.0
---

- name: Display the role path
  ansible.builtin.debug:
    var: role_path

# Load variable files in order:
# 1. Suse.yml / RedHat.yml - Specific to OS family.
# 2. SLES_15.yml / RedHat_9.yml - Specific to distribution (SLES, SLES_SAP or RedHat) and major release.
# 3. SLES_15.6.yml / RedHat_9.2 - Specific to distribution (SLES, SLES_SAP or RedHat) and minor release.
# 4. SLES_SAP_15.yml - Specific to distribution SLES_SAP and major release.
# 5. SLES_SAP_15.6.yml - Specific to distribution SLES_SAP and minor release.
- name: Include OS specific vars, specific
  ansible.builtin.include_vars: "{{ __vars_file }}"
  loop: "{{ __var_files }}"
  vars:
    __vars_file: "{{ role_path }}/vars/{{ item }}"
    __distribution_major: "{{ ansible_distribution ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_minor: "{{ ansible_distribution ~ '_' ~ ansible_distribution_version }}"
    # Enables loading of shared vars between SLES and SLES_SAP
    __distribution_major_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_minor_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_version }}"
    __var_files: >-
      {{
        [
          ansible_os_family ~ '.yml',
          (ansible_distribution ~ '.yml') if ansible_distribution != ansible_os_family else None,
          (__distribution_major_split ~ '.yml') if __distribution_major_split != __distribution_major else None,
          (__distribution_minor_split ~ '.yml') if __distribution_minor_split != __distribution_minor else None,
          __distribution_major ~ '.yml',
          __distribution_minor ~ '.yml'
        ] | select('defined') | select('string') | list
      }}
  when: __vars_file is file
  tags:
    - always


- name: Set filename prefix to empty string if role is run in normal mode
  ansible.builtin.set_fact:
    assert_prefix: ""
  when: not sap_netweaver_preconfigure_assert | d(false)

- name: Prepend filename with assert string if role is run in assert mode
  ansible.builtin.set_fact:
    assert_prefix: "assert-"
  when: sap_netweaver_preconfigure_assert | d(false)


- name: Include tasks from 'installation.yml'
  ansible.builtin.include_tasks: '{{ item }}/{{ assert_prefix }}installation.yml'
  when: sap_netweaver_preconfigure_config_all|d(true) or sap_netweaver_preconfigure_installation|d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'

- name: Include tasks from 'configuration.yml'
  ansible.builtin.include_tasks: '{{ item }}/{{ assert_prefix }}configuration.yml'
  when: sap_netweaver_preconfigure_config_all|d(true) or sap_netweaver_preconfigure_configuration|d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'
