# SPDX-License-Identifier: Apache-2.0
---
- name: Ansible Play for executing SAP HANA installation to all hosts in Ansible Inventory
  hosts: all
  become: true
  pre_tasks:
    - name: Include variables
      ansible.builtin.include_vars: ./vars/sample-variables-sap-hana-install.yml
  roles:
    - { role: ../roles/sap_hana_install }
