# SPDX-License-Identifier: Apache-2.0
---
# Ansible Playbook for executing sap_swpm Ansible in "Default Templates Mode"

- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true

  vars:
    sap_swpm_ansible_role_mode: default_templates
#    sap_swpm_templates_product_input: sap_system_rename
#    sap_swpm_templates_product_input: sap_s4hana_2020_onehost_install
#    sap_swpm_templates_product_input: sap_s4hana_2020_onehost_system_restore

  tasks:

    - name: Import variables for sap_swpm Ansible Role (Default Templates Mode)
      ansible.builtin.include_vars:
        file: ./sample-variables-sap-swpm-default-templates-mode.yml

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_install_media_detect }

    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_swpm }
