# SPDX-License-Identifier: Apache-2.0
---
# Ansible Playbook for executing sap_swpm Ansible in "Advanced Mode"

- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true

  vars:
    sap_swpm_ansible_role_mode: advanced

  tasks:

    - name: Import variables for sap_swpm Ansible Role (Advanced Mode)
      ansible.builtin.include_vars:
#        file: ./sample-variables-sap-swpm-advanced-mode-s4hana-install.yml

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_install_media_detect }

    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_swpm }
