# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "kernel.numa_balancing = 0"
- name: Assert 3562919-4
  ansible.builtin.debug:
    msg: "SAP note 3562919 Step 4: Turn off auto-numa balancing"

- name: Import ../../RedHat/generic/assert-auto-numa-balancing.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-auto-numa-balancing.yml
