# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "transparent_hugepages=never"
- name: Assert 3562919-5
  ansible.builtin.debug:
    msg: "SAP note 3562919 Step 5: Configure Transparent Hugepages (THP)"

- name: Import ../../RedHat/generic/assert-thp.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-thp.yml
