# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "force_latency=70"
- name: Configure 3562919-6
  ansible.builtin.debug:
    msg: "SAP note 3562919 Step 6: Configure C-States for lower latency (x86_64 platform only)"

- name: Import ../../RedHat/generic/configure-c-states-for-lower-latency.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/configure-c-states-for-lower-latency.yml
