# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "governor=performance"
#   in included tuned profile throughput-performance
- name: Assert 3562919-7
  ansible.builtin.debug:
    msg: "SAP note 3562919 Step 7: Configure CPU Governor for performance (x86_64 platform only)"

- name: Import ../../RedHat/generic/assert-cpu-governor-for-performance.yml
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-cpu-governor-for-performance.yml
