# SPDX-License-Identifier: Apache-2.0
---

- name: Configure 3562919-10
  ansible.builtin.debug:
    msg: "SAP note 3562919 Step 10: Increase kernel.pidmax"

- name: Notify about where 'kernel.pid_max' is set
  ansible.builtin.debug:
    msg: "Kernel parameter 'kernel.pid_max' is already set by role 'sap_general_preconfigure' if necessary."
