# SPDX-License-Identifier: Apache-2.0
---
# The following tasks will check which SAP landscape can be configured with
# the provided parameters.
# It will validate if requirements are met for the cluster configuration.

# TODO: fail if there is only one host in the play?
# TODO: check play hosts against cluster nodes definition - there should be no
#       hosts in the play that are undefined?

# 2 nodes are also valid for other scenarios.
# TODO: collect possible rules for target landscapes

- name: "SAP HA Prepare Pacemaker - Fail if there is only 1 target host"
  ansible.builtin.assert:
    that:
      - ansible_play_hosts | length > 1

- name: "SAP HA Prepare Pacemaker - Make sure the 'type' parameter is a list"
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_host_type: |
      {% if sap_ha_pacemaker_cluster_host_type | type_debug != 'list' -%}
        {{ sap_ha_pacemaker_cluster_host_type | split(' ') }}
      {%- else -%}
        {{ sap_ha_pacemaker_cluster_host_type }}
      {%- endif %}

- name: "SAP HA Prepare Pacemaker - Verify that for 'hana_scaleup' types 2 nodes are used"
  ansible.builtin.assert:
    that:
      - ansible_play_hosts | length == 2
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana_scaleup') | length > 0

# Host type rules:
# - there can only be 0 or 1 HANA type in the list
# - there can only be 0 or 1 NW (A)SCS/ERS type in the list
- name: "SAP HA Prepare Pacemaker - Make sure that the host_type combination is valid"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length < 2
      - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_.*_ers') | length < 2
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}

      Conflicting host types found!
      There can only be max. 1 HANA and/or 1 NWAS (A)SCS/ERS type in the same definition.

- name: "SAP HA Prepare Pacemaker - Include HANA specific variables"
  ansible.builtin.include_tasks:
    file: include_vars_hana.yml
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0

- name: "SAP HA Prepare Pacemaker - Include NETWEAVER specific variables"
  tags: nwas_postinst
  ansible.builtin.include_tasks:
    file: include_vars_nwas.yml
    apply:
      tags: nwas_postinst
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas') | length > 0
