---
# After all of the previous construction flows, the final parameters must
# be translated to 'ha_cluster' Linux System Role syntax.
#
# This way the include_role parameters are set as play vars and do not
# require a static list of vars when the role is included.

# List of parameters that are constructed by this role, but not all of them
# are mandatory to be defined. For any undefined parameter the default of the
# 'ha_cluster' role will apply, if the role has a default defined.
#
# Make sure to always define those parameters which have no 'ha_cluster' LSR default!
#
# SAP HA Pacemaker Cluster role                 -> 'ha_cluster' Linux System Role
# ------------------------------------------------------------------------------
# __sap_ha_pacemaker_cluster_ha_cluster             ha_cluster
# __sap_ha_pacemaker_cluster_cluster_name           ha_cluster_cluster_name
# __sap_ha_pacemaker_cluster_cluster_properties     ha_cluster_cluster_properties
# __sap_ha_pacemaker_cluster_constraints_colocation ha_cluster_constraints_colocation
# __sap_ha_pacemaker_cluster_constraints_location   ha_cluster_constraints_location
# __sap_ha_pacemaker_cluster_constraints_order      ha_cluster_constraints_order
# __sap_ha_pacemaker_cluster_extra_packages         ha_cluster_extra_packages
# __sap_ha_pacemaker_cluster_fence_agent_packages   ha_cluster_fence_agent_packages
# __sap_ha_pacemaker_cluster_hacluster_user_password     ha_cluster_hacluster_password
# __sap_ha_pacemaker_cluster_repos                  __ha_cluster_repos
# __sap_ha_pacemaker_cluster_resource_clones        ha_cluster_resource_clones
# __sap_ha_pacemaker_cluster_resource_groups        ha_cluster_resource_groups
# __sap_ha_pacemaker_cluster_resource_primitives    ha_cluster_resource_primitives

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster'"
  when: __sap_ha_pacemaker_cluster_ha_cluster is defined
  ansible.builtin.set_fact:
    ha_cluster: "{{ __sap_ha_pacemaker_cluster_ha_cluster }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_cluster_name'"
  when: __sap_ha_pacemaker_cluster_cluster_name is defined
  ansible.builtin.set_fact:
    ha_cluster_cluster_name: "{{ __sap_ha_pacemaker_cluster_cluster_name }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_cluster_properties'"
  when: __sap_ha_pacemaker_cluster_cluster_properties is defined
  ansible.builtin.set_fact:
    ha_cluster_cluster_properties: "{{ __sap_ha_pacemaker_cluster_cluster_properties }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_constraints_colocation'"
  when: __sap_ha_pacemaker_cluster_constraints_colocation is defined
  ansible.builtin.set_fact:
    ha_cluster_constraints_colocation: "{{ __sap_ha_pacemaker_cluster_constraints_colocation }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_constraints_location'"
  when: __sap_ha_pacemaker_cluster_constraints_location is defined
  ansible.builtin.set_fact:
    ha_cluster_constraints_location: "{{ __sap_ha_pacemaker_cluster_constraints_location }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_constraints_order'"
  when: __sap_ha_pacemaker_cluster_constraints_order is defined
  ansible.builtin.set_fact:
    ha_cluster_constraints_order: "{{ __sap_ha_pacemaker_cluster_constraints_order }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_extra_packages'"
  when: __sap_ha_pacemaker_cluster_extra_packages is defined
  ansible.builtin.set_fact:
    ha_cluster_extra_packages: "{{ __sap_ha_pacemaker_cluster_extra_packages }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_fence_agent_packages'"
  when: __sap_ha_pacemaker_cluster_fence_agent_packages is defined
  ansible.builtin.set_fact:
    ha_cluster_fence_agent_packages: "{{ __sap_ha_pacemaker_cluster_fence_agent_packages }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_hacluster_password'"
  when: __sap_ha_pacemaker_cluster_hacluster_user_password is defined
  ansible.builtin.set_fact:
    ha_cluster_hacluster_password: "{{ __sap_ha_pacemaker_cluster_hacluster_user_password }}"
  no_log: true  # secure the credential

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_repos'"
  when: __sap_ha_pacemaker_cluster_repos is defined
  ansible.builtin.set_fact:
    __ha_cluster_repos: "{{ __sap_ha_pacemaker_cluster_repos }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_resource_clones'"
  when: __sap_ha_pacemaker_cluster_resource_clones is defined
  ansible.builtin.set_fact:
    ha_cluster_resource_clones: "{{ __sap_ha_pacemaker_cluster_resource_clones }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_resource_groups'"
  when: __sap_ha_pacemaker_cluster_resource_groups is defined
  ansible.builtin.set_fact:
    ha_cluster_resource_groups: "{{ __sap_ha_pacemaker_cluster_resource_groups }}"

- name: "SAP HA Prepare Pacemaker - (ha_cluster) Define parameter 'ha_cluster_resource_primitives'"
  when: __sap_ha_pacemaker_cluster_resource_primitives is defined
  ansible.builtin.set_fact:
    ha_cluster_resource_primitives: "{{ __sap_ha_pacemaker_cluster_resource_primitives }}"
  no_log: true  # be paranoid, there could be credentials in it
