---
# Combine input parameters with inherited vars from the 'ha_cluster' role.
# The inherited values take precedence. Some parameters are not required to be set.
# The 'ha_cluster' LSR will apply its role defaults.
# For mandatory parameters, sanity checks will be done separately.

# sap_ha_pacemaker_cluster_cluster_name   -> user-defined or default inherited from {{ ha_cluster_cluster_name }}
- name: "SAP HA Prepare Pacemaker - Set cluster name"
  when:
    - __sap_ha_pacemaker_cluster_cluster_name is not defined
    - sap_ha_pacemaker_cluster_cluster_name is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_cluster_name: "{{ sap_ha_pacemaker_cluster_cluster_name }}"

# sap_ha_pacemaker_cluster_hacluster_user_password -> user-defined or default inherited from {{ ha_cluster_hacluster_password }}
- name: "SAP HA Prepare Pacemaker - Register the 'hacluster' user password"
  when:
    - __sap_ha_pacemaker_cluster_hacluster_user_password is not defined
    - sap_ha_pacemaker_cluster_hacluster_user_password
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hacluster_user_password: "{{ sap_ha_pacemaker_cluster_hacluster_user_password }}"
  no_log: true  # secure the credential


# sap_ha_pacemaker_cluster_extra_packages             -> user-defined, empty by global default
# __sap_ha_pacemaker_cluster_sap_extra_packages       -> included from vars/*
# __sap_ha_pacemaker_cluster_platform_extra_packages  -> included from vars/platform*

- name: "SAP HA Prepare Pacemaker - Combine extra packages lists"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_extra_packages: "{{ (
      sap_ha_pacemaker_cluster_extra_packages
      + __sap_ha_pacemaker_cluster_sap_extra_packages
      + __sap_ha_pacemaker_cluster_platform_extra_packages
    ) | unique | select() }}"
  # remove duplicates and empty elements

# sap_ha_pacemaker_cluster_fence_agent_minimal_packages -> global default
# sap_ha_pacemaker_cluster_fence_agent_packages         -> global default
# __sap_ha_pacemaker_cluster_fence_agent_packages       -> internal default (vars/main.yml)

- name: "SAP HA Prepare Pacemaker - Combine fence agent packages lists"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_fence_agent_packages: "{{ (
      sap_ha_pacemaker_cluster_fence_agent_minimal_packages
      + sap_ha_pacemaker_cluster_fence_agent_packages
      + __sap_ha_pacemaker_cluster_fence_agent_packages
    ) | unique }}"
