# SPDX-License-Identifier: Apache-2.0
---
# Reminder: This file is included in a loop over a dictionary.

# Start haproxy only after the HANA resource has been promoted
- name: "SAP HA Prepare Pacemaker - Add order constraint: 'haproxy' starts after DB is promoted"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_order: "{{ __sap_ha_pacemaker_cluster_constraints_order + [__constraint_order_haproxy] }}"
  vars:
    __constraint_order_haproxy:
      resource_first:
        id: "{{ __sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        action: promote
      resource_then:
        id: "{{ vip_list_item.key }}"
        action: start
  when:
    - __constraint_order_haproxy.resource_then not in (__sap_ha_pacemaker_cluster_constraints_order | map(attribute='resource_then'))

# The primary haproxy only runs where HANA is promoted
- name: "SAP HA Prepare Pacemaker - Add colocation constraint: Primary 'haproxy' runs where HANA is promoted"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_colocation: "{{ __sap_ha_pacemaker_cluster_constraints_colocation + [__constraint_colo_haproxy] }}"
  vars:
    __constraint_colo_haproxy:
      resource_leader:
        id: "{{ __sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        role: promoted
      resource_follower:
        id: "{{ __sap_ha_pacemaker_cluster_vip_hana_primary_resource_name }}"
      options:
        - name: score
          value: "{{ sap_ha_pacemaker_cluster_constraint_colo_base_score }}"
  when:
    - __constraint_colo_haproxy.resource_follower not in (__sap_ha_pacemaker_cluster_constraints_colocation | map(attribute='resource_follower'))

# The secondary haproxy only runs where HANA is UNpromoted
- name: "SAP HA Prepare Pacemaker - Add colocation constraint: Secondary 'haproxy' runs where HANA is not promoted"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_colocation: "{{ __sap_ha_pacemaker_cluster_constraints_colocation + [__constraint_colo_haproxy] }}"
  vars:
    __constraint_colo_haproxy:
      resource_leader:
        id: "{{ __sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        role: unpromoted
      resource_follower:
        id: "{{ __sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name }}"
      options:
        - name: score
          value: "{{ sap_ha_pacemaker_cluster_constraint_colo_base_score }}"
  when:
    - __constraint_colo_haproxy.resource_follower not in (__sap_ha_pacemaker_cluster_constraints_colocation | map(attribute='resource_follower'))
    - __sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address is defined
    - __sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address != ''
