---
# The following variables are constructed here in order to be provided as
# input for the included 'ha_cluster' system role.

### Block for disabling stonith when no stonith resource definition is found
#
# This block is entered when
# - no default stonith resource is defined and no custom is defined either
# - an empty custom is defined to override any default (defined or not)
- name: "SAP HA Prepare Pacemaker - (STONITH) Block when no STONITH resource is defined"
  when:
    - (
        sap_ha_pacemaker_cluster_stonith_custom is defined
        and
        (
          sap_ha_pacemaker_cluster_stonith_custom == ''
          or sap_ha_pacemaker_cluster_stonith_custom | length == 0
        )
      )
      or
      (
        sap_ha_pacemaker_cluster_stonith_custom is not defined
        and sap_ha_pacemaker_cluster_stonith_default is defined
        and
        (
          sap_ha_pacemaker_cluster_stonith_default == ''
          or sap_ha_pacemaker_cluster_stonith_default | length == 0
        )
      )
      or
      (
        sap_ha_pacemaker_cluster_stonith_custom is not defined
        and sap_ha_pacemaker_cluster_stonith_default is not defined
      )
  block:

    - name: "SAP HA Prepare Pacemaker - (STONITH) Set to disabled when no fencing resource is defined"
      ansible.builtin.set_fact:
        sap_ha_pacemaker_cluster_cluster_properties:
          "{{ sap_ha_pacemaker_cluster_cluster_properties | combine({ 'stonith-enabled': false }) }}"

    - name: "SAP HA Prepare Pacemaker - Warn that there is no STONITH configured"
      ansible.builtin.pause:
        seconds: 5
        prompt: |

          WARNING: No STONITH resource is defined and STONITH is disabled!

          Recommendation: Add a STONITH resource and set cluster property
                          "stonith-enabled=true"
                          before using this cluster for production services.

# END of block for disabling stonith


- name: "SAP HA Prepare Pacemaker - (STONITH) Define cluster properties"
  when:
    - sap_ha_pacemaker_cluster_cluster_properties is defined
    - sap_ha_pacemaker_cluster_cluster_properties is iterable
    - sap_ha_pacemaker_cluster_cluster_properties | length > 0
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_cluster_properties: "{{ __sap_ha_pacemaker_cluster_cluster_properties | default([]) + __stonith_properties }}"
  vars:
    __stonith_properties:
      - attrs: |-
          {% set attrs = __sap_ha_pacemaker_cluster_cluster_properties | map(attribute='attrs') | flatten -%}
          {%- for default_cluster_properties in (sap_ha_pacemaker_cluster_cluster_properties | dict2items) -%}
            {% if default_cluster_properties.key not in
            (__sap_ha_pacemaker_cluster_cluster_properties | map(attribute='attrs') | flatten | map(attribute='name')) -%}
              {% set role_attrs = attrs.extend([
                {
                  'name': default_cluster_properties.key,
                  'value': default_cluster_properties.value
                }
              ]) -%}
            {%- endif %}
          {%- endfor %}
          {{ attrs }}

# Combine the default stonith resource config from
# - assembled pcmk_host_map
#   (see platform tasks: __sap_ha_pacemaker_cluster_pcmk_host_map)
# - fence agent specific required options
#   (see platform vars: sap_ha_pacemaker_cluster_stonith_default)
# - generic pacemaker fence resource options
#   (see defaults: sap_ha_pacemaker_cluster_fence_options)

- name: "SAP HA Prepare Pacemaker - (STONITH) Assemble the resource definition from platform default"
  when:
    - sap_ha_pacemaker_cluster_stonith_default is defined
    - sap_ha_pacemaker_cluster_stonith_custom is not defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_stonith_resource: "{{ __sap_ha_pacemaker_cluster_stonith_resource | default([]) + [__stonith_resource_element] }}"
  vars:
    __stonith_resource_element:
      id: "{{ sap_ha_pacemaker_cluster_stonith_default.id }}"
      agent: "{{ sap_ha_pacemaker_cluster_stonith_default.agent }}"
      instance_attrs:
        - attrs: |-
            {% set attrs = [] -%}
            {% set map = attrs.extend([
              {
                'name': 'pcmk_host_map',
                'value': __sap_ha_pacemaker_cluster_pcmk_host_map
              }]) -%}
            {%- for agent_opt in (sap_ha_pacemaker_cluster_stonith_default.options | default({}) | dict2items) -%}
              {% set aopts = attrs.extend([
                {
                  'name': agent_opt.key,
                  'value': agent_opt.value
                }]) -%}
            {%- endfor %}
            {%- for fence_opt in (sap_ha_pacemaker_cluster_fence_options | dict2items) -%}
              {% set fopts = attrs.extend([
                {
                  'name': fence_opt.key,
                  'value': fence_opt.value
                }]) -%}
              {%- endfor %}
            {{ attrs }}

- name: "SAP HA Prepare Pacemaker - (STONITH) Assemble the resources from custom definition"
  when:
    - sap_ha_pacemaker_cluster_stonith_custom is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_stonith_resource: "{{ __sap_ha_pacemaker_cluster_stonith_resource | default([]) + [__stonith_resource_element] }}"
  vars:
    __stonith_resource_element:
      id: "res_{{ item.name }}"
      agent: "{{ item.agent }}"
      instance_attrs:
        - attrs: |-
            {% set attrs = [] -%}
            {%- for option in (item.options | dict2items) -%}
              {% set aopts = attrs.extend([
                {
                  'name': option.key,
                  'value': option.value
                }
              ]) -%}
            {%- endfor %}
            {{ attrs }}
  loop: "{{ sap_ha_pacemaker_cluster_stonith_custom }}"
  loop_control:
    label: "{{ item.name }}"


# The STONITH resource is an element in the cluster_resource_primitives list
- name: "SAP HA Prepare Pacemaker - (STONITH) Construct resources definition"
  when:
    - __sap_ha_pacemaker_cluster_stonith_resource is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: |-
      {{
        __sap_ha_pacemaker_cluster_resource_primitives
        +
        (__sap_ha_pacemaker_cluster_stonith_resource | from_yaml)
      }}
  no_log: true  # stonith resources usually contain secrets
