---
# Variables containing variables must be constructed with values
# to be fed into the included ha_cluster role

# TODO: add conditionals to verify that the same resource agent is not already
#       defined in user input variables. Conflicting user input should take precedence.

# Prepare default resource defaults
- name: "SAP HA Prepare Pacemaker - Define resource defaults for HANA clusters"
  when:
    - sap_ha_pacemaker_cluster_resource_defaults is not defined
      or sap_ha_pacemaker_cluster_resource_defaults | length == 0
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_resource_defaults:
      resource-stickiness: 1000
      migration-threshold: 5000

# Convert dictionary into ha_cluster format.
- name: "SAP HA Prepare Pacemaker - prepare resource defaults for ha_cluster"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_defaults: "{{ __resource_defaults }}"
  vars:
    __resource_defaults:
      meta_attrs:
        - attrs: |-
            {% set attrs = __sap_ha_pacemaker_cluster_resource_defaults.meta_attrs | map(attribute='attrs') | flatten -%}
            {%- for resource_default in (sap_ha_pacemaker_cluster_resource_defaults | dict2items) -%}
              {% if resource_default.key not in
              (__sap_ha_pacemaker_cluster_resource_defaults.meta_attrs  | map(attribute='attrs') | flatten | map(attribute='name')) -%}
                {% set role_attrs = attrs.extend([
                  {
                    'name': resource_default.key,
                    'value': resource_default.value
                  }
                ]) -%}
              {%- endif %}
            {%- endfor %}
            {{ attrs }}


# Prepare default resource operation defaults
- name: "SAP HA Prepare Pacemaker - Define operation defaults for HANA clusters"
  when:
    - sap_ha_pacemaker_cluster_operation_defaults is not defined
      or sap_ha_pacemaker_cluster_operation_defaults | length == 0
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_operation_defaults:
      timeout: 600
      record-pending: true

# Convert dictionary into ha_cluster format.
- name: "SAP HA Prepare Pacemaker - prepare operation defaults for ha_cluster"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_operation_defaults: "{{ __operation_defaults }}"
  vars:
    __operation_defaults:
      meta_attrs:
        - attrs: |-
            {% set attrs = __sap_ha_pacemaker_cluster_resource_operation_defaults.meta_attrs  | map(attribute='attrs') | flatten -%}
            {%- for operation_default in (sap_ha_pacemaker_cluster_operation_defaults | dict2items) -%}
              {% if operation_default.key not in
              (__sap_ha_pacemaker_cluster_resource_operation_defaults.meta_attrs  | map(attribute='attrs') | flatten | map(attribute='name')) -%}
                {% set role_attrs = attrs.extend([
                  {
                    'name': operation_default.key,
                    'value': operation_default.value
                  }
                ]) -%}
              {%- endif %}
            {%- endfor %}
            {{ attrs }}
