---
# If there are "ha_cluster" Linux System Role parameters already defined in the
# inventory, we will include these custom specifications and they take precedence.

# Only parameters which need to be adjusted or enhanced by the SAP HA role
# need to be included here.


### Take the following template to add additional parameters to be inherited:
# - name: "SAP HA Prepare Pacemaker - Register ha_cluster_"
#   ansible.builtin.set_fact:
#     __sap_ha_pacemaker_cluster_: "{{ ha_cluster_ }}"
#   when: ha_cluster_ is defined


# ha_cluster
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster'"
  when: ha_cluster is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_ha_cluster: "{{ ha_cluster }}"

# ha_cluster_cluster_name
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_cluster_name'"
  when: ha_cluster_cluster_name is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_cluster_name: "{{ ha_cluster_cluster_name }}"

# ha_cluster_cluster_properties
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_cluster_properties'"
  when: ha_cluster_cluster_properties is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_cluster_properties: "{{ ha_cluster_cluster_properties }}"

#__sap_ha_pacemaker_cluster_resource_groups ha_cluster_constraints_colocation
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_constraints_colocation'"
  when: ha_cluster_constraints_colocation is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_colocation: "{{ ha_cluster_constraints_colocation }}"

# ha_cluster_constraints_location
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_constraints_location'"
  when: ha_cluster_constraints_location is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_location: "{{ ha_cluster_constraints_location }}"

# ha_cluster_constraints_order
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_constraints_order'"
  when: ha_cluster_constraints_order is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_order: "{{ ha_cluster_constraints_order }}"

# ha_cluster_extra_packages
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_extra_packages'"
  when: ha_cluster_extra_packages is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_extra_packages: "{{ ha_cluster_extra_packages }}"

# ha_cluster_fence_agent_packages
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_fence_agent_packages'"
  when: ha_cluster_fence_agent_packages is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_fence_agent_packages: "{{ ha_cluster_fence_agent_packages }}"

# ha_cluster_hacluster_password
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_repos'"
  when: ha_cluster_hacluster_password is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hacluster_user_password: "{{ ha_cluster_hacluster_password }}"
  no_log: true  # handle credentials with care

# ha_cluster_repos
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_repos'"
  when: ha_cluster_repos is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_repos: "{{ ha_cluster_repos }}"

# ha_cluster_resource_clones
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_resource_clones'"
  when: ha_cluster_resource_clones is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_clones: "{{ ha_cluster_resource_clones }}"

# ha_cluster_resource_groups
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_resource_groups'"
  when: ha_cluster_resource_groups is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_groups: "{{ ha_cluster_resource_groups }}"

# ha_cluster_resource_primitives
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_resource_primitives'"
  when: ha_cluster_resource_primitives is defined
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_primitives: "{{ ha_cluster_resource_primitives }}"
  no_log: true  # be paranoid, there could be credentials in it
