---
- name: SAP HA Prepare Pacemaker - Include NETWEAVER landscape specific variables
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ include_item }}.yml"
  loop: "{{ __host_type_list | flatten }}"
  loop_control:
    loop_var: include_item
    label: "{{ include_item }}.yml"
  vars:
    __host_type_list:
      - nwas_common
      - "{{ sap_ha_pacemaker_cluster_host_type }}"
  when:
    - "(role_path + '/vars/' + include_item + '.yml') is file"
