# SPDX-License-Identifier: Apache-2.0
---
# Gather specific subsets of facts if the required facts are not yet available.
- name: "SAP HA Prepare Pacemaker - Collect required facts"
  when:
    - not ansible_facts.keys() | list |
      intersect(__sap_ha_pacemaker_cluster_required_facts) == __sap_ha_pacemaker_cluster_required_facts
  ansible.builtin.setup:
    gather_subset: hardware,interfaces

# Multi-NIC:
# Find out if there is more than one interface present, this will
# be used for determining the target NIC for VIP configurations.
# Assumption: The local loopback "lo" is always in the list.
- name: "SAP HA Prepare Pacemaker - Set multi-NIC when more than one interface is found"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_nic_multi_bool: true
  when:
    - ansible_interfaces | length > 2

- name: "SAP HA Prepare Pacemaker - Set interface name when only one interface is present"
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_vip_client_interface: "{{ ansible_default_ipv4.interface }}"
  when:
    - not __sap_ha_pacemaker_cluster_nic_multi_bool
    - sap_ha_pacemaker_cluster_vip_client_interface == ''


# Load variable files in order:
# 1. Suse.yml / RedHat.yml - Specific to OS family.
# 2. SLES_15.yml / RedHat_9.yml - Specific to distribution (SLES, SLES_SAP or RedHat) and major release.
# 3. SLES_15.6.yml / RedHat_9.2 - Specific to distribution (SLES, SLES_SAP or RedHat) and minor release.
# 4. SLES_SAP_15.yml - Specific to distribution SLES_SAP and major release.
# 5. SLES_SAP_15.6.yml - Specific to distribution SLES_SAP and minor release.
- name: "SAP HA Prepare Pacemaker - Include environment specific variables"
  ansible.builtin.include_vars: "{{ __vars_file }}"
  loop: "{{ __var_files }}"
  vars:
    __vars_file: "{{ role_path }}/vars/{{ item }}"
    __distribution_major: "{{ ansible_distribution ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_minor: "{{ ansible_distribution ~ '_' ~ ansible_distribution_version }}"
    # Enables loading of shared vars between SLES and SLES_SAP
    __distribution_major_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_major_version }}"
    __distribution_minor_split: "{{ ansible_distribution.split('_')[0] ~ '_' ~ ansible_distribution_version }}"
    __var_files: >-
      {{
        [
          ansible_os_family ~ '.yml',
          (ansible_distribution ~ '.yml') if ansible_distribution != ansible_os_family else None,
          (__distribution_major_split ~ '.yml') if __distribution_major_split != __distribution_major else None,
          (__distribution_minor_split ~ '.yml') if __distribution_minor_split != __distribution_minor else None,
          __distribution_major ~ '.yml',
          __distribution_minor ~ '.yml'
        ] | select('defined') | select('string') | list
      }}
  when: __vars_file is file
