# SPDX-License-Identifier: Apache-2.0
---
# The SAP ID must follow a strict format and not use reserved special values
- name: "SAP HA Prepare Pacemaker - (SAP HANA) Validate SAP System ID"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_hana_sid | length == 3
      - __sap_ha_pacemaker_cluster_hana_sid not in __sap_ha_pacemaker_cluster_sid_prohibited
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Requires: 'sap_ha_pacemaker_cluster_hana_sid' to be defined as 3 capital letters!
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0

- name: "SAP HA Prepare Pacemaker - (SAP HANA) Validate SAP Instance Number"
  ansible.builtin.assert:
    that:
      - (__sap_ha_pacemaker_cluster_hana_instance_nr | string) | length == 2
      - (__sap_ha_pacemaker_cluster_hana_instance_nr | string) is match('^[0-9]{2}$')
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Requires: 'sap_ha_pacemaker_cluster_hana_instance_nr' to be defined.

      The instance number must be exactly 2 digits.
      Add quotes if the number starts with a 0!
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0


- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver) Validate SAP System ID"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_nwas_sid | length == 3
      - __sap_ha_pacemaker_cluster_nwas_sid not in __sap_ha_pacemaker_cluster_sid_prohibited
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Current value: {{ __sap_ha_pacemaker_cluster_nwas_sid }}
      Requires: 'sap_ha_pacemaker_cluster_nwas_sid' to be defined as 3 capital letters!
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas') | length > 0


# Validate SAP Instance Number
- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver) Validate SAP Instance Number"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas') | length > 0
    - __instance_nr | length > 0
  ansible.builtin.assert:
    that:
      - (__instance_nr | string) | length == 2
      - (__instance_nr | string) is match('^[0-9]{2}$')
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      The instance number must be exactly 2 digits.
      Add quotes if the number starts with a 0!

      Required:
      {% if sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0 %}
      - sap_ha_pacemaker_cluster_nwas_ascs_instance_nr
      - sap_ha_pacemaker_cluster_nwas_ers_instance_nr

      {% elif sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0 %}
      - sap_ha_pacemaker_cluster_nwas_scs_instance_nr
      - sap_ha_pacemaker_cluster_nwas_ers_instance_nr

      {% elif sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_pas_aas') | length > 0 %}
      - sap_ha_pacemaker_cluster_nwas_abap_pas_instance_nr
      - sap_ha_pacemaker_cluster_nwas_abap_aas_instance_nr

      {% else %}
      Invalid sap_ha_pacemaker_cluster_host_type provided.
      {% endif %}

  loop:
    - __sap_ha_pacemaker_cluster_nwas_ascs_instance_nr
    - __sap_ha_pacemaker_cluster_nwas_scs_instance_nr
    - __sap_ha_pacemaker_cluster_nwas_ers_instance_nr
    # - __sap_ha_pacemaker_cluster_nwas_abap_pas_instance_nr
    # - __sap_ha_pacemaker_cluster_nwas_abap_aas_instance_nr
  loop_control:
    loop_var: item
  vars:
    __instance_nr: "{{ lookup('ansible.builtin.vars', item) }}"


# Ensure that storage definition is provided for Filesystem based scenarios
- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver) Validate storage definition"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas') | length > 0
    - not __sap_ha_pacemaker_cluster_nwas_cs_ers_simple_mount
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_storage_definition is defined
      - sap_ha_pacemaker_cluster_storage_definition | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Classic cluster without Simple Mount requires:
      - sap_ha_pacemaker_cluster_storage_definition


# Ensure that SAP profile names are defined
- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver ASCS) Validate SAP instance name"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_nwas_ascs_sapinstance_instance_name is defined
      - __sap_ha_pacemaker_cluster_nwas_ascs_sapinstance_instance_name | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      ASCS Instance Name is mandatory: sap_ha_pacemaker_cluster_nwas_ascs_sapinstance_instance_name

- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver SCS) Validate SAP instance name"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_nwas_scs_sapinstance_instance_name is defined
      - __sap_ha_pacemaker_cluster_nwas_scs_sapinstance_instance_name | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      SCS Instance Name is mandatory: sap_ha_pacemaker_cluster_nwas_scs_sapinstance_instance_name

- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver ERS) Validate SAP instance name"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0
      or sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_nwas_ers_sapinstance_instance_name is defined
      - __sap_ha_pacemaker_cluster_nwas_ers_sapinstance_instance_name | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      ERS Instance Name is mandatory: sap_ha_pacemaker_cluster_nwas_ers_sapinstance_instance_name


# NIC definition validation
- name: "SAP HA Prepare Pacemaker - Verify that a custom NIC name is defined when multiple NICs exist"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_client_interface is defined
      - sap_ha_pacemaker_cluster_vip_client_interface | length > 0
    fail_msg: |
      Multiple interfaces are found on the system.

      {{ ansible_interfaces | to_nice_yaml }}

      In this case 'sap_ha_pacemaker_cluster_vip_client_interface' must be defined.
  when:
    - ansible_interfaces | length > 2

- name: "SAP HA Prepare Pacemaker - Verify that the custom NIC name exists"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_client_interface in ansible_interfaces
    fail_msg: "The interface '{{ sap_ha_pacemaker_cluster_vip_client_interface }}' does not exist on this system!"
  when:
    - sap_ha_pacemaker_cluster_vip_client_interface | length > 0

# VIP definition validation
- name: "SAP HA Prepare Pacemaker - (HANA primary) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_vip_hana_primary_ip_address is defined
      - __sap_ha_pacemaker_cluster_vip_hana_primary_ip_address | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Required input 'sap_ha_pacemaker_cluster_vip_hana_primary_ip_address' is not defined or empty.
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver ASCS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_vip_nwas_ascs_ip_address is defined
      - __sap_ha_pacemaker_cluster_vip_nwas_ascs_ip_address | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Required input 'sap_ha_pacemaker_cluster_vip_nwas_ascs_ip_address' is not defined or empty.
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver SCS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_vip_nwas_scs_ip_address is defined
      - __sap_ha_pacemaker_cluster_vip_nwas_scs_ip_address | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Required input 'sap_ha_pacemaker_cluster_vip_nwas_scs_ip_address' is not defined or empty.
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver ERS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_vip_nwas_ers_ip_address is defined
      - __sap_ha_pacemaker_cluster_vip_nwas_ers_ip_address | length > 0
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Required input 'sap_ha_pacemaker_cluster_vip_nwas_ers_ip_address' is not defined or empty.
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0
      or sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_java_scs_ers') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver PAS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_vip_nwas_abap_pas_ip_address is defined
      - __sap_ha_pacemaker_cluster_vip_nwas_abap_pas_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_nwas_abap_pas_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_pas') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver AAS) Verify that the ERS VIP is defined"
  ansible.builtin.assert:
    that:
      - __sap_ha_pacemaker_cluster_vip_nwas_abap_aas_ip_address is defined
      - __sap_ha_pacemaker_cluster_vip_nwas_abap_aas_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_nwas_abap_aas_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_pas_aas') | length > 0
